### ISSUE TITLE
multiple options/arguments

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#100]
how do i create multiple options/arguments?

**Comment by LordOfPolls** [comment]
So if we take the example code from the docs, here we see one option being added (https://discord-py-slash-command.readthedocs.io/en/latest/gettingstarted.html?highlight=options#getting-started)
```python
@slash.slash(
  name="test",
  description="this returns the bot latency",
  options=[manage_commands.create_option(
    name = "argone",
    description = "description of first argument",
    option_type = 3,
    required = True
  )],
  guild_ids=guild_ids
)
async def _test(ctx, argone: str):
    await ctx.respond()
    await ctx.send(f"You responded with {argone}.")
```
The options argument is a list, so to add extra options just add another option to the options list:
```python
...
options=[
manage_commands.create_option(
      name= "option 1",
      ...),
manage_commands.create_option(
      name="option 2",
      ...)
]
 ```

**Comment by ghost** [comment]
Thanks :D

**Comment by quirky-bluejay** [comment]
*also for these type of questions it's better to either join the Discord server or open a github discussion*
