### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ashnbrew** [interactions-py/interactions.py#1032]
### Describe the bug.

InvalidArgument was removed (very recently) in discord.py v2.0 
![image](https://user-images.githubusercontent.com/63022201/185832135-3e00bf8d-41e9-4e58-a7f9-29a97b70f877.png)

### List the steps.

1. I updated the version of discord.py

### What you expected.

For there to be no issues.

### What you saw.

![image](https://user-images.githubusercontent.com/63022201/185832345-91659761-8d76-4b19-8115-8f4996b3ed14.png)

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
`interactions.py` v3 and below are no longer supported. Furthermore, those versions only worked with `discord.py` v1.7.X.
