### ISSUE TITLE
[BUG] Outdated link(s) in docs: Quickstart

### ISSUE THREAD

**Issue by DeinAlptraum** [interactions-py/interactions.py#1036]
### Describe the bug.

The link for the text "find these component types here" goes to https://interactionspy.readthedocs.io/en/stable/models.component.html which is a 404. "stable" should be replaced by "latest", then it works. There's also another similarly outdated link for the text "Client", though that one isn't even used as far as I can see.

### List the steps.

1. Go to https://interactionspy.readthedocs.io/en/latest/quickstart.html
2. CTRL+F: "find these"
3. click on the link

### What you expected.

To be directed to https://interactionspy.readthedocs.io/en/latest/models.component.html 

### What you saw.

Got to https://interactionspy.readthedocs.io/en/stable/models.component.html which is a 404

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
It's fine. `latest` is for `unstable` branch

**Comment by Toricane** [comment]
> It's fine. `latest` is for `unstable` branch

No, they're saying the link has `stable` which doesn't exist

**Comment by Damego** [comment]
> > It's fine. `latest` is for `unstable` branch
> 
> No, they're saying the link has `stable` which doesn't exist

But will it be exist in new release?!

**Comment by Damego** [comment]
nvm im bit dumb xD

**Comment by Damego** [comment]
fixed in #1037

**Comment by sillyElvy** [comment]
Resolved as of #1038
