### ISSUE TITLE
[BUG] Channel not set for thread and voice channel chat commands

### ISSUE THREAD

**Issue by lionel-panhaleux** [interactions-py/interactions.py#1041]
### Describe the bug.

The `channel` parameter is `MISSING` when the interaction comes from a thread or a voice channel chat.
This is misleading: we got the ID and initialising a Channel with just ID, type and client would be enough to send messages and do a number of things already.

### List the steps.

1. Create a slash command using `ctx.channel` to (for example) send a message (on top of the interaction response)
2. Use it in a thread

### What you expected.

Be able to send a separate message using the `channel` parameter of the Context.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
    await ctx.channel.send("
AttributeError: type object 'MISSING' has no attribute 'send'
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
Hi!

This is intended behaviour! If you want to use `ctx.channel` make sure you run `await ctx.get_channel()` before it! (same applies for ctx.guild with its own method)
