### ISSUE TITLE
[REQUEST] check if someone has the role to run the Command

### ISSUE THREAD

**Issue by vincyxiroff** [interactions-py/interactions.py#1078]
### Describe the feature.

example: if Carlo has the hello role he can execute the command if he doesn't have the hello role he will not be able to execute the command 

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
This can be implemented like this:

```py
async def func(ctx): #command function
	if hello_role_id not in ctx.author.roles:
		return await ctx.send("You are missing the hello role to run this command", ephemeral=True)
	
	# rest of the command
```

Another possibility would be that you update the bot command permissions in the integration tab of your server or use an extension library.

But there (probably) won't be a decorator to check such things in the main library
