### ISSUE TITLE
[BUG] stacking extension_component() not working

### ISSUE THREAD

**Issue by Donbur4156** [interactions-py/interactions.py#1107]
### Describe the bug.

When trying to stack extension_component decorators, only the first one is reacting.
Stacking of @bot.component(..) works with the same custom_ids as expected.

Don´t work whether in latest nor unstable

Code Main:
```
import interactions
bot = interactions.Client(...)
bot.load("responsefilename")

if __name__ == "__main__":
    bot.start()
```

Code Ext:
```
import interactions
class Response(interactions.Extension):
    def __init__(self, client: interactions.Client) -> None:
        self.client=client

    @interactions.extension_component("resp_1")
    @interactions.extension_component("resp_2")
    ....
    @interactions.extension_component("resp_9")
    async def boost_col_response(self, ctx: interactions.ComponentContext):
       #dostuff

def setup(client):
    Response(client)
```

### List the steps.

1. import interactions in external file and main
2. load ext
3. stack interactions.extension_component("")

### What you expected.

It should react to all custom_ids which defined in the decorators.

### What you saw.

It only react to the custom_id of the very first decorator.

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
Closed as resolved
