### ISSUE TITLE
[BUG] 'BaseResult' conditionally included in subcommand with empty BaseCommand

### ISSUE THREAD

**Issue by g-rar** [interactions-py/interactions.py#1111]
### Describe the bug.

When a SubCommand has an empty base command (it just `pass`es), then depending on the number of options on the subcommand the BaseResult is included into the command coro parameters. This is with the "new system" using the `@command.subcommand` decorator. So here are some specific details of where I found this:

python version: `3.9.11`
interactions version: `4.3.1`

This doesn't feel intentional, my guess is that the idea was that there wouldn't be a BaseResult if the base command didn't `return` a value... So there wouldn't be a BaseResult in any of the examples listed below. And could get in the way of developers trying to add their own parameters in my case via decorators.

**(this is how I found out, steps described here not necessary to replicate):** I stumbled upon this when I was trying to add a parameter to the coro using my own decorator using a keyword, and it tried to include BaseResult as a positional parameter when I wasn't expecting to, causing a `'subcommand()' got multiple values for parameter` because it interpreted the BaseResult as the parameter I also included with the keyword in my decorator.

### List the steps.

1. Imports, Client and scope
```python
import interactions
from interactions.api.models.flags import Intents
from interactions import CommandContext, Option, OptionType

bot = interactions.Client(token=<token>, intents=Intents.ALL)
botGuilds = [<yourTestGuildID>]

@bot.event(name='on_ready')
async def on_ready():
    print("Connected to discord")

```

2. Empty base command:
```python
@bot.command(name="base_command", scope=botGuilds)
async def baseCommand(ctx:CommandContext): pass
```

3. SubCommand with no options 
```python
@baseCommand.subcommand(
    name="sub_command_0",
    description="This is the first command I made!",
    options=[],
)
async def subCommand_0(ctx: interactions.CommandContext, *args, **kwargs):
    print("subcommand 0")
    print(args)
    print(kwargs)
    await ctx.send("Hi there!")
```

4. SubCommand with one option 
```python
@baseCommand.subcommand(
    name="sub_command_1",
    description="This is the first command I made!",
    options=[
        Option(name="option1",description="opt1",type=OptionType.STRING, required=False),
    ],
)
async def subCommand_1(ctx: interactions.CommandContext, *args, **kwargs):
    print("subcommand 1")
    print(args)
    print(kwargs)
    await ctx.send("Hi there!")
```

5. SubCommand with two options 
```python
@baseCommand.subcommand(
    name="sub_command_2",
    description="This is the first command I made!",
    options=[
        Option(name="option1",description="opt1",type=OptionType.STRING, required=False),
        Option(name="option2",description="opt2",type=OptionType.STRING, required=False),
    ],
)
async def subCommand_2(ctx: interactions.CommandContext, *args, **kwargs):
    print("subcommand 2")
    print(args)
    print(kwargs)
    await ctx.send("Hi there!")
```

6. Try stuff: use the commands and check console.

8. (tried with three options, same result as with two or no options, I would assume BaseResult is only included with one option)

### What you expected.

Basically I expected to see no BaseResult in the console:

```console
Connected to discord
subcommand 0
()
{}
subcommand 1
()
{}
subcommand 1
()
{'option1': 'asdfsd'}
subcommand 2
()
{}
subcommand 2
()
{'option1': 'asdfsdfsd'}
subcommand 2
()
{'option2': 'qwerqer'}
subcommand 2
()
{'option1': 'asdfasdfsa', 'option2': 'qerqerqwerqwr'}
```

### What you saw.

But in the subCommand1 there's a BaseResult... for some reason.
```console
Connected to discord
subcommand 0
()
{}
subcommand 1
(BaseResult(result=None),)
{}
subcommand 1
(BaseResult(result=None),)
{'option1': 'asdfsd'}
subcommand 2
()
{}
subcommand 2
()
{'option1': 'asdfsdfsd'}
subcommand 2
()
{'option2': 'qwerqer'}
subcommand 2
()
{'option1': 'asdfasdfsa', 'option2': 'qerqerqwerqwr'}
```

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Toricane** [comment]
This is intentional because you are using *args and **kwargs, let me break it down for you:

The BaseResult object exists to allow passing the return value from the base command to the subcommands.

This object is only passed when it is able to be passed. To clarify, the BaseResult will be passed in this function:
```py
@interactions.option()
async def subcommand(ctx, base_res, opt1):
    ...
```
But it will *not* be passed into this function:
```py
@interactions.option()
async def subcommand(ctx, opt1):
    ...
```
The reason it is not passed is because it cannot be passed.

Since there is room for the parameter, it *will* be passed in the following functions:
```py
@interactions.option()
async def subcommand(ctx, *args, opt1):
    ...

@interactions.option()
async def subcommand2(ctx, *args, **kwargs):
    ...
```

The reason why it is passed even though nothing is returned is so the developer can use that information in their subcommands. For example, a check could go in the base command, and if there was no result, the subcommand would act accordingly. If you don't like this approach and prefer it not to be returned when the result is None, let me know.

The point is, it will be passed when and only when it can be passed.

Now you may be wondering how to *not* get it passed. Here is a simple answer: get rid of `*args`. The library will never pass the options through `*args`, so you don't lose any data.

**Comment by g-rar** [comment]
Thanks for the response, @Toricane,  I think I get the logic better now :D:D... but I'm left still wondering why the BaseResult didn't get passed when there were two options or no options, and it did get passed when there was only one. Since in all three cases there's room withing the `*args`. All the coros have the same signature unless they're tinkered with in the background. And from my pov it seems inconsistent.

If the fact that the parameter is passed when no return value was given in the base command is intentional, I'm ok with it. But within that logic the amount of keyword parameters that are declared or expected on the function shouldn't be a factor on that considering it's a positional argument. My point boils down to consistency.

From what I can gather, it seems that you do some signature checking in order to determine if the parameter should be passed or not. If that's the case perhaps looking at the parameter names or type signature would be a better way to go about it? hence, passing it when the function is expecting to receive it. idk, lemme know your thoughts as well :D

cheers

**Comment by Toricane** [comment]
The problem with looking for the name or typehint is that it restricts developers, and not everyone speaks English or uses typehints in their code.

I will look into the signature checks and see how to improve consistency and optimize the checks, thanks!

**Comment by g-rar** [comment]
Not to downplay on accessibility but python and basically the entire ecosystem is kind of in English tho... I like the consideration tho, not many developers think about that outside of front-end development :D:D

typehints still could be used... if not to know were to put it, then as long as it knows were not to put it is good as far as my code concerns

but if it always gets passed down that'd be fine as well... so long as its consistent :D
