### ISSUE TITLE
[BUG] User parameter if user has emoji in nickname

### ISSUE THREAD

**Issue by FlorianPommerening** [interactions-py/interactions.py#1129]
### Describe the bug.

I'm using an option of type `OptionType.USER` and get a box to select the user among the users on the channel. However one user has a nickname that consists of only Emoji and does not show up in the list. Copy-Pasting the user's nick into the box also fails with the error `Not a valid user`.

### List the steps.

1. Set up a bot on a server with the following command
```
@bot.command(
    options = [
        interactions.Option(
            name="user",
            description="Who to greet?",
            type=interactions.OptionType.USER,
            required=True,
        )
    ],
)
async def hello(ctx: interactions.CommandContext, user: interactions.api.models.user.User):
    await ctx,send(f"Hello {user.mention}!")
```
2. Change the nickname of a user to :smile: .
3. Try to use `/hello` for :smile:. 

### What you expected.

Typing `/hello ` opens a list of all users including :smile:.

### What you saw.

Typing `/hello ` opens a list of all users except :smile:.

### What version of the library did you use?

stable

### Version specification

4.3.1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
![image](https://user-images.githubusercontent.com/25762802/196928948-e4c1c2bd-33a7-41bb-998c-ae23a7e74637.png)

**Comment by FlorianPommerening** [comment]
Hmm, I see. I looked at my test server again and now I also saw the user but they were not in the list earlier (directly after changing the nickname). Is there another reason why a user would not show in the list? Caching maybe?

**Comment by Damego** [comment]
That's not bug in the library. Just discord *magic*

**Comment by AstreaTSS** [comment]
This is explicitly a Discord bug. Please report it to them if possible.
