### ISSUE TITLE
[BUG] ValueError when editing message files during ratelimit

### ISSUE THREAD

**Issue by jamesrom** [interactions-py/interactions.py#1138]
### Describe the bug.

When the client has exhausted the rate limit for editing a message, attempting to attach a file (e.g., `ctx.message.edit(files=[...])`) does not work.

Firstly, a ValueError is logged: `ValueError: I/O operation on closed file`

Secondly, the `ctx.message.attachments` array is incorrectly populated with an attachment that was never sent.

In summary:
- the error is ignored
- the `attachments` property does not reflect the real state of the message

Thus making detection of this scenario difficult, as it cannot be handled with try/except, nor can the state of the message be interrogated. 

### Workaround
Replacing instances of `File(filePath)` with `File(filePath, fp=open(filePath, 'rb'))` prevents early closure of _fp.

Also, being careful to not hit the rate limit 😆

### List the steps.

1. Create a slash command that sends a message
2. Edit the message with `ctx.message.edit(...)` a few times in a some-what fast loop (enough to trigger ratelimit)
3. Edit the message with `ctx.message.edit(files=[...])` during the ratelimit backoff period
4. See the traceback error given

### What you expected.

1. File access is buffered or the handle is not closed until the request has been marshalled
2. Exceptions are raised correctly and not just logged

Here's [example code](https://github.com/interactions-py/library/pull/1135) that resolves point 2.

### What you saw.

I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/interactions/api/http/request.py", line 146, in request
    async with self._session.request(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 313, in __init__
    self.update_body_from_data(data)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 517, in update_body_from_data
    size = body.size
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/multipart.py", line 871, in size
    if encoding or te_encoding or part.size is None:
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/payload.py", line 379, in size
    return os.fstat(self._value.fileno()).st_size - self._value.tell()
ValueError: I/O operation on closed file
```

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by JumpingCoconut** [comment]
Problem still persists

**Comment by JumpingCoconut** [comment]
There is a workaround. Resetting the file pointer. 

This code tries to edit a message, and if that doesnt work because of discord limitations, just send it as new one:
```
try: 
    await ctx.message.edit(messagetext, embeds=[embed], files=files, components=components, attachments=None)
except Exception as e:
    # Too many edits. Just send it out as new message. 
    logging.info("Editing crashed: {} \nSending the content as completely new message.".format(e))
    for file in files:
        file._fp.seek(0)
    return await ctx.send(messagetext, embeds=[embed], files=files, components=components, ephemeral=False)
msg = await ctx.send("Message changed!")
return await msg.delete()
```

Without the file._fp.seek(0), the except block would still continue to crash. This is because the ctx.message.edit crashes while accessing the file pointer. Just setting it back and trying again works. Not sure if that helps you, but for my issue it was a good solution.

**Comment by LordOfPolls** [comment]
Can you confirm if this is still an issue in v5, @JumpingCoconut

**Comment by AstreaTSS** [comment]
Closing as the user cannot confirm it as of right now, and due to the drastic restructuring of v5. Can be reopened as needed.
