### ISSUE TITLE
[REQUEST] Remove or improve `__repr__` and `__str__` on models

### ISSUE THREAD

**Issue by Catalyst4222** [interactions-py/interactions.py#1140]
### Describe the feature.

Both of the `__repr__` and `__str__` magic methods can be very useful when used correctly. However, there are several places where their inclusion causes confusion. For example, the initial issue in [this help thread](https://canary.discord.com/channels/789032594456576001/1036495364737474612/1036495364737474612) was caused by the repr of the guild object just being the name. The default repr given by `attrs` would be better than returning the name of the object, due to it being clearer what kind of data it is. Similarly, the `__str__` magic method in Member can add extra confusion without providing a needed use case.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
I suggested to use `str` property for `Emoji` but EdVraz declined
https://github.com/interactions-py/library/pull/988

**Comment by sillyElvy** [comment]
Wait why does it even just print the name?

**Comment by sillyElvy** [comment]
Oh we probably override the repr right.

@Damego __str__ for emoji is not certainly bad as it shows valid information, opposed to __repr__ of the guild class which doesn't and just overwrites already present repr

**Comment by Damego** [comment]
> @Damego **str** for emoji is not certainly bad as it shows valid information, opposed to **repr** of the guild class which doesn't and just overwrites already present repr

Fine
