### ISSUE TITLE
[BUG] User Model Missing premium_type

### ISSUE THREAD

**Issue by JamesTesting888** [interactions-py/interactions.py#1152]
### Describe the bug.

When I print `user._json`, `premium_type` is not in there. However, in the docs, the user model should contain this value. This might be a Discord issue as it used to work. Might be an issue where Nitro classic has changed to Nitro basic. 

### List the steps.

1. Create any slash command
2. Get user model `user = ctx.author.user`
3. Print `user.premium_type` or check `user._json`

### What you expected.

It should return an integer value of (0, 1, or 2). I expected `premium_type` to be in `user._json`, but it is not. 

0 - None
1 - Nitro Classic
2 - Nitro

### What you saw.

None

### What version of the library did you use?

stable

### Version specification

4.3.4

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by mAxYoLo01** [comment]
I remember talking about it on the Support server, and in fact the `premium_type` is not dispatched by the Discord API. Idk since when though.
Nothing on our end disallows the state to be passed, it just looks like Discord removed it.

**Comment by Damego** [comment]
That's not library bug. Discord doesn't provides `premium_type` field. I suggest to ask about it in the ddevs server.
