### ISSUE TITLE
[REQUEST] Add event listener for bot disconnect

### ISSUE THREAD

**Issue by shradinx** [interactions-py/interactions.py#1180]
### Describe the feature.

I am currently developing my own Discord bot using interactions.py, however due to my internet not being the best, the bot tends to go offline randomly. I would like to know when the bot goes offline, and adding an event listener to listen for bot disconnects can help with this. Discord.py has an on_disconnect function, so it would make sense to have one here for interactions.py, as interactions.py was built to be an extension of Discord.py, according to the FAQ section on the documentation website.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by JamesTesting888** [comment]
This would be amazing.
