### ISSUE TITLE
[REQUEST] Improve docs for getting guild members

### ISSUE THREAD

**Issue by rwchhs** [interactions-py/interactions.py#1197]
### Describe the bug.

Going by the docs, right now there would seem to be three ways of getting all members of a guild. From what I can tell, two of these currently don't work as expected.

Assume that there's a bot which is a member of one guild with six members, including itself. Given that the bot's Server Members Intent is activated via the Discord Developer portal, I should be able to implement a slash command that outputs the guild's members.

The basic code would look like this:
```python
import interactions

bot = interactions.Client(
    token=...,
    intents=interactions.Intents.DEFAULT | interactions.Intents.GUILD_MEMBERS,
)

@bot.command()
async def members_info(ctx: interactions.CommandContext):
    ...

bot.start()
```

### Guild.members
As per the docs, Guild.members contains "the members in the guild". However, the following code
```python
@bot.command()
async def members_info(ctx: interactions.CommandContext):
    await ctx.send("processing...")
    str = ""

    for guild in bot.guilds:
        members = guild.members
        str += (f"Server: {guild.name} \r\n")
        str += (f"Members count: {len(members)} - ")
        str += ",".join(str(member) for member in members)
        str += "\r\n\r\n"
    await ctx.edit(str)
```
will have the bot output:
```Server: Test 
Members count: 1 - Bot
```
As far as I can tell, Guild.members will **always** only contain the bot itself, against the documentation's claim.

### Guild.get_all_members()
This method is the one that currently works most intuitively. The following code
```python
@bot.command()
async def members_info(ctx: interactions.CommandContext):
    await ctx.send("processing...")
    str = ""

    for guild in bot.guilds:
        members = await guild.get_all_members()
        str += (f"Server: {guild.name} \r\n")
        str += (f"Members count: {len(members)} - ")
        str += ",".join(str(member) for member in members)
        str += "\r\n\r\n"
    await ctx.edit(str)
```
will have the bot output
```Server: Test 
Members count: 6 - Bot,UserOne,UserTwo,UserThree,UserFour,UserFive
```
**However, as per the [source's warning](https://github.com/interactions-py/interactions.py/blob/2c902a2649fde05f4fe58672fc60ce8c84435cb7/interactions/api/models/guild.py#L2452), this method is deprecated.**

### Guild.get_members()
This method seems to simply not work at all.
```python
@bot.command()
async def members_info(ctx: interactions.CommandContext):
    await ctx.send("processing...")
    str = ""

    for guild in bot.guilds:
        members = guild.get_members() # the method isn't marked as async
        str += (f"Server: {guild.name} \r\n")
        str += (f"Members count: {members.object_count()} - ") # this will return 0
        str += ",".join(str(member) for member in members)
        str += "\r\n\r\n"
    await ctx.edit(str)
```
This will fail with
```
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<server_info() done, defined at .../venv/lib/python3.10/site-packages/interactions/client/models/command.py:930> exception=TypeError("'AsyncMembersIterator' object is not iterable")>
Traceback (most recent call last):
  File ".../venv/lib/python3.10/site-packages/interactions/client/models/command.py", line 970, in wrapper
    raise e
  File ".../venv/lib/python3.10/site-packages/interactions/client/models/command.py", line 939, in wrapper
    return await coro(ctx, *args, **kwargs)
  File ".../main.py", line 135, in server_info
    st += ",".join(str(member) for member in members)
TypeError: 'AsyncMembersIterator' object is not iterable
```

This error message seems a little weird, because AsyncMembersIterator does implement DiscordPaginationIterator which implements BaseIterator which provides `__iter__` and `__next__`, so I would assume that the object would be iterable. Interestingly enough, `flat = await members.flatten()` **does** work, giving all members as a list. So why doesn't it work via its iterator?

### List the steps.

See writeup.

### What you expected.

See writeup.

### What you saw.

See writeup.

### What version of the library did you use?

release

### Version specification

4.3.4

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
Hey! Both of these seem to be the fault of the documentation more than the actual code itself:

- `Guild.members` only returns *cached* members. Because of the little data Discord gives on startup (except if you have the presences intent on, for whatever reason), this will nearly always be empty unless you fetch all of the members.
- `Guild.get_all_members()` is indeed deprecated.
- `Guild.get_members()` is an *asynchronous* iterator, and these have some weird properties - basically, you need to use `async for` instead of `for` when iterating over it. It would look something like:
```python
async for member in guild.get_members():
    ...
```

That being said, a rewrite for interactions.py as a whole is coming up, so improving documentation on the current version is a very low priority. It could be possible that it may happen, but don't count on it unless someone PRs it.
