### ISSUE TITLE
Having some trouble with parameters

### ISSUE THREAD

**Issue by tildezero** [interactions-py/interactions.py#12]
I'm trying to make a slash command. If i make one without args, it works fine. But when i try to add args, the command breaks.
Command code:
```py
@slash.slash(name="echo")
async def _echo(ctx: SlashContext, text_to_echo):
    await ctx.send(text_to_echo)
```
when i registered the command, I did add an option in the POST json
```json
json = {
    "name": "echo",
    "description": "echo something",
    "options": [
        {
            "name": "text_to_echo",
            "description": "text that will be echoed",
            "type": 3,
            "required": True,
        }
    ]
}

```
my error seems to be in the request itself though: "Request failed with resp: 400 | {"code": 50035, "errors": {"type": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"a\" is not int."}]}}, "message": "Invalid Form Body"}"

any help would be greatly appreciated

also another thing, how do i add commands using the library? right now im just using a different file to add commands with requests, but it would be a lot easier if i could just add all the commands as my bot loads/as i code them

**Comment by VCJames** [comment]
> now im just using a different file to add commands with requests, but it would be a lot easier if i could just add all the commands as my bot loads/as i code them

Looks like these are handled in a utils package; more [here](https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.utils.manage_commands.html)

**Comment by eunwoo1104** [comment]
> my error seems to be in the request itself though: "Request failed with resp: 400 | {"code": 50035, "errors": {"type": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value "a" is not int."}]}}, "message": "Invalid Form Body"}"

https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.model.html#discord_slash.model.SlashContext.send
You passed string at `send_type`. To send a content, then pass it to `content`.
```py
await ctx.send(content=text_to_echo)
```

> also another thing, how do i add commands using the library? right now im just using a different file to add commands with requests, but it would be a lot easier if i could just add all the commands as my bot loads/as i code them

Auto-register system is in development, and will be added at next release maybe. For now, use utility function or manually send POST request.
