### ISSUE TITLE
User presence not detected [BUG]

### ISSUE THREAD

**Issue by Sub0X** [interactions-py/interactions.py#1211]
### Describe the bug.

When **member.user.presence.status** is called, **member.user.presence** returns as None and not as an object where I could access variables within it like **member.user.presence.status**. The rest of the **member.user** works fine as well.

### List the steps.

Create a cog for a slash command that sends user presence info:

-----------------
```
import interactions
import asyncio

class getInfo(interactions.Extension):
    def __init__(self, client: interactions.Extension) -> None:
        self.client = client

    @interactions.extension_command(name="get_status", description="Gets user Discord Statys")
    async def getStatus(self, ctx: interactions.CommandContext):
        member = await ctx.guild.get_member(ctx.author.id)
        print(member.user.presence.status)
        await ctx.send(f"{member.user.presence.status}")
```
-----------------

### What you expected.

I expected the discord bot to send data in the presence variable that is not None in the same channel as the user.

### What you saw.

Task exception was never retrieved
future: <Task finished name='Task-19' coro=<getInfo.getStatus() done, defined at C:\Users\Sub01\anaconda3\envs\main\lib\site-packages\interactions\client\models\command.py:930> exception=AttributeError("'NoneType' object has no attribute 'status'")>
Traceback (most recent call last):
  File "C:\Users\Sub01\anaconda3\envs\main\lib\site-packages\interactions\client\models\command.py", line 970, in wrapper
    raise e
  File "C:\Users\Sub01\anaconda3\envs\main\lib\site-packages\interactions\client\models\command.py", line 938, in wrapper
    return await coro(self.extension, ctx, *args, **kwargs)
  File "c:\Users\Sub01\Project\PaulWebsite\app\discordBot\cogs\getUser.py", line 20, in getStatus
    print(member.user.presence.status)
AttributeError: 'NoneType' object has no attribute 'status'

### What version of the library did you use?

release

### Version specification

4.3.4

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
This doesn't seem to be a bug - the library correctly notes that `presence` in `User` is optional, and so could be `None` (as it is here).
