### ISSUE TITLE
"This Interaction Failed"

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#124]
I'm not clear on how to get slash commands working. Inside one of my cogs, I have
```py
    @cog_ext.cog_slash(name="test")
    async def _test(self, ctx: SlashContext):
        await ctx.send("Test!")
```
I make sure the cog is added to the bot. However, the command doesn't show up, even in guilds where I added it with permission to have slash commands. Therefore, I decide to try to add it specifically to one guild. I manually registered it by having the bot execute
```py
from discord_slash import utils
await utils.manage_commands.add_slash_command(MYID, MYTOKEN, SERVERID, "test", "Test Description!", [])
```
Now, that guild sees the slash command. However, when I run it, it just says "This interaction failed." I have no errors on my end, so I'm not sure where it's failing? What am I missing here?

**Comment by ghost** [comment]
Update: I tried using the auto API update from #9 , and it claims that there aren't even any commands registered with the bot. Did I register it wrong in the cog? I added a slashcommand just in the main.py file as well, and when it tries to register that, I get
```py
Traceback (most recent call last):
  File "/home/ade/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 31, in on_ready
    await api.addToAPI(slash, CENSORED_ID, CENSORED_TOKEN)
  File "/home/ade/slashcoms/cogs/api.py", line 18, in addToAPI
    if info["guild_ids"] is not None:
TypeError: 'CommandObject' object is not subscriptable
```

**Comment by quirky-bluejay** [comment]
That code is from a while ago, there is now something like that built in.
Also issues here are for reporting bugs, feature requests, etc not for help with the libary. For that please use github discussions or join the Discord server

**Comment by ghost** [comment]
Sorry about that, I'll join it
