### ISSUE TITLE
[REQUEST] Add preview of components to the docs

### ISSUE THREAD

**Issue by chavinlo** [interactions-py/interactions.py#1260]
### Describe the feature.

New users (like me) might not know how these looks like and which one is which relying on guessing or trial and error until they find the appropiate one.

https://interactionspy.readthedocs.io/en/latest/models.component.html

Even a simple image would guide a lot.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Kigstn** [comment]
Should no longer be an issue. v5 docs have those already - https://interactions-py.github.io/interactions.py/Guides/05%20Components/#__tabbed_1_3

**Comment by AstreaTSS** [comment]
Closing due to v5 fundamentally changing the docs.
