### ISSUE TITLE
[BUG] Unable to view message content with message.content

### ISSUE THREAD

**Issue by ShadowMikado** [interactions-py/interactions.py#1276]
### Describe the bug.

Hi I created this code:

```python
@bot.event(name="on_message_create")
async def message(message: interactions.Message):
    print(f"Message from {message.author.username}: {message.content}")
```

and it dosen't work, message content is null and empty, do you know how to fix that ?

### List the steps.

1. Import the module 
2. create a basic bot with the @bot.event(name="on_message_create")
3. async def message(message: interactions.Message):
4. try print("message.content")
5. Just dosen't work, message.content is empty

### What you expected.

nothing append

### What you saw.

Instead, I received this in my python terminal:
```
Message from [My Username Here]: 
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
Heya! I'm sure you did not enable message content intent for your bot in discord developer portal and in your code

**Comment by ShadowMikado** [comment]
Oh, yes sorry I had not entered the intents in my code, sorry for the inconvenience. Thank you !
