### ISSUE TITLE
slash decorators should handle users using str for snowflakes

### ISSUE THREAD

**Issue by LordOfPolls** [interactions-py/interactions.py#129]
Seeing a lot of users using `str` for their snowflakes. Specifically for `guild_ids`. The issue with this is that it doesn't cause any errors for the user, causing confusion, but obviously breaks their commands and is very hard to debug 

I think we should be either converting the snowflake to `int` on the library side, or throwing a warning on creation of the command

**Comment by ghost** [comment]
Would be better to just do `int()`

**Comment by ghost** [comment]
> Would be better to just do `int()`

Btw why is there still no PR for that? Or I just missed it was merged already

**Comment by LordOfPolls** [comment]
Because I haven't made one :/

If you read this issue I'm giving 2 options. I made this issue to give people the opportunity to choose, as I don't really care either way

**Comment by ghost** [comment]
> Because I haven't made one :/

This *repo* needs a new hero xD

**Comment by quirky-bluejay** [comment]
What does d.py do if you pass a snowflake as a string?

**Comment by gabrielcastelan** [comment]
Nothing.

**Comment by boehs** [comment]
> Seeing a lot of users using `str` for their snowflakes. Specifically for `guild_ids`. The issue with this is that it doesn't cause any errors for the user, causing confusion, but obviously breaks their commands and is very hard to debug
> 
> I think we should be either converting the snowflake to `int` on the library side, or throwing a warning on creation of the command

I would be for option b, throwing a error, snowflakes are a int, and we should stick to best programming practices

**Comment by benwoo1110** [comment]
Doing nothing is probably the easiest option since it's already documented that snowflakes are int and `'1' != 1` is the first few things I learnt in python as well. But definitely, an informative error could be useful for people new to discord bot API 😄.

**Comment by ghost** [comment]
eh, didnt it now do warning in 2.0?
