### ISSUE TITLE
[BUG] AttributeError upon using bot.guilds

### ISSUE THREAD

**Issue by BnDLett** [interactions-py/interactions.py#1317]
### Describe the bug.

When using `bot.guilds` in order to get a list of the guilds the bot is in, I am given an AttributeError regarding `'str' object has no attribute 'cache'`.

### List the steps.

1. Import interactions.py
2. Create the interactions client
3. Assign variable "server_scopes" to `bot.guilds`
4. Error from `bot.guilds`

### What you expected.

I had expected `bot.guilds` to return a list of guilds that the bot is currently in.

### What you saw.

Instead of getting what I had expected, I had rather got
```
Traceback (most recent call last):
  File "/home/hp/Documents/Programming2/py/bots/smiley_bot/main.py", line 5, in <module>
    server_scopes = bot.guilds
  File "/usr/local/lib/python3.10/dist-packages/interactions/client/bot.py", line 180, in guilds
    return list(self._http.cache[Guild].values.values())
AttributeError: 'str' object has no attribute 'cache'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f18d7fc8430>
```

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
You can't use `bot.guilds` until the bot has started.
