### ISSUE TITLE
Cog slash commands not registering in Discord

### ISSUE THREAD

**Issue by AtlasC0R3** [interactions-py/interactions.py#132]
So, I've been trying to make slash commands work for my bot, but I didn't quite get it to work the way I wanted it to. I was only able to make slash commands work if I put them in the main bot file.

```python
# main.py
from discord_slash import SlashCommand, SlashContext

cogs = []
for cog_file in os.listdir('cogs/'):
    if cog_file.endswith('.py'):
        cog_import = 'cogs.' + cog_file.split('.')[0]
        cogs.append(cog_import)

bot = commands.Bot(  # Create a new bot
    # ...
)
bot.slash = SlashCommand(bot, override_type=True, sync_commands=True, sync_on_cog_reload=True)

@bot.slash.slash(name="testnt", guild_ids=[1234567890])
async def _test(ctx: SlashContext):
    await ctx.send(content="test", hidden=True)
    # This works.

bot.run(token, bot=True, reconnect=True)
```
I cannot get it to work within cogs. Chances are I'm doing something wrong _(which is why I opened an issue to get help)_.

```python
# cogs/slash.py
import discord
from discord.ext import commands
from discord_slash import cog_ext, SlashContext

guild_ids = [1234567890]


class Slash(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    def cog_unload(self):
        self.bot.slash.remove_cog_commands(self)
        pass

    @cog_ext.cog_slash(name="testcog", description="Test", guild_ids=guild_ids)
    async def _test(self, ctx: SlashContext):
        embed = discord.Embed(title="embed test")
        await ctx.send(content="test", embeds=[embed], hidden=False)


def setup(bot):
    bot.add_cog(Slash(bot))
```

This is all I see in Discord.
![image](https://user-images.githubusercontent.com/39468657/112723601-ccd38000-8ee5-11eb-9015-09f3ea5f76f9.png)

It obviously *tries* registering `testcog`, but just can't, since if I try to define a slash command named `testcog` inside `main.py`, it throws an error at me talking about "hey there's two commands with the same name i can't register them" _or something similar to that_.

**Comment by AtlasC0R3** [comment]
update: Slash commands in cogs only load after reloading the cog. I tried doing so with Jishaku and it only then showed the commands inside the cog.

**Comment by quirky-bluejay** [comment]
When do you initially load the cog?
Is it the first but of code excluding the slash command?

**Comment by AtlasC0R3** [comment]
The cog is loaded on the `on_ready()` event.


> Is it the first but of code excluding the slash command?

not sure I understand that...

The only workaround I've found so far is to add `bot.reload_extension("cogs.slash")` at the end of `on_ready()` *which is a **great** way to get rate limited*.

**Comment by quirky-bluejay** [comment]
You'll need to load cogs with slash commands before the bot is run.

**Comment by AtlasC0R3** [comment]
oh, that... explains a lot.
thanks, that fixed it.

**Comment by robertsez** [comment]
> 
> 
> You'll need to load cogs with slash commands before the bot is run.

Not just before the bot is running, but also after the `SlashCommand` client is created.
```py
class BotClient(commands.Bot):
    def __init__(self, **kwargs) -> None:
...
        for cog in INITIAL_COGS:
            try:
                self.load_extension(cog)
                print(f"Cog \"{cog}\" loaded.")
            except Exception:
                traceback.print_exc()
...

if __name__ == "__main__":
    bot = BotClient()
    slash = SlashCommand(bot, sync_commands=True, sync_on_cog_reload=True, override_type=True)
    bot.run()
```

This didn't run either. To fix it I had to put `SlashCommand` client inside BotClient class `__init__` before loading cogs.

**Comment by quirky-bluejay** [comment]
I actually think that could be fixed to allow loading before. Might be worth opening a fr
