### ISSUE TITLE
TTS not working since latest release

### ISSUE THREAD

**Issue by arian-nasr** [interactions-py/interactions.py#133]
@slash.slash(name="test", description="test case.", guild_ids=guild_ids)
async def test(ctx: SlashContext):
    
    await ctx.guild.me.edit(nick='newnick')
    await ctx.send('test', tts=True)
    await ctx.guild.me.edit(nick='oldnick')

This results in the message being sent but no TTS. It was working fine before the last release. Is it something wrong on my end?

**Comment by quirky-bluejay** [comment]
Are you deferring? Is this the first `ctx.send` in the command?

**Comment by i0bs** [comment]
Please re-direct your question to #questions in our support server for help, as Issues is not our area to help with that.
