### ISSUE TITLE
Add typing method to context

### ISSUE THREAD

**Issue by LilSpazJoekp** [interactions-py/interactions.py#134]
In discord.py there is a context manager for sending the typing indicator in chat for an arbitrary amount of time.

**Comment by quirky-bluejay** [comment]
`SlashContext` doesn't have many features that d.py's `Context` has because there may not be a bot user in the guild, and slash commands are fundamentally different from text based commands.
However you can access the channel object, if there is a bot user in the guild, with `ctx.channel`. Would this work?

**Comment by ghost** [comment]
> `SlashContext` doesn't have many features that d.py's `Context` has because there may not be a bot user in the guild, and slash commands are fundamentally different from text based commands.
> However you can access the channel object, if there is a bot user in the guild, with `ctx.channel`. Would this work?

yes, this work, i used it too for my ping command

**Comment by ShasV05** [comment]
we actually get that the bot is thinking message when we use slash, is it not enough?
anyway you can use 
```
async with ctx.channel.typing():
 time.sleep(0.5)
await ctx.send(yourmessage)
```

**Comment by ghost** [comment]
> we actually get that the bot is thinking message when we use slash, is it not enough?
> anyway you can use
> 
> ```
> async with ctx.typing():
>  time.sleep(0.5)
> await ctx.send(yourmessage)
> ```

not `ctx.typing()`, `ctx.channel.typing()`

**Comment by LilSpazJoekp** [comment]
> we actually get that the bot is thinking message when we use slash, is it not enough?
> 
> anyway you can use 
> 
> ```
> 
> async with ctx.typing():
> 
>  time.sleep(0.5)
> 
> await ctx.send(yourmessage)
> 
> ```

You can't send anything with the slash thinking.

**Comment by ghost** [comment]
> > we actually get that the bot is thinking message when we use slash, is it not enough?
> > anyway you can use
> > ```
> > 
> > async with ctx.typing():
> > 
> >  time.sleep(0.5)
> > 
> > await ctx.send(yourmessage)
> > ```
> 
> You can't send anything with the slash thinking.

wdym

**Comment by ShasV05** [comment]
> > we actually get that the bot is thinking message when we use slash, is it not enough?
> > anyway you can use
> > ```
> > async with ctx.typing():
> >  time.sleep(0.5)
> > await ctx.send(yourmessage)
> > ```
> 
> not `ctx.typing()`, `ctx.channel.typing()`

yeah sorry
its ctx.channel.typing()

**Comment by ShasV05** [comment]
> > > we actually get that the bot is thinking message when we use slash, is it not enough?
> > > anyway you can use
> > > ```
> > > 
> > > async with ctx.typing():
> > > 
> > >  time.sleep(0.5)
> > > 
> > > await ctx.send(yourmessage)
> > > ```
> > 
> > 
> > You can't send anything with the slash thinking.
> 
> wdym

![image](https://user-images.githubusercontent.com/32218136/113479526-443c7d00-94ad-11eb-8967-534f88e02d41.png)
i mean like this, similar to typing

**Comment by ShasV05** [comment]
> > we actually get that the bot is thinking message when we use slash, is it not enough?
> > anyway you can use
> > ```
> > 
> > async with ctx.typing():
> > 
> >  time.sleep(0.5)
> > 
> > await ctx.send(yourmessage)
> > ```
> 
> You can't send anything with the slash thinking.

you cant but it usually occurs when there is a delay or something like that

**Comment by quirky-bluejay** [comment]
When the command is deferred, which means displaying the 'bot is thinking message' you can send messages, just the first one will cause it to stop 'thinking'
As others have said here you can use `ctx.channel` if you want the bot to type. 
I don't think there is any reason to create a `ctx.typing`

**Comment by i0bs** [comment]
This is a misunderstanding as the Discord API is handling client UX events differently that are not being sent through the API's interaction response that we currently know of for showing a "typing" action as shown here. This is the same reasoning that we see with Discord beginning to handle their own error handling AFAIK with interaction responses failing. `ctx.typing` would have no essence towards this either.
