### ISSUE TITLE
[Docs]: autocomplete options data (args, kwargs)

### ISSUE THREAD

**Issue by Scrxtchy** [interactions-py/interactions.py#1349]
### Page

https://interactions-py.github.io/interactions.py/API%20Reference/API%20Reference/models/Internal/context/

### Problem description

Due to significant changes to version 5, the way that options are fetched for autocomplete contexts has changed drastically. While we used to fetch this from the context payload data, it is now being stored in the args and kwargs attributes.
I was not able to find anywhere on the documentation about these changes as well as anything to suggest that the data is being stored in here, I had to rely on reading source code to figure out there's already a method that processes them while not providing inline documentation of what it's attempting of doing

### Suggested changes

- Add autocomplete options to the [guide](https://interactions-py.github.io/interactions.py/Guides/03%20Creating%20Commands/#i-need-more-than-25-choices) linked in the migration documentation
- Improve definition of kwargs/args in context documentation

**Comment by AstreaTSS** [comment]
Bit late to the party, but I think this is worth a look into for anyone interested in looking at the docs.

Most of this could be fixed by both mentioning it in the migration guide and the slash commands guide. Admittedly, it's left very unclear in those docs.

I have my doubts about changing the docs for the context though - `BaseInteractionContext` correctly notes that `kwargs` has the keyword arguments for the interaction (with autocomplete being a type of interaction in a way).

**Comment by Scrxtchy** [comment]
Another alternative that could be taken that would be require more of a consideration/approval would be to improve the accessibility of the auto-complete options. A simple getter is provided for retrieving the input text from kwargs, but something similar isn't available for this data in the context. I admittedly almost wrote a function for this myself before realising the output of [process_options()](https://github.com/interactions-py/interactions.py/blob/c3fc966256ed7b86a51d73982f193a15df83a665/interactions/models/internal/context.py#L347) is making these available through the `kwargs` dict.

By adding something like this to the class for getting auto-complete options, you'll have something more concrete to document as well as being discovered more simply though source navigation or an IDE's auto-completion, but I consider such work out of scope for this tracked issue

**Comment by AstreaTSS** [comment]
I do agree with that. In general, I do feel as if autocomplete UX was downgraded significantly during the process of making v5, as NAFF v2, the base for v5, had a clearer syntax IMO (although I had people disagree with that). Regardless, I think `kwargs`, if documented in the guides, should be fine for now, but it may worth be revisiting autocomplete UX in the future.

**Comment by LordOfPolls** [comment]
Evening. 

Please comment example code demonstrating the ux you want. (Directed at everyone, not just participants of this issue)

**Comment by AstreaTSS** [comment]
I do like the old NAFF way of it, though I can think of a modification that might make it better.

Let's take a slash command with two options:
- `name`, a string that is autocompleted.
- `channel`, a... channel.

In NAFF, autocomplete for name would be something like the below (note I'm on mobile):
```python
async def name_autocomplete(ctx: AutcompleteContext, name: str | None = None, channel: BaseChannel | None = None):
    ...
```

You could also use `**kwargs` to essentially "ignore" other options besides names if you wanted to:
```python
async def name_autocomplete(ctx: AutcompleteContext, name: str | None = None, **kwargs):
    ...
```

Admittedly, this behavior produces some seemingly strange results. For example, I believe the example in the docs used a command with one option, meaning when there are multiple options with a mix of autocomplete/not autocomplete, NAFF would try to pass every filled-in option, confusing people as their one-argument functions (ignoring `self` and `ctx`) failed.

However, I think that by only passing the context and not the options, as well as forcing users to use `ctx.kwargs`, was the wrong fix to this. Instead, I propose this as a solution:

```python
async def name_autocomplete(ctx: AutocompleteContext, name: str | None = None):
    ctx.kwargs  # other options are still here
```

This means the targeted option is the only "required" thing to put, which is pretty intuitive for people to understand. That being said, you can still access other options, if needed, through `ctx.kwargs` (or some helper method), just in case you wanted them.
