### ISSUE TITLE
[BUG] auto mod type 6 missing

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1363]
### Library Version

5.0.1

### Describe the Bug

The new member profil auto mod rule type is not implemented

![image](https://user-images.githubusercontent.com/51890392/234994550-371adde2-865b-45c5-be01-4a1993236fdb.png)

### Steps to Reproduce

Set up a member profil auto mod rule an let it trigger

### Expected Results

That the type would be integrated

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by LordOfPolls** [comment]
This part of the API is still in Alpha testing. It's not implemented pending wider beta rollout

**Comment by Mias15** [comment]
What's wrong with adding it anyway? The chances of Discord discarding the feature are very low and it would help, since every server has the feature and can use it

**Comment by LordOfPolls** [comment]
Looks like since I last commented it has now propagated - it'll be added now
![image](https://user-images.githubusercontent.com/22540825/235594654-36ca0f3c-99e2-4d77-996c-caa230e192ba.png)
