### ISSUE TITLE
Make global slash commands.

### ISSUE THREAD

**Issue by NomCustom** [interactions-py/interactions.py#137]
So, i'm a developer of a bot in 100 servers, but I want to make global slash commands, how ?

**Comment by benwoo1110** [comment]
There is documentation:
https://discord-py-slash-command.readthedocs.io/en/latest/
https://discord-py-slash-command.readthedocs.io/en/latest/quickstart.html
https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.client.html#discord_slash.client.SlashCommand.slash

**Comment by quirky-bluejay** [comment]
Issues are for bugs, feature requests, etc about the library's code
For questions use discussions or the discord server. 
Also the links above should help.
Converting this to a discussion
