### ISSUE TITLE
[FEAT] Sort member roles

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1383]
### Library Version

5.0.2

### Describe the Bug

The roles of a user are always mixed and not in the actually order

### Steps to Reproduce

add yourself some roles on a server and run the code provided below

### Expected Results

That the roles would be in the right order

### Minimal Reproducible Code

```python
@slash_command(name='roles')
async def roles_cmd(ctx: InteractionContext):
    for role in ctx.member.roles:
        print(role.name)
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
Not necessarily a bug as the roles are given to us unsorted - I would consider this more of a feature request. That being said, using `sorted(roles)` sorts the roles for you.

**Comment by LordOfPolls** [comment]
I'll add this for a future release. But yes, astrea is completely right
