### ISSUE TITLE
[FEAT] purge returns deleted messages

### ISSUE THREAD

**Issue by Donbur4156** [interactions-py/interactions.py#1390]
### Problem Description

In V4 channel.purge returns a list of deleted messages.
It would be nice to have this in V5 too.

### Proposed Solution

channel.purge(...) -> list[Message]

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
Think it's a good idea - it shouldn't be too hard anyhow.

**Comment by AstreaTSS** [comment]
...turns out this would be breaking. Still not a bad idea IMO, but it'll have to be discussed.

**Comment by LordOfPolls** [comment]
Reesolved in #1396 without breaking
