### ISSUE TITLE
Add support for custom Context

### ISSUE THREAD

**Issue by Luc1412** [interactions-py/interactions.py#140]
Discord.py currently allows implementing a custom context when you for example overwrite the process_commands function and manually invoke the command with `await self.invoke(ctx)`. It would be useful if this extension also supports custom Context classes.

**Comment by i0bs** [comment]
Pinging @LordOfPolls for this, not sure how this went unnoticed/not responded to.

**Comment by i0bs** [comment]
**EDIT:** No need for this Issue to still be kept open at this time. For any inquiries please refer to the #lib-discussion channel of the support server.
