### ISSUE TITLE
Paginator does not work with 5.0

### ISSUE THREAD

**Issue by Vishvesh1542** [interactions-py/interactions.py#1400]
### Problem Description

I tried for an entire day to make Paginator work on my codespace but it just wouldn't. After some experimentation I found that it worked on my PC. After installing the exact version of interactions that my PC used on my codespace (4.4.1) it worked. The error you get when using 5.x.x is 'module interactions does not have 'spread_to_rows'.

### Proposed Solution

Just update the code to work with paginator

### Code of Conduct

- [ ] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
Hi! v4 paginator wont work with v5. However, v5 have own paginator and you shoud use it
Docs: https://interactions-py.github.io/interactions.py/Guides/30%20Pagination/
