### ISSUE TITLE
[FEAT] Stack Autocomplete Operators

### ISSUE THREAD

**Issue by MasterNoob34** [interactions-py/interactions.py#1405]
### Problem Description

Exact same code for multiple different autocomplete options. So I can just use the same code for each of those autocomplete.

### Proposed Solution

```py
@ipy.global_autocomplete(option_name="player_tag1")
@ipy.global_autocomplete(option_name="player_tag2")
@ipy.global_autocomplete(option_name="player_tag3")
```

Stack autocompletes like so?

### Alternatives Considered

Regex for option_name.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by LordOfPolls** [comment]
Have you considered using a single decorator with a regex custom ID?

**Comment by MasterNoob34** [comment]
> Have you considered using a single decorator with a regex custom ID?

Oh yeah, that can be a alternative solution!

**Comment by i0bs** [comment]
Filing this as a wontfix. as @LordOfPolls said– I would consider using the `regex` kwarg we have for callbacks, your usecase seems to fit this niche best. 

Outside of this, autocomplete operator stacking seems redundant. I don't think it's great in DX practice to have numerous autocomplete fields hinge on the same function. If you want re-useable code, consider separating your code into a separate function, and have numerous function callback declarations call that within.
