### ISSUE TITLE
[QUESTION] How to disconnect user from voice? 

### ISSUE THREAD

**Issue by AlexaCarra** [interactions-py/interactions.py#1409]
### Library Version

5.4.0

### Describe the Bug

I tried to use the user.edit(channel_id = 0) method but that didn't work. I need to disconnect a user from a voice channel

### Steps to Reproduce

-

### Expected Results

-

### Minimal Reproducible Code

```python
-
```

### Traceback

-

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by LordOfPolls** [comment]
I would advise you to read the documentation, if you're still unsure, join the discord help server. 
You've made 3 issues in the last hour for things that aren't issues

I don't believe GitHub issues are appropriate for your requirements

**Comment by AlexaCarra** [comment]
> I would advise you to read the documentation, if you're still unsure, join the discord help server. You've made 3 issues in the last hour for things that aren't issues
> 
> I don't believe GitHub issues are appropriate for your requirements

ssory) okay
