### ISSUE TITLE
[BUG] Unable to create new `Role` with `Permissions.NONE`

### ISSUE THREAD

**Issue by ShajeshJ** [interactions-py/interactions.py#1420]
### Library Version

5.5.1

### Describe the Bug

When attempting to create a new guild role with permissions set to `Permissions.NONE` (i.e. the role should have all permissions disabled), the role is instead created with Discord's default set of permissions for new guild roles.

### Steps to Reproduce

Call the function `create_role` on a `interactions.Guild` object, and attempt to create a new role, passing in `permissions=interactions.Permissions.NONE`. Then through the Discord UI, observe the permissions enabled for the role. Notice that the default permissions for guild roles are all enabled.

### Expected Results

When calling `interactions.Guild.create_role` with `permissions=interactions.Permissions.NONE`, the role created should have all guild permissions disabled on it.

### Minimal Reproducible Code

```python
import interactions as ipy

bot = ipy.Client(intents=ipy.Intents.DEFAULT, debug_scope=<your_guild_id>)

@ipy.slash_command()
async def create_role(ctx: ipy.SlashContext):
    role = await ctx.guild.create_role(name="test role", permissions=ipy.Permissions.NONE)
    await ctx.send(f"role's new permissions: {role.permissions}")

if __name__ == "__main__":
    bot.start("<token>")
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

I think the bug is just an improper falsey check on the `permissions` argument.

**Comment by silasary** [comment]
Fixed in Unstable
