### ISSUE TITLE
[BUG] CustomEmoji.edit: roles only allows snowflakes no Role Objects

### ISSUE THREAD

**Issue by Donbur4156** [interactions-py/interactions.py#1426]
### Library Version

5.5.1

### Describe the Bug

Edit a CustomEmoji only takes list of snowflakes for roles argument.

Following the Argument definition list of Roles should work, too:
`roles: Optional[List[Union["Snowflake_Type", "Role"]]] = None`

Possible solution is to set roles inside the payload in same way of creating a CustomEmoji:
`"roles": roles` --> `"roles": to_snowflake_list(roles) if roles else MISSING`

### Steps to Reproduce

```py
emoji = await guild.create_custom_emoji(name=name, imagefile=image, reason=reason)
...
await emoji.edit(roles=[role1, role2]) // role1/role2 are interactions.Role Objects
```

### Expected Results

change the allowed roles for the emoji.

### Traceback

```
  File "C:\...\bot\ext\emoji_ext.py", line 550, in create_emoji (Current frame)
    await emoji.edit(roles=[role1, role2])
  File "C:\...\bot\bot.py", line 64, in <module>
    client.start()
interactions.client.errors.HTTPException: HTTPException: 
400|Bad Request: roles->0 NUMBER_TYPE_COERCE: 
Value "{'id': 123456123456123456, 'name': 'name', 'color': {'value': 0}, 'hoist': False, 'position': 34, 'permissions': 0, 'managed': False, 'mentionable': False, 'premium_subscriber': False, 'purchasable_or_has_subscribers': False, '_guild_id': 123456123456123456, '_guild_connections': False}" 
is not snowflake.
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
Your proposed solution does seem like a valid solution, if you want to PR it.

**Comment by Donbur4156** [comment]
@AstreaTSS done: #1427
