### ISSUE TITLE
[BUG] Task Won't Run in Extension if Self is Specified

### ISSUE THREAD

**Issue by Colorfulsalmon** [interactions-py/interactions.py#1429]
### Library Version

5.5.1

### Describe the Bug

If I pass self into a task extension, the extension doesn't run even if the task is. 
It excepts and suppresses the traceback/exception.

### Steps to Reproduce

Pass self into a task extension.

### Expected Results

The task to run, and self be a usable variable within the task function.

### Minimal Reproducible Code

```python
class CheckIdleChannels(interactions.Extension):
    def __init__(self, bot):
        self.bot: interactions.Client = bot

    @interactions.Task.create(interactions.IntervalTrigger(seconds=5))
    async def print_every_ten(self):
        print("It's been 5 seconds!")``
```

```python
class Startup(interactions.Extension):
    def __init__(self, bot):
        self.bot: interactions.client = bot

    @interactions.listen()
    async def on_startup(event: Startup):
        CheckIdleChannels.print_every_ten.start()

```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by LordOfPolls** [comment]
This has nothing to do with the task object; This is due to your code. You are calling the task function inside another class without initializing said class. This means the function is never bound as a method, hence your error. Consider revising your project structure 

```python
class TestExt(Extension):
    @listen()
    async def on_startup(self):
        print("Test extension loaded!")
        self.test_task.start()

    @Task.create(IntervalTrigger(seconds=5))
    async def test_task(self):
        print(f"Test task running @ {time.time()}")
```
