### ISSUE TITLE
[BUG] AutoModTriggerType.MEMBER_PROFILE has no channel object & AuditLogEventType 146 is missing

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1442]
### Library Version

5.6.0

### Describe the Bug

`AutoModTriggerType.MEMBER_PROFILE` is not supposed to have a channel object because it can also trigger on nickname changes, which then throws some errors...

And the `AuditLogEventType` 146 for quarantining a member as an auto mod action is missing.

### Steps to Reproduce

create an auto mod role for user names and let it trigger 

### Expected Results

that the channel object is optional and the missing event type is added

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by LordOfPolls** [comment]
re
> AutoModTriggerType.MEMBER_PROFILE is not supposed to have a channel object because it can also trigger on nickname changes, which then throws some errors...

does it fail outright, or only when you reference then channel property?

**Comment by Mias15** [comment]
directly (the channel property is required in the AutoModTriggerType)

**Comment by LordOfPolls** [comment]
Resolved in unstable
