### ISSUE TITLE
[BUG] AttributeError: module 'interactions' has no attribute 'Option'

### ISSUE THREAD

**Issue by gh-doot** [interactions-py/interactions.py#1446]
### Library Version

discord-py-interactions      5.6.0

### Describe the Bug

The provided code encounters an error when attempting to use the Option attribute from the interactions module. The error message suggests that the Option attribute is not found in the interactions module.
interactions.Option( <------ "Breakpoint"
            name="text",
            description="What you want to say",
            type=interactions.OptionType.STRING,
            required=True,
        ),

### Steps to Reproduce

Update to latest version, or install, get error trying to- usually around here:
interactions.Option( <---------- "No" attribute named option.
            name="text",
            description="What you want to say",
            type=interactions.OptionType.STRING,
            required=True,
        ),

### Expected Results

My expected results were that the bot should be running fine with the commands and producing the correct results, which, I followed the documents for. Previously before updating it was working perfectly fine and ran the bot but upon further inspection came to me with an error.

### Minimal Reproducible Code

```python
import interactions

interactions.Option <------- no attr of Option
```

### Traceback

Traceback (most recent call last):
  File ".../.py", line 3, in <module>
    interactions.Option(
AttributeError: module 'interactions' has no attribute 'Option'

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by mAxYoLo01** [comment]
Hi, this is not a bug, you are probably looking at v4 docs that are outdated since you have installed the v5 version of the lib.
Please follow [this guide](https://interactions-py.github.io/interactions.py/Guides/03%20Creating%20Commands/#but-i-need-more-options) for information on Command Options using v5.

**Comment by gh-doot** [comment]
> Hi, this is not a bug, you are probably looking at v4 docs that are outdated since you have installed the v5 version of the lib. Please follow [this guide](https://interactions-py.github.io/interactions.py/Guides/03%20Creating%20Commands/#but-i-need-more-options) for information on Command Options using v5.

Yup, you're right, confirmed so.
