### ISSUE TITLE
Outdated documentation?

### ISSUE THREAD

**Issue by linnnus** [interactions-py/interactions.py#146]
[The documentation](https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.context.html) claims that the `SlashContext` has the properties `args` and `kwargs` but they do not appear to be present. I get the following error when I try to acces them: `'SlashContext' object has no attribute 'kwargs'`.  Either the documentation is outdated or something is going wrong.

**Comment by quirky-bluejay** [comment]
That's the docs for the dev version, the master branch. Use the [stable](https://discord-py-slash-command.readthedocs.io/en/stable/discord_slash.context.html) version or install from github.
