### ISSUE TITLE
[BUG] Fix ctx.send("", delete_after) for ephemeral message

### ISSUE THREAD

**Issue by BigChungus888** [interactions-py/interactions.py#1465]
### Library Version

5.7.0

### Describe the Bug

```
ValueError("Cannot delete ephemeral message without interaction context parameter")
```

### Steps to Reproduce

ctx is SlashContext

```py
await ctx.send("some", delete_after=2)
```

### Expected Results

Delete the interaction message after 2 seconds.

### Minimal Reproducible Code

```python
await ctx.send("some", delete_after=2)
```

### Traceback

```
ValueError("Cannot delete ephemeral message without interaction context parameter")
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

I think it can be fixed if a context is passed. Perhaps add a way to pass context or something.

**Comment by Wolfhound905** [comment]
@BigChungus888 are you using `ctx.defer(ephemeral=True)` before this code?

**Comment by BigChungus888** [comment]
Yeah I do. But deleting ephemeral should not be a problem right? As ctx.delete() is able to do that.

**Comment by AstreaTSS** [comment]
#1467 will close this.
