### ISSUE TITLE
Wrong command invocation with optional args

### ISSUE THREAD

**Issue by Luc1412** [interactions-py/interactions.py#148]
I got the following code:
```py
def __init__(self):
    self.bot.slash.add_slash_command(
        self._slash_stats, guild_ids=guild_ids,
        name='stats', description='Get a players stats.',
        options=[
            create_option('player', 'The player name', 3, False),
            create_option('user', 'The Discord User you want the stats from.', 6, False),
            create_option(
                'input', 'The input type the the player.', 3, False,
                choices=[
                    create_choice('global', 'Global'),
                    create_choice('keyboardmouse', 'Keyboard and Mouse'),
                    create_choice('gamepad', 'Controller'),
                    create_choice('touch', 'Touch')
                ]
            )
        ]
    )

async def _slash_stats(self, ctx: discord_slash.SlashContext, player_name: str = None, user: discord.User = None, input_type: str = None):
    print(player_name, user, input_type)
```

The result:
![image](https://user-images.githubusercontent.com/24532065/114467967-047f3f00-9beb-11eb-9147-d6e9673485ea.png)

The command I use:
![image](https://user-images.githubusercontent.com/24532065/114468009-195bd280-9beb-11eb-9924-c6a6273d1a51.png)

The print result:
`nikki1511 touch None`

I choose the first (`player`) and third (`input`) arg, but it didn't ignore the 2nd arg and passed me the first and second arg. (no it's not caused by naming `input` and `input_type`)

**Comment by ghost** [comment]
are u trying to make command in cog?

**Comment by quirky-bluejay** [comment]
The arguments are not named the same as your options, so it's passing them in order.

**Comment by Luc1412** [comment]
> are u trying to make command in cog?

Yeah, but due to dynamic guild_ids I cannot use the decorator. I add them on Cog Start


> The arguments are not named the same as your options, so it's passing them in order.

 I just checked input -> input_type and forgot about player -> playername. Thanks, this solved this issue.
