### ISSUE TITLE
[BUG] Channel attributes missing

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1486]
### Library Version

5.8.0

### Describe the Bug

- **GuildNews** is missing: `rate_limit_per_user`
- **VoiceChannel** is missing: `rate_limit_per_user`, `default_auto_archive_duration`
- **ForumChannel** is missing: `available_tags`, `rate_limit_per_user`, `default_thread_rate_limit_per_user`, `default_sort_order`, `default_forum_layout`

### Steps to Reproduce

Try to retrieve the above attributes during the creation create event of the specific channel ... as an example, the attribute `rate_limit_per_user` can be set (during the creation/editing of the channel), but can't be readed out

### Expected Results

 that the missing attributes would be present

### Minimal Reproducible Code

```python
async def on_channel_create_event(self, event: events.ChannelCreate):
    print(event.channel.rate_limit_per_user)
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
This is useful... but what did you get instead of the expected response? Simply the fact that it could not be read is a bit vague and could mean a lot.

**Comment by Mias15** [comment]
get some nice attribute errors
