### ISSUE TITLE
[BUG] Invites have no guild parameter for create/delete event

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1498]
### Library Version

5.8.0

### Describe the Bug

Invites have no guild_in parameter or guild object

### Steps to Reproduce

try to find out which server the event comes from when creating/deleting an invites

### Expected Results

that the guild parameter exists if the invite is from a server

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
It's under `guild_preview` as Discord only gives partial guild data.

**Comment by Mias15** [comment]
the `guild_preview` is missing in the invite create/delet event ... How do I get access to the guild ID shown in the screenshot below?
![image](https://github.com/interactions-py/interactions.py/assets/51890392/08910bc3-fa80-46ad-82ac-d5d338c65107)

**Comment by AstreaTSS** [comment]
Oh lord Discord really gives a whole different payload for invite creations and deletions— I guess it's not the first time.

Reopening.

**Comment by AstreaTSS** [comment]
#1500 will close this.
