### ISSUE TITLE
Adding type enums from Discord docs

### ISSUE THREAD

**Issue by VCJames** [interactions-py/interactions.py#15]
Going to be porting over the types from Discord docs. Will submit a PR with them in `discord_slash.types`?

Completely my own fault but due to lack of type annotations - just fought for a couple hours with what seemed to be a problem with [THIS ](https://github.com/eunwoo1104/discord-py-slash-command/blob/master/discord_slash/client.py#L284)returning when it shouldn't. But was my fault; checking for int `ctx.guild.id` in me mistakenly passing `List[str]` to `guild_ids`.

**Comment by eunwoo1104** [comment]
I'll try to make it more clear to use it and change type hint.
