### ISSUE TITLE
[FEAT] Image upload to embed or allow Base64 images

### ISSUE THREAD

**Issue by syntaxsdev** [interactions-py/interactions.py#1510]
### Problem Description

I want to be able to upload images from the local machine to an embed object instead of using a URL.
The URL option exposes my S3 bucket URL.

### Proposed Solution

Allowing Image uploads or Base64 images

### Additional Information

If any known workarounds are known for this, please let me know

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
Discord's Web API limits us to a URL, unless you're asking for us to introduce a helper method. I think as the developer, you should have control over how you upload images to URLs for use – we don't really need to do any of that in the background, we're only providing the means to nicely interface it with the APIs provided.

Have you considered looking into making requests to Web API services like ImgBB?

**Comment by AstreaTSS** [comment]
I should also note that you can use the local attachment link trick:

```py
file = interactions.File("image.png")
embed = interactions.Embed(...)
embed.set_image(url="attachment://image.png")
await channel.send(embeds=embed, files=file)
```

**Comment by LordOfPolls** [comment]
closing per the above. feel free to reopen if those arent viable

**Comment by syntaxsdev** [comment]
> I should also note that you can use the local attachment link trick:
> 
> ```python
> file = interactions.File("image.png")
> embed = interactions.Embed(...)
> embed.set_image(url="attachment://image.png")
> await channel.send(embeds=embed, files=file)
> ```

@AstreaTSS Thanks for that. However, does this allow for the image to be embedded into the card? I don't want to just upload it as a message, but within the embed card. I tried this trick but it just uploaded the file as a normal image. Does the image need to be in the same folder as the file? Is there anymore insights you can provide on this?

**Comment by AstreaTSS** [comment]
The trick should work just fine - it'll only be in the embed if done right. I can't really say what you may be missing without more details - perhaps the support server is better for that.

**Comment by syntaxsdev** [comment]
Thanks. The issue is that if you create a `interactions.File` of the image path, the url must just be the attachment's file name, excluding path.

Thank you all, will use the server next time for support!
