### ISSUE TITLE
docs: Examples

### ISSUE THREAD

**Issue by hastyquickbeam** [interactions-py/interactions.py#1515]
### Page

Examples : /Guides/90 Example/

### Problem description

The example seems to require `Intents.ALL` in order to successfully get message content for the following function to work:
```python
@listen()
async def on_message_create(event):
    print(f"message received: {event.message.content}")
```
But the example has `Intents.DEFAULT` instead.

### Suggested changes

Change to `Intents.ALL` or change the example function to not require privileged intents.

### Additional context

https://interactions-py.github.io/interactions.py/Guides/90%20Example/

**Comment by i0bs** [comment]
Thanks for catching this, this will be changed shortly
