### ISSUE TITLE
[BUG] listen decorator is mistyped

### ISSUE THREAD

**Issue by DeinAlptraum** [interactions-py/interactions.py#1520]
### Library Version

5.8.0

### Describe the Bug

The `listen()` decorator is mistyped.
`@listen(Startup)` gave me a type error from mypy:
`app.py:71: error: Argument 1 to "listen" has incompatible type "type[Startup]"; expected "str | BaseEvent | Missing"`

### Steps to Reproduce

1. Write any event listener via `listen` decorator
2. Pass the decorator any subclass of `BaseEvent`
3. Type check it with mypy, this results in a type error.

### Expected Results

No type error.

### Minimal Reproducible Code

```python
@listen(Startup)
async def on_start(_: Startup):
    pass
```

### Traceback

`app.py:71: error: Argument 1 to "listen" has incompatible type "type[Startup]"; expected "str | BaseEvent | Missing"  [arg-type]`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

Changing the type of the `event_name` parameter from `Absent[str | BaseEvent]` to `Absent[str | type[BaseEvent]]` fixes the issue.

**Comment by AstreaTSS** [comment]
This was fixed in... some PR I made for 5.9.0. That version will fix the typehint once it comes out.
