### ISSUE TITLE
[BUG] Using User.avatar_url gives a "no attribute" type error

### ISSUE THREAD

**Issue by DeinAlptraum** [interactions-py/interactions.py#1525]
### Library Version

5.9.2

### Describe the Bug

Using `User.avatar_url` gives a "no attribute" type error when type-checking with mypy. It works fine at runtime though.
Going through `User.display_avatar.url` instead fixes the type error

### Steps to Reproduce

Create a file with the following content:

```python
from interactions import User

print(User().display_avatar.url)
print(User().avatar_url)
```

Check with mypy (use `--disable-error-code call-arg` to ignore other errors).
This throws an error for line 4, but not for line 3.

### Expected Results

Accessing `User.avatar_url` should not lead to any errors.

### Minimal Reproducible Code

```python
from interactions import User

print(User().display_avatar.url)
print(User().avatar_url)
```

### Traceback

`/home/deinalptraum/Desktop/testfile.py:4: error: "User" has no attribute "avatar_url"  [attr-defined]`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by mAxYoLo01** [comment]
Yep I see why, `avatar_url` is missing in the Mixins in `user.pyi`. If someone wants to PR that!
