### ISSUE TITLE
[FEAT] Custom activity states

### ISSUE THREAD

**Issue by i0bs** [interactions-py/interactions.py#1526]
### Problem Description

https://github.com/discord/discord-api-docs/pull/6345 is on open track. Bots can now set a custom activity state, including custom statuses. We currently only accept activity statuses for watching, playing and streaming.

### Proposed Solution

This requires an implementation detail for our client-facing gateway and bot.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
interactions.py doesn't actually do any filtering based off the type, and even has the `state` field already, but the `state` itself wasn't being passed through as a payload (via `to_dict()`). #1527 solves this (and didn't appear on the GitHub log in the server for some reason).
