### ISSUE TITLE
[BUG] Bot fails to disconnect properly from voice channel when used across multiple guilds

### ISSUE THREAD

**Issue by tequa** [interactions-py/interactions.py#1531]
### Library Version

5.9.2

### Describe the Bug

The connect and disconnect voice channel endpoints for my bot work just fine when using in a single guild. But when I use the bot in multiple guilds, if I disconnect from a voice channel in 1 guild, and then subsequently disconnect from a voice channel in another guild, the second bot will seemingly disconnect from the voice channel but its voice state will not update. Because its voice state fails to be set to null, it will fail to further connect to the same voice channel because it thinks it's still connected to it.

### Steps to Reproduce

1. Set up the endpoints in the code pasted below
2. In 2 different guilds with 2 different accounts, join a voice channel
3. Call `/join_voice` in each guild. Each bot should successfully join the voice channel.
4. Call `/leave voice` in bot 1's guild; they should successfully leave the voice channel and this INFO message will show:
`2023-08-15 07:07:47 | INFO | interactions | Disconnecting from voice channel ###`
5. Call `/leave_voice` in bot 2's guild. The bot will leave the voice channel BUT there will be no INFO message for the disconnect.
5. Call `/join_voice` in bot 2's guild. They will fail to join because their voice state is non-null and the bot still thinks it's in the voice channel 

I originally got the bug on a messy Python 3.10 project but was able to reproduce it again with a fresh Python 3.11 virtual env after doing just `pip install discord-py-interactions` and `pip install discord.py-interactions[voice]` and using the code below

### Expected Results

Connecting and disconnecting from the channels across guilds should not interfere with one another.

### Minimal Reproducible Code

```python
@interactions.slash_command(
    name="join_voice",
    description="Connect and stay in the voice channel you're currently in",
)
async def join_voice(ctx: SlashContext):
    if not ctx.author.voice:
        await ctx.send("You are not in a voice channel", ephemeral=True)
        return
    channel = ctx.author.voice.channel
    await channel.connect()

    await ctx.send("Joining voice channel!")


@interactions.slash_command(
    name="leave_voice",
    description="Kick the bot from the voice channel its currently in",
)
async def leave_voice(ctx: SlashContext):
    voice_state = ctx.voice_state
    if not voice_state:
        await ctx.send("The bot is not in any voice channel!", ephemeral=True)
        return
    await voice_state.channel.disconnect()
    
    await ctx.send("Leaving voice channel!") 
    
bot = interactions.Client(token=discord_bot_key, intents=interactions.Intents.DEFAULT)
bot.start()
```

### Traceback

No relevant traceback

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by i0bs** [comment]
This might be a related Discord dispatch issue. Have you considered concurrently delaying the async process for a random amount of time between 0.1 - 1 seconds so that there's ample time for the state to change during Gateway dispatch?

**Comment by tequa** [comment]
not sure if this kinda what you mean but I added a lock so only 1 connect or disconnect happens at a time, and I wait a few seconds after each one. I still get the bug:

I'm actually now realizing that the bug doesn't have much to do with concurrency and is even easier to reproduce than I thought. I'm updating the ticket info.

```python
channel_lock = asyncio.Lock()

@interactions.slash_command(
    name="join_voice",
    description="Connect and stay in the voice channel you're currently in",
)
async def join_voice(ctx: SlashContext):
    if not ctx.author.voice:
        await ctx.send("You are not in a voice channel", ephemeral=True)
        return
    channel = ctx.author.voice.channel
    async with channel_lock:
        await channel.connect()
        await asyncio.sleep(2)

    await ctx.send("Joining voice channel!")


@interactions.slash_command(
    name="leave_voice",
    description="Connect and stay in the voice channel you're currently in",
)
async def leave_voice(ctx: SlashContext):
    voice_state = ctx.voice_state
    if not voice_state:
        await ctx.send("I'm not in any voice channel!", ephemeral=True)
        return
    async with channel_lock:
        await voice_state.channel.disconnect()
        await asyncio.sleep(2)
    await ctx.send("Leaving voice channel!")
   ```

**Comment by tequa** [comment]
OK so I just dove a little deeper and it seemed to be an issue with `_on_raw_voice_state_update` in `voice_events.py`. The problem is that that it's grabbing cached `before` data for the user ID, which is fine if you're doing voice updates for actual non-bot users, but if this event is happening on a bot, it's gonna pull the "user" data for that bot, which will be global across guilds. I updated the code so that the bot updates ignore the before data and don't dispatch a voice state update, since this voice state update would be global across all guilds and not useful in any way. This fixed the bug I was encountering.

I'm pasting the code below -- I'm really sorry but I don't have GitHub keys and stuff set up for this account. If it's not too big of a deal could 1 of the developers maybe just put up a PR for this if the code makes sense to you? @i0bs not sure if you work on this

In `voice_events.py` in `_on_raw_voice_state_update`
1. We are first handling bot only updates (which shouldn't be messing with `event.data["user_id"]` at all, since this is the global bot user ID)
2. Then we early return and handle user-only updates
```python
class VoiceEvents(EventMixinTemplate):
    @Processor.define()
    async def _on_raw_voice_state_update(self, event: "RawGatewayEvent") -> None:
        after = await self.cache.place_voice_state_data(event.data)
        is_bot = event.data['member']['user']['bot']

        if is_bot:
            if vc := self.cache.get_bot_voice_state(event.data["guild_id"]):
                # noinspection PyProtectedMember
                await vc._voice_state_update(after, event.data)
            return

        # Following code is for updates to non-bot users
        before = copy.copy(self.cache.get_voice_state(event.data["user_id"])) or None
        self.dispatch(events.VoiceStateUpdate(before, after))

        if before and after:
            if (before.mute != after.mute) or (before.self_mute != after.self_mute):
                self.dispatch(events.VoiceUserMute(after, after.member, after.channel, after.mute or after.self_mute))
            if (before.deaf != after.deaf) or (before.self_deaf != after.self_deaf):
                self.dispatch(events.VoiceUserDeafen(after, after.member, after.channel, after.deaf or after.self_deaf))
            if before.channel != after.channel:
                self.dispatch(events.VoiceUserMove(after, after.member, before.channel, after.channel))
        elif not before and after:
            self.dispatch(events.VoiceUserJoin(after, after.member, after.channel))
        elif before:
            self.dispatch(events.VoiceUserLeave(before, before.member, before.channel))
```

In `active_voice_state.py._voice_state_update` deleted the unused `before` argument for less confusion
```python
    async def _voice_state_update(
        self,
        after: Optional[VoiceState],
        data: Optional[VoiceStateData],
    ) -> None:
        """
        An internal receiver for voice server state events.

        Args:
            after: The current voice state
            data: Raw data from gateway
        """
        if after is None:
            # bot disconnected
            self.logger.info(f"Disconnecting from voice channel {self._channel_id}")
            await self._close_connection()
            self._client.cache.delete_bot_voice_state(self._guild_id)
            return

        self.update_from_dict(data)
```

**Comment by tequa** [comment]
Nevermind I created a PR: https://github.com/interactions-py/interactions.py/pull/1533
