### ISSUE TITLE
User type doesn't work properly in DM.

### ISSUE THREAD

**Issue by AiroPi** [interactions-py/interactions.py#154]
When we pass an user to a slash command, in an argument well typed "User", the argument will be a string, and not discord.User as expected.

There is no problem when the slash is excecuted in a guild.

discord-py-slash-command : version 1.1.1

**Comment by LilSpazJoekp** [comment]
IIRC user type is not available in DM.

**Comment by i0bs** [comment]
Please refer to our #faq channel on our support server.
