### ISSUE TITLE
[FEAT] Option to make "no permission" check response ephemeral

### ISSUE THREAD

**Issue by techguydave** [interactions-py/interactions.py#1548]
### Problem Description

My apologies if I missed something in the documentation that covered this use case.

Currently when running a check on a command, all users in that channel will see the "You do not have permission" message.

```python
async def my_check(ctx: SlashContext):
    return ctx.author.username.startswith('a')

@check(check=my_check)
async def initial_setup(self, ctx: SlashContext):
    [...]
```

![image](https://github.com/interactions-py/interactions.py/assets/2099988/d796c69a-76f7-420f-99c0-9d56596245ff)

### Proposed Solution

Ideally the dev could add something like `ephemeral=True` to make it so that only the user running the command receives the feedback. For backward/non-breaking compatibility this could default to `False`.

```python
async def my_check(ctx: SlashContext):
    return ctx.author.username.startswith('a')

@check(check=my_check, ephemeral=True) # <----
async def initial_setup(self, ctx: SlashContext):
    [...]
```

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
As checks can be used for *any* command, including prefixed commands, I'm not sure if this is necessarily a good idea. Usually the solution is to make a custom error handler for `CommandError` and override the default one - you can usually add in your own flexibility from there.

**Comment by techguydave** [comment]
Thanks, that did the trick! Although I ran into an unrelated error trying to follow the documentation, so here's the solution I came up with:

```python
@listen(CommandError, disable_default_listeners=True)
async def on_command_error(self: CommandError):
    if isinstance(self.error, errors.CommandCheckFailure):
        await self.ctx.send(
            embeds=Embed(
                description="You do not have permission to run this command!",
                color=BrandColors.YELLOW,
            ),
            ephemeral=True
        )
    if not self.ctx.responded:
        await self.ctx.send("Something went wrong.")
```

![image](https://github.com/interactions-py/interactions.py/assets/2099988/4698d517-0edb-41f7-8bfd-076f9923edb1)

Note that I had to use `self: CommandError` instead of `self, event: CommandError`, so instead of `event.ctx` I used `self.ctx`. Otherwise if I used the code in the documentation I received `TypeError: on_command_error() missing 1 required positional argument: 'event'`.

**Comment by AstreaTSS** [comment]
Well, if this is in your main file and not in an extension, that's expected 😅. `self` (or, well, the first variable in any function in a class) is specifically for classes, not outside of it.

**Comment by techguydave** [comment]
Ahhh, ok, so maybe I misunderstood how this all works! So I should be able to put the code from the documentation in my extension's file and it'll _only_ override it for that particular extension?

**Comment by AstreaTSS** [comment]
Not necessarily - no offense, but `self` is kind of a basic Python concept. I'd suggest learning how it's used in detail because of how important it is.

There are ways of having extension wide (as opposed to bot wide) error handlers, but perhaps that's a topic best left for the extension guide or the support server.

Any further help should probably go to the support server.
