### ISSUE TITLE
[FEAT] Add support for editing member flags

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1553]
### Library Version

5.10.0

### Describe the Bug

you can't edit the flags of a member 

### Steps to Reproduce

try to edit the flags of a member

### Expected Results

that you can edit the flags of a member

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by mAxYoLo01** [comment]
Please give us a better understanding of the issue. What code are you trying to use, any errors, etc.

**Comment by Mias15** [comment]
There is no code for a missing attribute... Have a look at https://discord.com/developers/docs/resources/guild#modify-guild-member - you cant edit the member flags.
![image](https://github.com/interactions-py/interactions.py/assets/51890392/e5c26cd4-22b7-49d7-b920-5df75fea8249)
![image](https://github.com/interactions-py/interactions.py/assets/51890392/a16bd966-cdaf-4ae1-92f7-3f7c7785bdf4)

there is no option to edit/change the BYPASSES_VERIFICATION flag of a member
![image](https://github.com/interactions-py/interactions.py/assets/51890392/38c93849-c8fa-4226-ae0d-db23e9d2fc6e)

**Comment by LordOfPolls** [comment]
This isn't a bug. This is a feature request 

I'll look into adding support for this

**Comment by Bastien1533** [comment]
Hi! 
Is this feature request still a thing?
If it is, could I be assigned to it?

Bastien

**Comment by silasary** [comment]
Yeah, go ahead and open a PR :)
