### ISSUE TITLE
[BUG] import issue

### ISSUE THREAD

**Issue by sachamazouz** [interactions-py/interactions.py#1557]
### Library Version

last

### Describe the Bug

after installing the module and importing it using "import interactions", it doesnt detect SlashCommands

### Steps to Reproduce

uninstall and reinstall

### Expected Results

should works

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by LordOfPolls** [comment]
Check your python version - you're almost certainly using an incompatible version. The minimum is python3.10
