### ISSUE TITLE
[BUG] Class `PremiumType` received an invalid and unexpected value `3`

### ISSUE THREAD

**Issue by ryandiamond23** [interactions-py/interactions.py#1564]
### Library Version

5.10.0

### Describe the Bug

After upgrading to latest version, I am seeing the following error showing in my bot logs:

10/21/2023 00:03:36 - [DEBUG]: Fetching Discord client token secret
10/21/2023 00:03:36 - [DEBUG]: Successfully retrieved Discord client token
10/21/2023 00:03:36 - [INFO]: Discord bot starting...
10/21/2023 00:03:37 - [DEBUG]: Discord bot started!
Class `PremiumType` received an invalid and unexpected value `3`, a new enum item will be created to represent this value. Please update interactions.py or report this issue on GitHub - https://github.com/interactions-py/interactions.py/issues

### Steps to Reproduce

Start bot using latest version.

### Expected Results

No error is shown in the logs when starting bot.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by LordOfPolls** [comment]
This has already been reported and fixed in 

https://github.com/interactions-py/interactions.py/pull/1563
