### ISSUE TITLE
[Docs]: Documentation link from PyPi is broken

### ISSUE THREAD

**Issue by coreyb42** [interactions-py/interactions.py#1566]
### Page

https://pypi.org/project/interactions.py/

### Problem description

The "Documentation" link on PyPi leads to https://naff-docs.readthedocs.io/en/latest/, which itself just has a broken link to a "naff" domain that is parked.

### Suggested changes

PyPi should link directly to the current documentation at https://interactions-py.github.io/interactions.py/

**Comment by LordOfPolls** [comment]
This will be fixed in the next release. Thank you for reporting this
