### ISSUE TITLE
[BUG] Moderated argument missing for tags

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1591]
### Library Version

5.11.0

### Describe the Bug

While creating a new tag for a forum you can set the moderation value for it. 

![image](https://github.com/interactions-py/interactions.py/assets/51890392/af101b91-e144-4b91-967d-c8e71b5129b2)

![image](https://github.com/interactions-py/interactions.py/assets/51890392/131b8810-ba25-4b13-9f92-36a5695011a3)
https://discord.com/developers/docs/resources/channel#forum-tag-object-forum-tag-structure

### Steps to Reproduce

Try to create a mod only tag for a forum channel.

### Expected Results

That you can make the tag mod only

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by eightween** [comment]
Is this only an issue for `.create_tag()`? This also appears to be a feature request since it's missing functionality.
