### ISSUE TITLE
[FEAT] Add create_invite method to GuildForum

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1592]
### Library Version

5.11.0

### Describe the Bug

`AttributeError: 'GuildForum' object has no attribute 'create_invite'`
![image](https://github.com/interactions-py/interactions.py/assets/51890392/6ab266eb-d073-4663-a856-770755bab2b4)

### Steps to Reproduce

Try creating an invitation for a forum channel.

### Expected Results

That you can create one.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by eightween** [comment]
This is a feature request, I suggest submitting a PR (you or anyone else for that matter) for implementing this.
