### ISSUE TITLE
[BUG] AuditLogEventType 192 missing 

### ISSUE THREAD

**Issue by ryandiamond23** [interactions-py/interactions.py#1596]
### Library Version

stable

### Describe the Bug

Seeing the following error in bot logs:
Class `AuditLogEventType` received an invalid and unexpected value `192`, a new enum item will be created to represent this value. Please update interactions.py or report this issue on GitHub - https://github.com/interactions-py/interactions.py/issues

### Steps to Reproduce

TBD, trying to determine which audit log event corresponds to ID 192 so that the enums can be updated.

### Expected Results

No AuditLogEventType event code errors shown in bot log output.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

Enum needs to be set, but need to first identify what event 192 is. Discord Docs don't have anything listed, either. 

https://discord.com/developers/docs/resources/audit-log#audit-log-change-object-audit-log-change-exceptions
https://github.com/interactions-py/interactions.py/blob/stable/interactions/models/discord/enums.py#L992

**Comment by ryandiamond23** [comment]
Opening this issue to track -- I'm trying to identify which event 192 corresponds to and will open a MR with the fix once identified.

**Comment by Mias15** [comment]
@ryandiamond23
192 = channel status added/changed
193 = channel status removed
![image](https://github.com/interactions-py/interactions.py/assets/51890392/acc48e84-f42d-4a66-8244-8bec59eac940)

**Comment by Scrxtchy** [comment]
here is what's from the canary dist that isn't covered by the enum if someone would like to contribute it. The names may change in the future like they have in the past (we don't match very accurately anymore)
```js
{
                VOICE_CHANNEL_STATUS_CREATE: 192,
                VOICE_CHANNEL_STATUS_DELETE: 193,
                CLYDE_AI_PROFILE_UPDATE: 194,
                GUILD_SCHEDULED_EVENT_EXCEPTION_CREATE: 200,
                GUILD_SCHEDULED_EVENT_EXCEPTION_UPDATE: 201,
                GUILD_SCHEDULED_EVENT_EXCEPTION_DELETE: 202
```
