### ISSUE TITLE
docs: Introduction

### ISSUE THREAD

**Issue by austinrscott** [interactions-py/interactions.py#1597]
### Page

Introduction : /Guides/01 Getting Started/

### Problem description

Examples are outdated and don't work. Python library does not even contain the imports specified in the examples.

### Suggested changes

Someone who is familiar with the 5.x.x API should go through and make sure everything still works.

**Comment by AstreaTSS** [comment]
The examples... do work as intended, though - I've used that example as a test bot for stuff plenty of times, and it's been working all the way to the latest version. Are you sure you're installing the library with Python 3.10 or greater?

**Comment by austinrscott** [comment]
I saw your comment and came back to try again. I believe I was using 3.11 at the time, but I don't know. When I wrote this ticket, I was coding from within an IDE (PyCharm) and I just tried it successfully on a bare terminal with no frills. My bad--sorry for raising the issue.
