### ISSUE TITLE
ModuleNotFoundError: No module named 'interactions' Whilist not having an activated virtual envirovment

### ISSUE THREAD

**Issue by MFFTD** [interactions-py/interactions.py#1599]
### Library Version

5.11.0

### Describe the Bug

Trying to run my python file outside of virtual envirovement results into "**ModuleNotFoundError: No module named 'interactions'"** , but when I activate my virtual envirovement with **source venv/bin/activate** and then run the python file, then I don't get this error.

### Steps to Reproduce

-have a python file that has this line of code  **import interactions**
-run the file with python filename.py without activating virtual envirovment

### Expected Results

ModuleNotFoundError: No module named 'interactions'

### Minimal Reproducible Code

```python
import interactions
from interactions.models import OptionType 
import random
import discord
from discord.ext import commands

bot = interactions.Client(
    token="",
    default_scope=1195760890130206740,
)

queue = []

# /join slash command
@interactions.slash_command()
async def join(ctx: interactions.ComponentContext):
    # user = ctx.author.mention
    user = ctx.author.id  # Change here to get user ID

    if user in queue:
        await ctx.send("You are already in the queue.")
        return
    queue.append(user)

    embed = interactions.Embed(
        title="5 v 5",
        description=f"{ctx.author.mention} has joined the queue `[{len(queue)}/2]`",
        color=0xFFFF00
    )
    await ctx.send(embed=embed)

bot.start()
```

### Traceback

This is from my desktop pc
------------------------------------------------------
[pc@archlinux bee]$ python main.py
Traceback (most recent call last):
  File "/home/kp/Documents/bee/main.py", line 1, in <module>
    import interactions
ModuleNotFoundError: No module named 'interactions'
[pc@archlinux bee]$ source venv/bin/activate
(venv) [pc@archlinux bee]$ python main.py
---------------------------------------------------------------
This is from PebbleHost cloud server
-----------------------------------------------------
14.01 17:09:13 [PebbleHost Loader] ----------------------------------------------
14.01 17:09:13 [PebbleHost Loader] PebbleHost Bot Loader now starting...
14.01 17:09:13 [PebbleHost Loader] Running loader version Bot-1.2.1
14.01 17:09:13 [PebbleHost Loader] Checking for Configured Reverse Proxy...
14.01 17:09:13 [PebbleHost Loader] Attempting to boot with the following settings: SERVER ID: , MEMORY: 1024M
14.01 17:09:13 [PebbleHost Loader] Found pebble-python-config.json
14.01 17:09:13 [PebbleHost Loader] Found requirements.txt
14.01 17:09:13 [PebbleHost Loader] Using Python Version 3.9
14.01 17:09:13 [PebbleHost Loader] Updating pip packages (command output is in logs/2024-01-14_17-09-13.txt)...
14.01 17:09:13 [PebbleHost Loader] Installing aiohttp==3.9.1
14.01 17:09:15 [PebbleHost Loader] Installing aiosignal==1.3.1
14.01 17:09:16 [PebbleHost Loader] Installing attrs==23.2.0
14.01 17:09:16 [PebbleHost Loader] Installing discord-py-interactions==5.11.0
14.01 17:09:17 [PebbleHost Loader] Installing discord-typings==0.7.0
14.01 17:09:18 [PebbleHost Loader] Installing discord.py==2.3.2
14.01 17:09:19 [PebbleHost Loader] Installing emoji==2.9.0
14.01 17:09:20 [PebbleHost Loader] Installing frozenlist==1.4.1
14.01 17:09:22 [PebbleHost Loader] Installing idna==3.6
14.01 17:09:23 [PebbleHost Loader] Installing multidict==6.0.4
14.01 17:09:24 [PebbleHost Loader] Installing tomli==2.0.1
14.01 17:09:25 [PebbleHost Loader] Installing typing_extensions==4.9.0
14.01 17:09:25 [PebbleHost Loader] Installing yarl==1.9.4
14.01 17:09:26 [PebbleHost Loader] Starting file main.py
14.01 17:09:26 [PebbleHost Loader] ----------------------------------------------
14.01 17:09:26 [Bot] Traceback (most recent call last):
14.01 17:09:26 [Bot] File "/main.py", line 1, in <module>
14.01 17:09:26 [Bot] import interactions
14.01 17:09:26 [Bot] ModuleNotFoundError: No module named 'interactions'
14.01 17:09:27 [PebbleHost] Server shut down (running)
14.01 17:09:27 [PebbleHost] Server stopped

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

I ran my sourcecode inside activated virtual envirovment and everything works fine.
I then ran the command "pip freeze > requirements.txt "inside my virtual envirovment and got the list of dependicies.

Then I Uploaded my sourcecode to cloud hosting server and also uploaded the requirements and started up the cloud server and I get the error **ModuleNotFoundError: No module named 'interactions'**

**Comment by AstreaTSS** [comment]
This is definitely an issue with your starting script, not the library. The library already has been proven to work outside of a virtualenv - rather, either PebbleHost or you are likely messing something up here.

As this isn't a place for support (not like I use PebbleHost as my host anyways, so I wouldn't know how to fix it), I'll be closing this.

**Comment by MFFTD** [comment]
sounds good, and sorry
