### ISSUE TITLE
[Feature Request] Permission Check 

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#160]
Can you make a permission check that makes that only permitted users get shown a command, e.g.

only if a user have the permission ban_members, he can see the command /ban

**Comment by LordOfPolls** [comment]
No. Unfortunately discord doesn't provide that functionality for slash commands. 

A permissions decorator is being worked on, but unfortunately it works based on roles as per Discord's API

I would advise joining the support server if you have any questions
