### ISSUE TITLE
Implement SlashCommandOptionType.MENTIONABLE

### ISSUE THREAD

**Issue by Luc1412** [interactions-py/interactions.py#161]
Discord just released option type 9 which is mentionable. It includes Members and Roles. It's currently undocumented, buts work fine.

**Comment by i0bs** [comment]
v9 won't be out for another 2 months, we'll keep this as a pending for now because we frankly can't test just yet.

**Comment by Luc1412** [comment]
> v9 won't be out for another 2 months, we'll keep this as a pending for now because we frankly can't test just yet.

@goverfl0w I think this isn't v9 related. I was able to create this OptionType with the create_option function. It works well. Just the handler + documentation is missing.

**Comment by quirky-bluejay** [comment]
This isn't related to v9
Does it work on stable?

**Comment by Luc1412** [comment]
> This isn't related to v9
> Does it work on stable?

@AnotherCat I tested it. It works fine on Desktop Canary, PTB, Stable. On IOS it crashed Discord. So it might be worth starting adding it and scheduling the stable release.

**Comment by LilSpazJoekp** [comment]
> On IOS it crashed Discord.

Does it crash on the TestFlight version or just release?

**Comment by Luc1412** [comment]
> > On IOS it crashed Discord.
> 
> Does it crash on the TestFlight version or just release?

Am using the stable IOS. I got no access to TestFlight.

**Comment by LilSpazJoekp** [comment]
> > > On IOS it crashed Discord.
> 
> > 
> 
> > Does it crash on the TestFlight version or just release?
> 
> 
> 
> Am using the stable IOS. I got no access to TestFlight.

I have access to the TestFlight version. I'll hit you up on discord.

**Comment by LilSpazJoekp** [comment]
Just checked on the TestFlight version and it crashes on the version as well.

**Comment by Luc1412** [comment]
Mentionable is now officially mentioned in Discord Docs

**Comment by quirky-bluejay** [comment]
https://github.com/discord/discord-api-docs/issues/2878

**Comment by i0bs** [comment]
Hotfix was given under stable awhile ago, closing.
