### ISSUE TITLE
option_type isn't working

### ISSUE THREAD

**Issue by Melumi11** [interactions-py/interactions.py#163]
I created two slash commands with option_type 3 and 4 which is supposed to make it require an int and string but instead I can type whatever I want when using the slash command.
`@slash.slash(name="roll", description="Dice roll command",
                options=[create_option(
                    name="d",
                    description="Roll a d-sided die",
                    option_type=3,
                    required=True)])`
`async def roll(ctx, d):
        await ctx.send(content=str(random.randint(1, int(d))))`
I haven't tested any of the other option types but this worked the last time I created slash commands. Thanks.

**Comment by quirky-bluejay** [comment]
The code you gave uses option type 3, which is a string, which will allow any characters

**Comment by Melumi11** [comment]
Oops, never mind then.
Thanks for correcting my mistake!
