### ISSUE TITLE
[BUG] TypeError on SlashCommand Option Definition

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#1630]
### Library Version

5.11.0

### Describe the Bug

While attempting to define options for a slash command using the `interactions.py` library, I encountered a `TypeError`. The error occurs when adding options to the `@slash_command` decorator: the library seems to expect a sorted list of options but receives a function object instead, leading to the error `'function' object is not subscriptable`.

### Steps to Reproduce

1. Define a new slash_command with options using the interactions.py library.
2. Use the Option object to define the options for the command.
3. Attempt to run the bot and register the command with Discord.

### Expected Results

The slash command with its options should be successfully defined, and the bot should start without any `TypeError`.

### Minimal Reproducible Code

```python
import os
from interactions import Client, Intents, slash_command, slash_option, OptionType, SlashCommandChoice

intents = Intents.DEFAULT | Intents.GUILD_MEMBERS | Intents.GUILD_MESSAGES
bot = Client(token=os.environ['TOKEN'], intents=intents)

@slash_command(
    name="role",
    description="Add or Remove a role from a member.",
    options=[
        slash_option(
            opt_type=OptionType.STRING,
            name="action",
            description="add or remove",
            required=True,
            choices=[
                SlashCommandChoice(name="add", value="add"),
                SlashCommandChoice(name="remove", value="remove")
            ],
        ),
        slash_option(
            opt_type=OptionType.STRING,
            name="role_name",
            description="The role's name",
            required=True,
        ),
        slash_option(
            opt_type=OptionType.USER,
            name="member",
            description="Member to add or remove a role from",
            required=True,
        )
    ]
)
async def role(ctx: SlashContext, action: str, role_name: str, member: Member):
    pass

bot.start()
```

### Traceback

```
Traceback (most recent call last):
  File "/home/runner/Discord-interactionspy/main.py", line 128, in <module>
    async def role(ctx: SlashContext, action: str, role_name: str, member: Member):
  File "/home/runner/Discord-interactionspy/.pythonlibs/lib/python3.10/site-packages/interactions/models/internal/application_commands.py", line 958, in wrapper
    cmd = SlashCommand(
  File "<attrs generated init interactions.models.internal.application_commands.SlashCommand>", line 46, in __init__
  File "/home/runner/Discord-interactionspy/.pythonlibs/lib/python3.10/site-packages/interactions/models/internal/application_commands.py", line 717, in options_validator
    if value != sorted(
  File "/home/runner/Discord-interactionspy/.pythonlibs/lib/python3.10/site-packages/interactions/models/internal/application_commands.py", line 719, in <lambda>
    key=lambda x: x.required if isinstance(x, SlashCommandOption) else x["required"],
TypeError: 'function' object is not subscriptable
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
Hello - please take a look [at the guide for slash commands](https://interactions-py.github.io/interactions.py/Guides/03%20Creating%20Commands/#options) to see proper usage of `slash_option` - essentially, it's not like this.
