### ISSUE TITLE
[BUG] Occasionally VoiceChannel is None 

### ISSUE THREAD

**Issue by DeJayDev** [interactions-py/interactions.py#1644]
### Library Version

5.11.0

### Describe the Bug

Occasionally, the built in cache receives None for VoiceChannel when trying to access `_voice_member_ids`. I believe this has to do with not having the `VOICE_STATE_UPDATE` intent.

### Steps to Reproduce

Run an interactions.py bot with Sentry enabled and inspect the error log occasionally.

### Expected Results

Ideally, the library isn't sending errors to Sentry :)

### Traceback

```py
AttributeError: 'NoneType' object has no attribute '_voice_member_ids'
  File "interactions/client/smart_cache.py", line 767, in place_voice_state_data
    if user_id in old_state.channel._voice_member_ids:
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by silasary** [comment]
Ah, I see what's happening here.  Shouldn't be too hard to fix.
