### ISSUE TITLE
Option Types 2 and 3 are no longer allowed?

### ISSUE THREAD

**Issue by Aida-Enna** [interactions-py/interactions.py#166]
I have some code that was working fine a few days ago, that is now being rejected by the API. I wrote some test code to double check it, and it still fails. The code:

```python
@slash.slash(
  name="test",
  description="Tests stuff",
  options=[
    create_option(
      name="Option",
      description="The first option",
      choices=[
        create_choice(
          value="One",
          name="Choice 1"
        ),
        create_choice(
          value="Two",
          name="Choice 2"
        )
      ],
      option_type=3,
      required=True
    )
  ],
guild_ids=fleet)
async def test_stuff(ctx, option): # Daily lookup command
    try:
        await ctx.send(option, hidden=True)

    except Exception as e:
        print('[Error] Issue with sending test stuff:\n' + traceback.format_exc())
```

This gives me:

```python
[05/02/2021 09:44:48 AM] [Error] Issue with sending test stuff:
Traceback (most recent call last):
  File "./MekaPython.py", line 141, in test_stuff
    await ctx.send(option, hidden=True)
  File "/usr/local/lib/python3.6/dist-packages/discord_slash/context.py", line 157, in send
    await self.respond(eat=hidden)
  File "/usr/local/lib/python3.6/dist-packages/discord_slash/context.py", line 106, in respond
    await _task
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In type: Value must be one of (1, 4, 5, 6, 7).
```

**Comment by quirky-bluejay** [comment]
This isn't an issue with option types, it's an issue with older versions of the lib using deprecated response types. Update the lib

**Comment by Aida-Enna** [comment]
I am using the latest version of both this library and discord.py.

```
pip show discord.py
Name: discord.py
Version: 1.7.1
pip show discord-py-slash-command
Name: discord-py-slash-command
Version: 1.1.2
```

**Comment by quirky-bluejay** [comment]
Then you won't be getting this issue 🤷 
Check that if you're using a virtual environment that you've updated them in that, and that you've restarted the bot process

**Comment by Aida-Enna** [comment]
I'm not using a virtual environment, and I've restarted a bunch too. One of your Helpers in the discord (Lord Of Pools, Oxi) confirmed that the issue happens as well. It appears it doesn't happen if you switch to cogs with the same code, though.

**Comment by gabrielcastelan** [comment]
Wait no I said it [works for me](https://canary.discord.com/channels/789032594456576001/789032934648447016/838414008310431784) on a cog

**Comment by Aida-Enna** [comment]
You said ["I'm testing it myself and yea"](https://discord.com/channels/789032594456576001/789032934648447016/838410899085197312) and confirmed I should make a PR for it >.> but if it's not happening for you, then I guess it's just me and something on my side. I'll try to figure it out.

**Comment by gabrielcastelan** [comment]
oh my gah literally 4 messages later I said it actually worked and I didn't even mention a PR here, but anyways we're kinda reviving a dead issue here

**Comment by quirky-bluejay** [comment]
> I'm not using a virtual environment, and I've restarted a bunch too. One of your Helpers in the discord (Lord Of Pools, Oxi) confirmed that the issue happens as well. It appears it doesn't happen if you switch to cogs with the same code, though.

I **cannot** reproduce this, and again the error that you gave is about the interaction response type, which has nothing to do with options.
If you want to check the version that is being used when the code is run try printing `discord_slash.__version__` 🙂

**Comment by Wolfhound905** [comment]
@Aida-Enna I just tried your code but put the options and stuff into a dictionary instead, it just looks neater in my opinion, and the command was created just fine. Here is the code 
```py
test_options = [
    {
        "name": "option",
        "description": "Tests stuff",
        "type": 3,
        "required": True,
        "choices": [
            {
                "name": "Choice 1",
                "value": "One"
            },
            {
                "name": "Choice 2",
                "value": "Two"
            },
        ]
    }
]

@slash.slash(name="test", options=test_options, description="Tests stuff", guild_ids=guilds)
async def test(ctx: SlashContext, option: str):
    await ctx.send(option)

```
![image](https://user-images.githubusercontent.com/58155937/116954947-3a9a6680-ac5f-11eb-84f3-297d86e78c05.png)
I do not see what the issue is 🤷‍♂️ 

More info:
discord-py-slash-command==1.1.0
Using python 3.9.4
Using a virtual env
