### ISSUE TITLE
[BUG] module

### ISSUE THREAD

**Issue by SuitedNerd** [interactions-py/interactions.py#1667]
### Library Version

the latest one

### Describe the Bug

when i install discord-py-slash-command it still says module not found named discord_slash

### Steps to Reproduce

.

### Expected Results

working.

### Minimal Reproducible Code

```python
import os
import discord
import re
import requests
from keep_alive import keep_alive
from googlesearch import search
from bs4 import BeautifulSoup
from discord.ext import commands
from discord_slash import SlashCommand, SlashContext

-----------------------------------------------------------------

Import "discord_slash" could not be resolved
```

### Traceback

PS C:\Users\Naam> & C:/Users/Naam/AppData/Local/Programs/Python/Python312/python.exe c:/Users/Naam/Desktop/Seal/main.pyaam/Desktop/Seal/main.py
Traceback (most recent call last):
  File "c:\Users\Naam\Desktop\Seal\main.py", line 6, in <module>
    from discord_slash import SlashCommand
ModuleNotFoundError: No module named 'discord_slash'

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

.

**Comment by AstreaTSS** [comment]
You are trying to use the current version of the library as a version of the library which has been non-existent for 2+ years. No support will be provided for old versions like that.
