### ISSUE TITLE
[BUG] Interactions not recognizing guilg

### ISSUE THREAD

**Issue by midoalawieh** [interactions-py/interactions.py#1669]
### Library Version

5.11.0

### Describe the Bug

The code is not recognizing the guild, no matter what i do, when i try to use guild, it says its a nonetpye object

### Steps to Reproduce

just add any guild like ```bot.get_guild(Id)```, and try to use it

### Expected Results

i expect guild to b e a name, but its a none

### Minimal Reproducible Code

```python
from interactions import Intents , Client
ID = 1 #your id here
bot = Client(intents=Intents.DEFAULT)
guild = bot.get_guild(ID)
print(guild) #this prints none
bot.start("") #your token here
```

### Traceback

thois traceback happens if it ry stufff like guild,create_channel
    guild.create_channel(channel_type="text", name="hey")
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_channel'

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
This isn't a support channel, nor is this a bug (the cache will naturally have nothing before the bot starts). If you're looking for support, please [join the support server](https://discord.gg/interactions).
