### ISSUE TITLE
`import discord` import detected.  Interactions.py is a completely separate library, and is not compatible with d.py models.

### ISSUE THREAD

**Issue by Developer-Striker** [interactions-py/interactions.py#1671]
### Library Version

Latest pip install -U discord-py-interactions

### Describe the Bug

Well, I have updated my PIP discord interactions and downloaded all needed contents, but it seems like my code isn't able to read any module in my code eventhough there are clearly some. I don't know how to fix this because it keeps redirecting me to this github, although nothing happens. I've searched thoroughly, I'm new to python soo, I wish someone will be able to help.

### Steps to Reproduce

import discord

from discord import app_commands
from discord.ext import commands
from interactions import Client, Intents 
from interactions.ext import prefixed_commands 
from interactions.ext.prefixed_commands import prefixed_command, PrefixedContext

intents = discord.Intents.default()
intents.members = True  
intents.message_content = True
intents.presences = True

client = commands.Bot(command_prefix="", intents = discord.Intents().all())
bot = commands.Bot(command_prefix="!", intents = discord.Intents.all())

@client.event
async def on_ready():
    print("Bot is Striking and striving!")
    try:
        synced = await client.tree.sync()
        print(f"Synced {len(synced)} command(s)")
    except Exception as e:
        print(e)

@client.tree.command(name="greetings")
async def greetings(interaction: discord.Interaction):
    await interaction.response.send_message(f"Hey {interaction.user.mention}! I'm penghwin! Nice to meet you! ^v^ ")

@client.tree.command(name="deliver")
@app_commands.describe(deliver_message = "What message do you want to deliver? ^v^")
async def deliver(interaction: discord.Interaction, deliver_message: str):
    await interaction.response.send_message(f"{interaction.user.mention} Delivered a message ^v^ : '{deliver_message}'")
    
    It should read a module named interactions since I'm creating slash commands for my discord bot. Yet, It says on the terminal that, It doesn't have a module named interactions.

![image](https://github.com/interactions-py/interactions.py/assets/168578967/38259162-1de1-4393-a6a1-81e4d2bb607e)

### Expected Results

Well, my expected result is to be able to do a slash command. It does work, But not in Terminal Debug Command. But in the Output Debug Command on my Visual Studio Code. But I don't know if output debug command in VSC is enough to maintain my bot's functionality.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
As your title says, you cannot mix `discord.py` and `interactions.py`, as they are two separate libraries. `interactions.py` *used* to be an extension to `discord.py` years ago, but it no longer is, and we do not support versions which are extensions of `discord.py`.

Please pick one of the libraries, as both have slash commands by now. You should also ask for help in their support servers, not on GitHub Issues.
