### ISSUE TITLE
[BUG] Member object has no 'guild_banner' or 'display_banner'

### ISSUE THREAD

**Issue by Mias15** [interactions-py/interactions.py#1674]
### Library Version

5.12.0

### Describe the Bug

In the member object, you can currently only get the normal banner of the user (member.banner), but it is not possible to get any server specific banner (banner.guild_banner).

### Steps to Reproduce

.

### Expected Results

.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by mifuyutsuki** [comment]
As it stands, server profile banner is yet to be part of the Discord API [guild member object](https://discord.com/developers/docs/resources/guild#guild-member-object) the way server profile _avatar_ is. For this to be added as a feature, we would have to wait for Discord themselves to add it specifically - at least a GET endpoint returning the server profile banner, which I at least have yet to know of.

See also the feature request for this field in discord/discord-api-docs/discussions/4217

**Comment by Mias15** [comment]
mb... I could have checked that before. Thanks anyway!
