### ISSUE TITLE
[BUG] ActivityType.CUSTOM will not error when state is not defined 

### ISSUE THREAD

**Issue by LawMixer** [interactions-py/interactions.py#1679]
### Library Version

5.12.1

### Describe the Bug

``ActivityType.CUSTOM`` does not error when it is set as ``Activity(state=None)``, as it is invalid.

### Steps to Reproduce

Look at the Minimal Reproducible Code section.

### Expected Results

``ActivityType.CUSTOM`` should error when it is set as ``Activity(state=None)`` 

### Minimal Reproducible Code

```python
from interactions import (
    Client,
    Intents, 
    ActivityType, 
    Activity, 
    Status, 
    listen
)

intents = Intents.DEFAULT | Intents.MESSAGE_CONTENT
my_activity = Activity(type=ActivityType.CUSTOM, state=None, name="Example Activity", details="Hi", application_id=879808043787907103)
client = Client(intents=intents, activity=my_activity, status=Status.ONLINE)


@listen()
async def on_ready():
    print(f"We're online! We've logged in as {client.app.name}.")


client.start("token here")
```

### Traceback

None provided.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

None.

**Comment by AstreaTSS** [comment]
~~The example you give has state set to something, so I'm a bit confused on that.~~ (fixed in an edit)

Regardless, `ActivityType` does not validate field combinations in general. I'm not sure if it should, suggesting how dynamic the Discord API is.

**Comment by LawMixer** [comment]
Oh, I'm dumb...accidently set state to something..I've fixed this. 

I was using ``ActivityType.CUSTOM`` for the example, this is what is looks like when set:
![vL5YJUm](https://i.imgur.com/vL5YJUm.png)


This is on Discord's Rich Presence website:
![dE8YMtq](https://i.imgur.com/dE8YMtq.png)

**Comment by AstreaTSS** [comment]
That... seems normal, yes. The issue isn't about what happens when it's set though, right?

**Comment by LawMixer** [comment]
It seems to be set wrong, it looks to be set in the custom status field, not custom activity field not unless this is suppose to be like this?

**Comment by AstreaTSS** [comment]
No, that's correct. `CUSTOM` isn't for rich presences, it just allows for bots to have a custom status field instead of the usual "Playing X" or "Watching X".

**Comment by LawMixer** [comment]
Ahhh, alright..my mistake. will close this issue then, thanks!
