### ISSUE TITLE
[BUG] audioop is deprecated and to be removed in Python 3.13

### ISSUE THREAD

**Issue by AstreaTSS** [interactions-py/interactions.py#1685]
### Library Version

unstable

### Describe the Bug

Currently, in our voice support, we [use audioop](https://github.com/interactions-py/interactions.py/blob/a8f6fcfc165d11efed3a623c2d9e32a5caf4595e/interactions/api/voice/audio.py#L1) for a [specific line](https://github.com/interactions-py/interactions.py/blob/a8f6fcfc165d11efed3a623c2d9e32a5caf4595e/interactions/api/voice/audio.py#L381) in it. As noted in [PEP 594](https://peps.python.org/pep-0594/#audioop) though, audioop is deprecated and will be removed in Python 3.13.

Voice support will be broken in Python 3.13 because of this, and reimplementing the one line we use is *not* trival.

### Steps to Reproduce

Use `interactions.py` in Python 3.13, and especially the voice features.

### Expected Results

...it to work, I guess.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

Thankfully for us, [discord.py also faces this issue](https://github.com/Rapptz/discord.py/issues/9477) and one of its contributors made an [LTS version of audioop](https://github.com/AbstractUmbra/audioop) that looks like a great solution. It's not on pip yet [as the developer needs to test it](https://github.com/Rapptz/discord.py/issues/9477#issuecomment-1911031959), but hopefully it should be ready soon enough.

This issue is more to make sure we're aware of the problem more than anything else.

**Comment by wilson0x4d** [comment]
a python drop-in for the volume transform actually is trivial, this took about 10 minutes:

https://gist.github.com/wilson0x4d/c434b95939d7920f4a213286733cf1a3

verified on an overburdened k8s cluster running containerized bots, no audio issues.

**Comment by AstreaTSS** [comment]
Thanks, but this issue has already been resolved.
