### ISSUE TITLE
I don't know if I'm doing this right

### ISSUE THREAD

**Issue by LBTheHinzers** [interactions-py/interactions.py#1686]
### Library Version

4.2.1

### Describe the Bug

I have it installed but when I do ``from discord_slash import SlashCommand, SlashContext`` it says

Severity	Code	Description	Project	File	Line	Suppression State

Warning (active)	reportMissingImports	Import "discord_slash" could not be resolved		c:\Users\PC\source\repos\*******\PIL.py 3

### Steps to Reproduce

By installing pip install discord-py-slash-command

### Expected Results

For it to work

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
interactions.py v4 and lower is no longer supported. Please either upgrade or use a different Discord library.
