### ISSUE TITLE
[BUG] WARNING:interactions:Class `ChannelType` received an invalid and unexpected value `Missing`, a new enum item will be created to represent this value.

### ISSUE THREAD

**Issue by bakert** [interactions-py/interactions.py#1707]
### Library Version

5.12.1

### Describe the Bug

Looking for a channel that doesn't exist the library emits this message:

```
WARNING:interactions:Class `ChannelType` received an invalid and unexpected value `Missing`, a new enum item will be created to represent this value. Please update interactions.py or report this issue on GitHub - https://github.com/interactions-py/interactions.py/issues
```

### Steps to Reproduce

```
from interactions import Extension

class BackgroundTasks(Extension):
    @listen()
    async def on_startup(self) -> None:
        await self.prepare_tournaments()

        async def prepare_tournaments(self) -> None:
            tournament_channel_id = 1 # An int, but not one that corresponds to a real channel on the current server.
            channel = await self.bot.fetch_channel(tournament_channel_id)
```

### Expected Results

No warning about an enum when running this code.

### Minimal Reproducible Code

```python
from interactions import Extension

class BackgroundTasks(Extension):
    @listen()
    async def on_startup(self) -> None:
        await self.prepare_tournaments()

        async def prepare_tournaments(self) -> None:
            tournament_channel_id = 1 # An int, but not one that corresponds to a real channel on the current server.
            channel = await self.bot.fetch_channel(tournament_channel_id)
```
```


### Traceback

_No response_

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

_No response_

**Comment by AstreaTSS** [comment]
This happens thanks to the [fallback code for fetching channels](https://github.com/interactions-py/interactions.py/blob/87f814f8e66debdb2d4700c840e0f04be483cc4f/interactions/client/smart_cache.py#L475), and so I'm calling this working as intended.

**Comment by bakert** [comment]
Should probably remove the message asking people to report it?

`Please update interactions.py or report this issue on GitHub - https://github.com/interactions-py/interactions.py/issues`

**Comment by AstreaTSS** [comment]
This would unfortunately have unintended side effects since that message is used in a variety of cases. Even adding a special case for `Missing` could cause issues with things slipping by when they shouldn't.

I believe I've argued for the "report this issue" part to be removed from the general message a long time ago, but to be fair, we usually do need to add what values they have.

**Comment by AstreaTSS** [comment]
No idea why it reopened, reclosing.
