### ISSUE TITLE
"command name is invalid"

### ISSUE THREAD

**Issue by mavdotj** [interactions-py/interactions.py#172]
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at /opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/client.py:294> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn 1.options.0.name: Command name is invalid')>
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_slash/client.py", line 341, in sync_all_commands
    await self.req.put_slash_commands(slash_commands=to_send, guild_id=scope)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 1.options.0.name: Command name is invalid

**Comment by mavdotj** [comment]
```python3
@slash.slash(name="speak",
             description="Speak using an embed so you look kool or sumthin",
             options=[
                 create_option(name="message",
                               description="the message to say",
                               option_type=3,
                               required=True)
             ])
async def _speak(ctx: SlashContext, message: str):
    getwho = f'{ctx.author}'.split('#')
    whodid = getwho[0]
    embed = discord.Embed(title=f'``{whodid}``: **{message}**')
    await ctx.send(embeds=[embed])

@slash.slash(name="ai",
             description="Talk to an AI bot",
             options=[
               create_option(
                 name="Chat",
                 description="Chat with an AI",
                 option_type=3,
                 required=True,
               )
             ])
async def _ai(ctx: SlashContext, Chat: str):
	response = ai.message(f'{Chat}')
	await ctx.send(content=f'{response}')
```

**Comment by quirky-bluejay** [comment]
Command names and option names cannot have upper case characters
