### ISSUE TITLE
[BUG] Command not appearing in DM even with dm_permission set to True

### ISSUE THREAD

**Issue by BigChungus888** [interactions-py/interactions.py#1737]
### Library Version

5.13.2

### Describe the Bug

As the title suggests. And I found a very interesting thing, the command only get added to DM if scope field is empty. 

### Steps to Reproduce

Try creating a slash command scopes and dm_permission.

### Expected Results

Command added to the scopes I specified and added to DM.

### Minimal Reproducible Code

```python
base = ipy.SlashCommand(name="match", description="", scopes=GUILD_IDS, dm_permission=True)
```

### Traceback

None

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

**Comment by AstreaTSS** [comment]
This is intentional. Discord treats DMs as part of the global scope (aka no scope), and naturally, a guild scope does not include the global scope.

**Comment by BigChungus888** [comment]
> This is intentional. Discord treats DMs as part of the global scope (aka no scope), and naturally, a guild scope does not include the global scope.

A question, I have synced it as guild scope then I changed it to global scope and synced again. Now I get two commands from two different scope. So my question is, when I change from guild to global, should not the old guild scope command to removed?

**Comment by PythiaUF** [comment]
Please join the support server for questions like this (interactions.py does not delete no longer existing slash commands by default for technical reasons).

**Comment by AstreaTSS** [comment]
Please join the support server for this (that being said, that behavior is also not a bug).
