### ISSUE TITLE
Inconsistent behavior around mentions, defer and hidden.

### ISSUE THREAD

**Issue by soupglasses** [interactions-py/interactions.py#175]
When using hidden and/or defer together with pinging mentions, it breaks the notifying mention. I am not sure if this is an issue on Discords end or this projects end. Id like more input on that.

The wanted end result:
- Have notifying pings work inside of a deferred slash command.
- Have notifying pings work inside of a hidden slash command.

The tests I did:
- `ctx.send()` returns with the `mentions: [...]` in debug response. Pings user!
- `ctx.send(hidden=True)` gives a vague 204 "No Content" response. No ping.
- `ctx.defer(); ctx.send()` returns the `'mentions': [...]` for the mention but does not ping.
- `ctx.defer(hidden=True); ctx.send()` returns an empty `mentions: []`. No ping.
- `ctx.defer(hidden=True); ctx.send(hidden=True)` also returns empty `mentions: []`. No ping.

---

The code used to do said tests:

```py
import discord
from discord.ext import commands
from discord_slash import SlashCommand, SlashContext

import logging
logging.basicConfig(level=logging.DEBUG)

bot = commands.Bot(command_prefix="!", intents=discord.Intents.default())
slash = SlashCommand(bot, sync_commands=True)

GUILD_ID = 000000000000000000
DISCORD_TOKEN = "token"

@slash.slash(
    name="normal",
    guild_ids=[GUILD_ID],
    )
async def _normal(ctx: SlashContext):
    await ctx.send(ctx.author.mention, allowed_mentions=discord.AllowedMentions(roles=True, users=True, everyone=True))

@slash.slash(
    name="defered",
    guild_ids=[GUILD_ID],
    )
async def _defered(ctx: SlashContext):
    await ctx.defer()
    await ctx.send(ctx.author.mention, allowed_mentions=discord.AllowedMentions(roles=True, users=True, everyone=True))

@slash.slash(
    name="hidden",
    guild_ids=[GUILD_ID],
    )
async def _hidden(ctx: SlashContext):
    await ctx.send(ctx.author.mention, hidden=True, allowed_mentions=discord.AllowedMentions(roles=True, users=True, everyone=True))

@slash.slash(
    name="hiddendefered",
    guild_ids=[GUILD_ID],
    )
async def _hiddendefered(ctx: SlashContext):
    await ctx.defer(hidden=True)
    await ctx.send(ctx.author.mention, allowed_mentions=discord.AllowedMentions(roles=True, users=True, everyone=True))

@slash.slash(
    name="hiddenhidden",
    guild_ids=[GUILD_ID],
    )
async def _hiddenhidden(ctx: SlashContext):
    await ctx.defer(hidden=True)
    await ctx.send(ctx.author.mention, hidden=True, allowed_mentions=discord.AllowedMentions(roles=True, users=True, everyone=True))

bot.run(DISCORD_TOKEN)
```

---

Output of tests in Discord:

![latest](https://user-images.githubusercontent.com/20756843/117588500-fa862880-b123-11eb-96ce-6a9259b79ed5.png)

**Comment by quirky-bluejay** [comment]
This while annoying, is expected behaviour, and it's also on discord's end.
I assume ephemeral messages don't go through the normal mention parsing, because they can only be seen by a single user
And 'sending' after a deferred response actually edits the original response, so this is inline with editing a message to contain a mention.
I suggest making feature requests on the discord repo https://github.com/discord/discord-api-docs
