### ISSUE TITLE
Submodules ImportError

### ISSUE THREAD

**Issue by jasonli0616** [interactions-py/interactions.py#182]
From [documentation for adding permissions](https://discord-py-slash-command.readthedocs.io/en/latest/gettingstarted.html#want-to-restrict-access-setup-permissions), the imports at the top do not work.

Imports with error:
`from discord_slash.utils.manage_commands import create_permission
from discord_slash.model import SlashCommandPermissionType`

Error messages:
`from discord_slash.utils.manage_commands import create_permission
ImportError: cannot import name 'create_permission' from 'discord_slash.utils.manage_commands' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord_slash/utils/manage_commands.py)`

`from discord_slash.model import SlashCommandPermissionType
ImportError: cannot import name 'SlashCommandPermissionType' from 'discord_slash.model' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord_slash/model.py)`

**Comment by jasonli0616** [comment]
`from discord_slash import SlashCommand, SlashContext` is working, and `discord-py-slash-command` has been installed via pip

**Comment by benwoo1110** [comment]
permission related things are not in release yet. Either wait or install this lib directly from master branch. You can do that with `pip install git+https://github.com/eunwoo1104/discord-py-slash-command --force` (assuming you have pip and git install properly on your com)
