### ISSUE TITLE
The cog ones are not working

### ISSUE THREAD

**Issue by Dhruvacube** [interactions-py/interactions.py#186]
https://github.com/eunwoo1104/discord-py-slash-command#advanced

The slash commands arent showing up for the cogs one!

**Comment by quirky-bluejay** [comment]
This is most likely due to global commands taking up to one hour to roll out.
Use guild based commands for testing. Also please read the docs, at least after you find what you think to be a bug.
Please join the discord server for general help.

**Comment by Dhruvacube** [comment]
well tbh I have waited more than a day yet the slash commands didnt showed up!

**Comment by quirky-bluejay** [comment]
Reopening it *for now*, although please ask in the discord server and send you code there too.

**Comment by Dhruvacube** [comment]
okay and I have sent my code there also! Thank you!

**Comment by Dhruvacube** [comment]
Please close the issue ! It has been in support server
