### ISSUE TITLE
Pressing a Button sent by current bot causes exception in on_socket_response

### ISSUE THREAD

**Issue by artem30801** [interactions-py/interactions.py#190]
When your bot sent a message with new discord buttons - upon pressing on button, following exception arises in console (not critical, but annoying and suboptimal):
```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "***\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "***\venv\lib\site-packages\discord_slash\client.py", line 762, in on_socket_response
    if to_use["data"]["name"] in self.commands:
KeyError: 'name'
```

Steps to reproduce:
1) Have your bot send message containing components (buttons) (for example sent  by another python script with discord-components library)
2) Launch your bot with discord-py-slash-command
3) Press on button in the message
4) Exception

Reproducable on example from readme
```py
import discord
from discord.ext import commands
from discord_slash import SlashCommand, SlashContext

bot = commands.Bot(command_prefix="!", intents=discord.Intents.all())
slash = SlashCommand(bot)

@slash.slash(name="test")
async def _test(ctx: SlashContext):
    embed = discord.Embed(title="embed test")
    await ctx.send(content="test", embeds=[embed])

bot.run("token")
```

discord-py-slash-command version: 1.1.2 from pypi

**Comment by i0bs** [comment]
We've received a lot of comments and questions concerning the implementation of buttons with our library right now. The current sentiment is that we are currently talking about plans of how to add the interaction into our library, and waiting for feedback from various other contributors who help add to this project. The maintainer (and respectfully owner) @eunwoo1104 has not been yet online to foresee all of the new changes, and frankly, we don't want to push for something so sudden without further information from him alongside those we firmly trust.

For now I will be keeping this Issue open and request reviews, but until then we will not close or merge without the proper insight on how to add them.
