### ISSUE TITLE
Command fails due to Unknown event INTERACTION_CREATE

### ISSUE THREAD

**Issue by richard-preston** [interactions-py/interactions.py#194]
I'm able to successfully register slash commands, but when I try to use one from my Discord client I get a "This interaction failed" message. I get the following message in the logs: `DEBUG:discord.gateway:Unknown event INTERACTION_CREATE`. Any help on this would be greatly appreciated 😊

**Comment by ghost** [comment]
I guess that it is d.py error, since it is discord.py logs.

**Comment by i0bs** [comment]
Temporarily closing this issue for the time being until v2.0 is released to address. This seems to be a discord.py specific issue and not related to our library.

**Comment by mmattbtw** [comment]
@richard-preston I'm currently getting this error, did you ever solve it?
