### ISSUE TITLE
default_permission doesn't have any effect

### ISSUE THREAD

**Issue by alexisig** [interactions-py/interactions.py#195]
Hi,

Thanks a lot for this project!

I am trying to restrict the use of a command to a specific role using the following options, though it does not seem to have any effect:
```
    "default_permission": False,
    "permissions": {
        GUILD_ID : [ create_permission(ROLE_ID, SlashCommandPermissionType.ROLE, True) ]
    },
```
Other options I've tried that don't work:
- Only setting one "positive" permission to the role
- Setting one "negative" permission to the role `@everyone` and one positive to one role (the negative permission has no effect)
- Setting default_permission=False without anything else also has no effect.

The only way I can disallow a role/user to use it is by explicit adding a negative permission for them, meaning that for admin commands I would need to add a negative permission to all the guild users (because some users don't have roles).

I believe that's not the intended behavior and is a bug right?

**Comment by benwoo1110** [comment]
I use this when I was testing the permission PR, and only user with id 281300452270931969 was able to run the command. From that little code snippet from you, its not enough to pin point any issue with your code tho.

```py
@slash.slash(name="test_guild", description="test_guild", default_permission=False, guild_ids=[750556940127436880, 823454213089787914], options=[create_option("test", "lol", SlashCommandOptionType.INTEGER, True)])
@slash.permission(823454213089787914, generate_permissions(allowed_users=[281300452270931969]))
async def test_guild(ctx, test):
    print(test)
    await ctx.send("test_guild")
```

**Comment by alexisig** [comment]
So I investigated further. It looks like creating a command without adding `default_permission=False` the first time it is created and then adding it later has not effect.

I was able to go around the issue by temporarily renaming the command, adding the option and renaming it back to its original name.

Here is roughly the script I have, to give you more context, though I'm not sure if that helps.

```python
slash = SlashCommand(bot, sync_commands=True, delete_from_unused_guilds=True

slash.add_slash_command(
    name=BASE_COMMAND_NAME,
    cmd=_base_cmd,
    guild_ids=[GUILD_ID],
    options=[],
    default_permission=False,
    permissions={
        GUILD_ID: [
            create_permission(RESTRICTED_COMMANDS_ROLE_ID, SlashCommandPermissionType.ROLE, True)
        ]
    })
    
 slash.add_subcommand(base=BASE_COMMAND_NAME, **{
    "cmd": _some_function,
    "description": "description",
    "guild_ids": [GUILD_ID],
    "connector": {
        "utilisateur": "member"
    },
    "options": [
        {
            'name': 'utilisateur',
            'description': "Utilisateur à qui le message d'accueil sera envoyé",
            'type': SlashCommandOptionType.USER,
            'required': True
        }
    ]
})

```

**Comment by benwoo1110** [comment]
ok yea, I think I found the issue. will link a pr soon.

**Comment by benwoo1110** [comment]
You can test the above PR by installing from by branch `pip install git+https://github.com/benwoo1110/discord-py-slash-command@default-permission-missing --force`
