### ISSUE TITLE
cant install the module itsel error = module not found 

### ISSUE THREAD

**Issue by rochanrk** [interactions-py/interactions.py#201]
Traceback (most recent call last):
  File "C:\Users\rocha\PycharmProjects\pythonProject2\test.py", line 3, in <module>
    from discord_slash import SlashCommand
ModuleNotFoundError: No module named 'discord_slash'

**Comment by LordOfPolls** [comment]
That error means you have not installed the library. 
You want `pip install discord-py-slash-command`

If that still doesn't work, you may be using a venv, check your pycharm settings

**Comment by temp-pk** [comment]
now working in repit.com
![image](https://github.com/interactions-py/interactions.py/assets/147116291/60212c33-595b-4eb4-9897-ebfad5225bd3)

**Comment by AstreaTSS** [comment]
Please don't comment on dead issues like this, and please don't use issues as support.

Regardless, repl.it and similar services are not supported.
