### ISSUE TITLE
Compatibility with discord.py views

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [interactions-py/interactions.py#202]
The latest version of discord.py (not yet on pip) has a new `views` thing that makes components easy. It should be supported

**Comment by LordOfPolls** [comment]
Discord.py 2.0 has views, which adds all interactions. As such we will not support them as they quite literally replace this library

**Comment by SIGSTACKFAULT** [comment]
What's the intended way to get both slash commands and components working together? Unless i'm dumb, the latest discord.py doesn't have support for adding slash commands.

**Comment by LordOfPolls** [comment]
Not in this library yet, the component branch has an in progress implementation for that. 

If you have any further questions please go to the discord, as these arent *issues*
