### ISSUE TITLE
Interaction Failed

### ISSUE THREAD

**Issue by ilyanfraimbault** [interactions-py/interactions.py#205]
Hello, I recently updated my bot to use slash_commands. But i'm still getting this message after executing a command (the command is working well) : 
![image_2021-06-08_144920](https://user-images.githubusercontent.com/35037869/121187777-b4c69800-c868-11eb-8eff-5deb3c2abe84.png)
I have no error in console.
Thats an example of command which is making this issu:
 ```python
@slash.slash(name="Clear", description="Effacer des messages")
@has_permissions(manage_messages=True)
async def clear(ctx, nombre: int):
    author = ctx.author
    channel = ctx.channel
    channel_logs = bot.get_channel(848578058906238996)
    messages = await ctx.channel.history(limit=nombre + 1).flatten()
    for message in messages:
        await message.delete()
    embed = discord.Embed(title=f"Le channel "f"#{channel}" " a été clear !", color=0xe6de00)
    embed.set_thumbnail(url=image_acces)
    embed.add_field(name="Modérateur", value=ctx.author.mention, inline=True)
    await channel_logs.send(embed=embed)
```

**Comment by mccoderpy** [comment]
1. wy are you using delete and not the method [purge](https://discordpy.readthedocs.io/en/latest/api.html?highlight=purge#discord.TextChannel.purge) of discord.TextChannel ?
2. you have to write 
`await ctx.defer()`
under the `async def clear(ctx, nombre: int):`
to tell the discord-API that the command is "arrived"
or just send an response like `await ctx.send(f"{nombre} messages have been deleted ", hidden=True)` (the hidden Parameter makes the message only visible for the command-author)

**Comment by LordOfPolls** [comment]
A slash command must be resolved, or "completed". You need to either use `await ctx.send("some content")` to send a response. A common technique is `await ctx.send("processing", hidden=True)` which would send a message only the author can see saying "processing"

If you use `await ctx.defer()` a loading state will be visible in chat, which will not disappear until the interaction is resolved with `ctx.send`

If you have any further questions, please ask them in the discord.
