### ISSUE TITLE
Need to add channel permission type

### ISSUE THREAD

**Issue by XCanG** [interactions-py/interactions.py#218]
Currently `permission` option and `@slash.permission` accept only User or Role type permissions, but channel-lock commands are also common even if you technically can call it in any channel.

**Comment by LordOfPolls** [comment]
Unfortunately, the permission option is just an abstraction of the discord permission system for interactions. The only options in it are `user` or `role`

https://discord.com/developers/docs/interactions/slash-commands#application-command-permissions-object-application-command-permission-type
