### ISSUE TITLE
TypeError: ban() got an unexpected keyword argument 'user'

### ISSUE THREAD

**Issue by robalyy** [interactions-py/interactions.py#233]
Hi 
My code is: 
`import discord
from discord.ext import commands
from discord_slash import SlashCommand, SlashContext
from discord_slash.utils.manage_commands import create_option, create_choice, create_permission
from discord_slash.model import SlashCommandPermissionType, SlashCommandOptionType

client = commands.Bot(command_prefix="/")
slash = SlashCommand(client, sync_commands=True)
token = "token"

@slash.slash(
    name="ban",
    description="Banowanie osoby z serwera",
    guild_ids=[852608078935359518],
    options=[
        create_option(
            name="user",
            description="Podaj osobe z pingiem którą chcesz zbanowac",
            option_type=SlashCommandOptionType.USER,
            required=True
        ),
        create_option(
            name="reason",
            description="Podaj powod dlaczego on dostał bana",
            option_type=SlashCommandOptionType.STRING,
            required=True
        ),
        create_option(
            name="time",
            description="Podaj na ile chcesz dac tego bana np. tydzień",
            option_type=SlashCommandOptionType.STRING,
            required=False
        )
    ], permissions={
        852608078935359518:[
            create_permission(852608601180471347, SlashCommandPermissionType.ROLE, True),
            create_permission(852608690632261681, SlashCommandPermissionType.ROLE, True),
            create_permission(852609359469084742, SlashCommandPermissionType.ROLE, True),
            create_permission(852609416187740240, SlashCommandPermissionType.ROLE, True),
        ]
    })
async def ban(ctx:SlashContext):
    await ctx.send("tester")

@client.event
async def on_ready():
    print("ready")

client.run(token)`
and My error on invoke command is:
An exception has occurred while executing command `ban`:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\model.py", line 209, in invoke
    return await self.func(*args, **kwargs)
TypeError: ban() got an unexpected keyword argument 'user'

**Comment by benwoo1110** [comment]
See how to properly create option https://discord-py-slash-command.readthedocs.io/en/latest/gettingstarted.html#giving-some-options-for-variety

You need to add then options as parameters of your function.

**Comment by mccoderpy** [comment]
you have to pass the option-names as parameters in the function
```py
  @slash.slash(name="ban", description="Banowanie osoby z serwera", guild_ids=[852608078935359518], options=[create_option(name="user", description="Podaj osobe z pingiem którą chcesz zbanowac", option_type=7,
  required=True), create_option(name="reason", description="Podaj powod dlaczego on dostał bana", option_type=3, required=True), create_option(name="time", description="Podaj na ile chcesz dac tego bana np. tydzień", option_type=3, required=False)
  ], default_permission=False, permissions={852608078935359518: [create_permission(852608601180471347, 1, True), create_permission(852608690632261681, 1, True), create_permission(852609359469084742, 1, True), create_permission(852609416187740240, 1, True)]})
  async def ban(ctx: SlashContext, user: discord.Member, reason: str, time: str = None):
      await ctx.send("tester")
```

**Comment by robalyy** [comment]
> you have to pass the option-names as parameters in the function
> 
> ```python
>   @slash.slash(name="ban", description="Banowanie osoby z serwera", guild_ids=[852608078935359518], options=[create_option(name="user", description="Podaj osobe z pingiem którą chcesz zbanowac", option_type=7,
>   required=True), create_option(name="reason", description="Podaj powod dlaczego on dostał bana", option_type=3, required=True), create_option(name="time", description="Podaj na ile chcesz dac tego bana np. tydzień", option_type=3, required=False)
>   ], default_permission=False, permissions={852608078935359518: [create_permission(852608601180471347, 1, True), create_permission(852608690632261681, 1, True), create_permission(852609359469084742, 1, True), create_permission(852609416187740240, 1, True)]})
>   async def ban(ctx: SlashContext, user: discord.Member, reason: str, time: str = None):
>       await ctx.send("tester")
> ```

Thanks you!

**Comment by mccoderpy** [comment]
> > you have to pass the option-names as parameters in the function
> > ```python
> >   @slash.slash(name="ban", description="Banowanie osoby z serwera", guild_ids=[852608078935359518], options=[create_option(name="user", description="Podaj osobe z pingiem którą chcesz zbanowac", option_type=7,
> >   required=True), create_option(name="reason", description="Podaj powod dlaczego on dostał bana", option_type=3, required=True), create_option(name="time", description="Podaj na ile chcesz dac tego bana np. tydzień", option_type=3, required=False)
> >   ], default_permission=False, permissions={852608078935359518: [create_permission(852608601180471347, 1, True), create_permission(852608690632261681, 1, True), create_permission(852609359469084742, 1, True), create_permission(852609416187740240, 1, True)]})
> >   async def ban(ctx: SlashContext, user: discord.Member, reason: str, time: str = None):
> >       await ctx.send("tester")
> > ```
> 
> Thanks you!

you're welcome 😀
