### ISSUE TITLE
Incorrect TypeError Message

### ISSUE THREAD

**Issue by BritishBenji** [interactions-py/interactions.py#235]
Steps to recreate:
- Create a listener in a Cog for a button press/component interaction
- Give less Arguments than required
For example:
```python
@commands.Cog.listener()
    async def on_component():
        print("Fuck Yeah")
```
- Interact with a component (i.e. Button Press)
- Receive error message:
`TypeError: on_component() takes 0 positional argument but 2 were given`

**Comment by LordOfPolls** [comment]
Thats not a bug with the library. you need to have to parameters in your `on_component` method

`self` - a reference to your class
`ctx` - a reference to the context of the interaction
