### ISSUE TITLE
Doubled cog commands

### ISSUE THREAD

**Issue by Flowseal** [interactions-py/interactions.py#236]
I made music cog, but slash commands are doubled in that cog.
![image](https://user-images.githubusercontent.com/50780822/123798240-a9a6db00-d8ef-11eb-9939-8b85dd1c18e2.png)
![image](https://user-images.githubusercontent.com/50780822/123798280-b297ac80-d8ef-11eb-85eb-e38a8aaa7bde.png)
(And other music commands..)

Before run:
`client.load_extension('cogs.music')`

In music.py:
`def setup(client: commands.Bot):
    client.add_cog(Music(client))`
    
And cog slash command example:
![image](https://user-images.githubusercontent.com/50780822/123798581-fab6cf00-d8ef-11eb-84e5-61fd2934c68b.png)

**Comment by LordOfPolls** [comment]
This is almost certainly because one is a guild command, one is global. add this to your slash innit `delete_from_unused_guilds=True`

https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.client.html#discord_slash.client.SlashCommand
