### ISSUE TITLE
Can we have client side messaging support?

### ISSUE THREAD

**Issue by Waspyeh** [interactions-py/interactions.py#25]
Is it possible that we can get client side messaging support?

Example: https://drago.is-inside.me/o8o2msMd.png

**Comment by hpenney2** [comment]
That's already available, use the `hidden` argument in `SlashContext.send`.

Example:
```python
@slash.slash(name="mycommand")
async def _mycommand(ctx: SlashContext):
    await ctx.send(3, content="Only you can see this message.", hidden=True)
```

There is also the `complete_hidden` argument which will automatically override `hidden` to True and `send_type` to 3 (according to the Discord API docs, type 3 will "respond with a message, eating the user's input").

**Comment by Waspyeh** [comment]
Oh cool thanks.

**Comment by Waspyeh** [comment]
> That's already available, use the `hidden` argument in `SlashContext.send`.
> 
> Example:
> 
> ```python
> @slash.slash(name="mycommand")
> async def _mycommand(ctx: SlashContext):
>     await ctx.send(3, content="Only you can see this message.", hidden=True)
> ```
> 
> There is also the `complete_hidden` argument which will automatically override `hidden` to True and `send_type` to 3 (according to the Discord API docs, type 3 will "respond with a message, eating the user's input").

So is there also a way to remove the x used x with x

**Comment by hpenney2** [comment]
That's what `send_type` (the first argument to `SlashContext.send`) 3 is for, as I noted in the last sentence of my comment.
> (according to the Discord API docs, type 3 will "respond with a message, eating the user's input")

Refer to the [Discord's documentation on `InteractionResponseType`](https://discord.com/developers/docs/interactions/slash-commands#interaction-interactionresponsetype) for other numbers you can enter into `send_type`. (You'll usually only use 3 and 4.)
