### ISSUE TITLE
discord_slash.context.InteractionContext returning empty args

### ISSUE THREAD

**Issue by solumath** [interactions-py/interactions.py#257]
On version 1.2.2 args return values. On version 2.0.0 and 2.3.1 it returns empty list. Seems like missing implementation.
* Tested on versions 1.2.2., 2.0.0, 2.3.1 
* python 3.9.5

**Comment by LordOfPolls** [comment]
Good catch

I'll add them in the next release
Specifically, I'll add the variable back, not positional args support
