### ISSUE TITLE
Need Help Pls

### ISSUE THREAD

**Issue by 45i** [interactions-py/interactions.py#265]
Hi!
What do i use to catch this exception:
![image](https://user-images.githubusercontent.com/86361659/126589920-e34e8611-8f2c-4a4d-9472-a2cf3ab0b99e.png)

**Comment by JUGADOR123** [comment]
for problems like that its better to go to the discord, also there are quite a lot of reasons why your are getting interaction filed.

**Comment by 45i** [comment]
no i mean i want to know what should i use after ```except``` to catch the exception?

**Comment by Toricane** [comment]
> no i mean i want to know what should i use after `except` to catch the exception?

Use the `on_slash_command_error`, similar to Discord.py's `on_command_error`. More info in the [docs](https://discord-py-slash-command.readthedocs.io/en/latest/events.html#on_slash_command_error). Or maybe you are not sending a message within 3 seconds. In the future, please ask in the Discord server.

**Comment by 45i** [comment]
ohk
and uhh I fixed it
the error was an UnicodeEncodeError
Thanks for all your help
greatly appreciated:)
