### ISSUE TITLE
Add support for bot.get_user/bot.fetch_user converters

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#280]
The USER type for slash commands supports passing in ID's of users that do not share a guild with you.

However, if you pass in an ID of such a user, the library will end up returning just the integer ID of the user, instead of a discord.User object.

For me, this means I have to manually typecheck every moderation command I have that uses user options and run get_user manually. It also means if you don't and you're just running off the assumption that the slash command will always return a User object, these commands will break.

Would it be better to fallback automatically to getting a user object if fetch_member fails? This seems more desirable than just returning an integer.

If commands strictly need members to be in the guild, then you can typecheck and see if it's a Member object that way.

Alternatively, maybe SlashCommandOptionType.USER could be changed to use the User converter, and a new SlashCommandOptionType.MEMBER type could be added that uses the Member converter?

**Comment by LordOfPolls** [comment]
We discussed this a short while ago. We decided it was best for this library **not** to make any more API calls than necessary when dispatching an interaction.

It's very possible for an API call to take a second to resolve completely, which is an additional second of time before the interaction Is in your bot. As I'm sure you're aware, interactions must be responded to within 3 seconds. Under poor network conditions, heavy bot load, or poor hardware, its very easy to have failed interactions in this case. 

As such we decided it was best for the user to have responsibility of handling type conversion
