### ISSUE TITLE
[Feature request] Context menus are released

### ISSUE THREAD

**Issue by yannic-md** [interactions-py/interactions.py#284]
Quote from discord developer discord:

_Context menus
We've just rolled out support for context menu commands on desktop clients!

You can register context menu actions on users and messages.  These commands are visible when you right click on a user/message or click the three dots next to a message.

Head over to #context-menus to mingle with other context menu aficionados.  We're excited to see what you build :grin: 

Docs for user commands: https://discord.com/developers/docs/interactions/application-commands#user-commands
Docs for message commands: https://discord.com/developers/docs/interactions/application-commands#message-commands_

**Comment by i0bs** [comment]
Already working on integrating.

**Comment by yannic-md** [comment]
Glad to hear!

**Comment by i0bs** [comment]
Implemented as of release 3.0.0.
