### ISSUE TITLE
add_slash_command not work? Or script that I stole not working... bruh

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#29]
I use script that provided in #9 and doesnt seem to working... Prints all, no error, runs, but discord doesnt show this...
![image](https://user-images.githubusercontent.com/51151590/102690673-9d074300-4239-11eb-8079-c52b87307851.png)
![image](https://user-images.githubusercontent.com/51151590/102690679-b01a1300-4239-11eb-8bdc-2625c6f9a8fb.png)

**Comment by eunwoo1104** [comment]
Is your bot added to the guild with `applications.commands` OAuth2 Scope? Or is the command global command?

**Comment by hpenney2** [comment]
As an additional question, do you ever call the `add_to_api` function?

**Comment by ghost** [comment]
> As an additional question, do you ever call the `add_to_api` function?

yes

> Is your bot added to the guild with `applications.commands` OAuth2 Scope? Or is the command global command?

OHHH maybe not. i change bot`s guild, but not add with commands. srr ill try

**Comment by ghost** [comment]
cyka blyat! I added with applications.commands, command in only for one server, but it again not show command!

**Comment by eunwoo1104** [comment]
Try manually registering commands.
Read this: https://discord.com/developers/docs/interactions/slash-commands#registering-a-command
Also, this extension comes with utility function that helps you register the command.
Read the docs: https://discord-py-slash-command.readthedocs.io/en/latest/discord_slash.utils.manage_commands.html
