### ISSUE TITLE
Error when responding to a button after upgrade to version 3.0.0

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#290]
I followed the instructions on https://discord-py-slash-command.readthedocs.io/en/components/components.html to create a button, using the wait_for method. When I clicked the button in discord, my bot didn't respont, but this error appeared.
![grafik](https://user-images.githubusercontent.com/88881326/129333911-490dff9e-6710-40a8-94dc-b95697fa3869.png)

With version 2.4.2 it works without problems.

**Comment by Toricane** [comment]
Yeah same, I've also pointed it out in the Discord, waiting for fl0w's response

**Comment by i0bs** [comment]
Discord made a big brain move by changing how the interaction types work for processing application commands separate to components, so the logic for this class method also changed in the client. I was able to get components to work fine with menus but I did not test from a slash command. I'll be looking into it.

**Comment by sillyElv** [comment]
Thanks

**Comment by i0bs** [comment]
Fixed in #293.
