### ISSUE TITLE
The quickstart page linked in getting started opens a 404 page

### ISSUE THREAD

**Issue by chweesee** [interactions-py/interactions.py#292]
go to https://github.com/discord-py-interactions/discord-py-interactions/blob/master/docs/gettingstarted.rst
click on "quickstart"
observe how you're redirected to quickstart.html instead of quickstart.rst

**Comment by i0bs** [comment]
That's intentionally set to HTML. I also can't get the 404 error.

**Comment by chweesee** [comment]
well 
![image](https://user-images.githubusercontent.com/81509124/129378242-c57d47bd-3b69-453a-9221-8d6e3b3f0f69.png)

**Comment by FayeDel** [comment]
You get that error if you navigate from the .rst file directly.
Instead, navigate it through the [docs ](https://discord-py-slash-command.readthedocs.io/en/latest/index.html)instead. In there, that `quickstart.html` points to https://discord-py-slash-command.readthedocs.io/en/latest/quickstart.html

**Comment by chweesee** [comment]
ah ok thanks i guess then, so i assume it indeed is supposed to redirect you to .html if you navigate from the .rst file directly right?

**Comment by chweesee** [comment]
> That's intentionally set to HTML. I also can't get the 404 error.

also a bit confused as to why you're unable to get the 404 error

**Comment by FayeDel** [comment]
If you navigate from the .rst file directly without using the site, and click on the same link, you get that error that you showed.
This is moreso because of file navigation; the screenshot shows 404 because the github repo doesn't produce .HTML files (hence the error), the doc site does it for you (and hence, pointed properly)

**Comment by chweesee** [comment]
Thanks, that makes much more sense now. I assume that the repo's files itself are being used on the website which is why changing the redirection to .rst wouldn't make sense since the website can display html and probably not rst or something right?

**Comment by i0bs** [comment]
Yep

**Comment by chweesee** [comment]
Thanks then, seems like i mistook intended behavior for an issue, closing this
