### ISSUE TITLE
Just not working, or im dumbass

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#3]
Command not showing in discord
![image](https://user-images.githubusercontent.com/51151590/102359930-faa25200-3fe3-11eb-9ac6-ffa33a898f6e.png)

**Comment by eunwoo1104** [comment]
You need to add command to Discord API. Check Discord API Document.
https://discord.com/developers/docs/interactions/slash-commands#registering-a-command

**Comment by eunwoo1104** [comment]
Also change your bot token now. - Edited the issue since there was bot token.
