### ISSUE TITLE
Weird issue.

### ISSUE THREAD

**Issue by thomaskeig** [interactions-py/interactions.py#30]
Why am I getting this issue?
```
Traceback (most recent call last):
  File "C:\Users\Thomas Keig\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Thomas Keig\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord_slash\client.py", line 344, in on_socket_response
    await selected_cmd["func"](ctx, *args)
  File "G:/My Drive/Home/Python Projects/Personal/iFBR Bot/Discord Bot/v2.0/bot (only slash cmds).py", line 547, in export
    await ctx.send(embeds=[embed2])
  File "C:\Users\Thomas Keig\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord_slash\model.py", line 111, in send
    resp = await self._http.post(base, self._discord.user.id, self.interaction_id, self.__token, initial)
  File "C:\Users\Thomas Keig\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord_slash\http.py", line 34, in post
    raise RequestFailure(resp.status, await resp.text())
discord_slash.error.RequestFailure: Request failed with resp: 404 | {"message": "Unknown interaction", "code": 10062}
```

**Comment by eunwoo1104** [comment]
Hmm... Cannot reproduce that error.

**Comment by ghost** [comment]
Can u show code?

**Comment by Lifeismana** [comment]
I'm also getting this error and it seems like it's when the slash command has not been used for a long time

**Comment by eunwoo1104** [comment]
Then it might occur because 15 mins after getting slash command invoke, the interaction token expires. In that case, try not to delay sending a response for 15 mins or use `await ctx.channel.send()`, which is just same as discord.py's `TextChannel.send`.

**Comment by Lifeismana** [comment]
you miss understood what i meant
i'm using await ctx.channel.send(), but like i've not used a slash command for 21h, it failed twice with that error
```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/data/venv/lib/python3.8/site-packages/discord_slash/client.py", line 349, in on_socket_response
    await selected_cmd["func"](ctx, *args)
  File "/data/devcogs/mycogs/mycog.py", line 180, in lenny
    await ctx.send(send_type=3,content=await self.__get_lenny())
  File "/data/venv/lib/python3.8/site-packages/discord_slash/model.py", line 111, in send
    resp = await self._http.post(base, self._discord.user.id, self.interaction_id, self.__token, initial)
  File "/data/venv/lib/python3.8/site-packages/discord_slash/http.py", line 34, in post
    raise RequestFailure(resp.status, await resp.text())
discord_slash.error.RequestFailure: Request failed with resp: 404 | {"message": "Unknown interaction", "code": 10062}

```
 before working again
check my code there https://github.com/Lifeismana/randomcogs/tree/master/lennyslash

**Comment by eunwoo1104** [comment]
Hmm, I'll try to reproduce this error later.

**Comment by Lifeismana** [comment]
I just had this error again after not using it for 40 minutes, 15:52 → 16:31, makes me think something is configured incorrectly on my side but i have no idea what it could be, (the command is a global one)

**Comment by echan00** [comment]
I'm also having this error

```
  File "/Users/xxx/Workspace/discord-bot/slash_cmds/l00t.py", line 45, in handle
    await context.send(content=msg, hidden=True)
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/discord_slash/model.py", line 124, in send
    resp = await self._http.post(base, self._discord.user.id, self.interaction_id, self.__token, initial)
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/discord_slash/http.py", line 34, in post
    raise RequestFailure(resp.status, await resp.text())
discord_slash.error.RequestFailure: Request failed with resp: 404 | {"message": "Unknown interaction", "code": 10062}
```

My msg is being sent but seeing this error nevertheless, happy to help debug if anyone needs any info

**Comment by spinnerich** [comment]
> I'm also having this error
> 
> ```
>   File "/Users/xxx/Workspace/discord-bot/slash_cmds/l00t.py", line 45, in handle
>     await context.send(content=msg, hidden=True)
>   File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/discord_slash/model.py", line 124, in send
>     resp = await self._http.post(base, self._discord.user.id, self.interaction_id, self.__token, initial)
>   File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/discord_slash/http.py", line 34, in post
>     raise RequestFailure(resp.status, await resp.text())
> discord_slash.error.RequestFailure: Request failed with resp: 404 | {"message": "Unknown interaction", "code": 10062}
> ```
> 
> My msg is being sent but seeing this error nevertheless, happy to help debug if anyone needs any info

Code?

**Comment by echan00** [comment]
FYI I saw that http.py was refactored and updated to v1.0.8, the issue seems to be resolved now. 

Happy to share code, but I don't think that was the issue.

**Comment by eunwoo1104** [comment]
> FYI I saw that http.py was refactored and updated to v1.0.8, the issue seems to be resolved now. 
> 
> Happy to share code, but I don't think that was the issue. 
> 
> 

Well, I haven't tested this issue with the refactored one. Not sure whether this is fixed, so this will still be remained open.

**Comment by echan00** [comment]
Okay, it seems like the problem wasn't resolved in the new version (1.0.8.1) But I was able to replicate the issue. 

I have a process that takes a bit longer to process (render an SVG image). I am consistently getting the 'unknown interaction' error with the code below. 

```
            file1, embed = render(client, guild, session)     # render SVG image
            await context.channel.send(file=file1, embed=embed)

            await context.send(content="Test Message")
```


But if I comment out the slow (render/embed sending) code, the problem no longer becomes an issue

```
            #comment out - file1, embed = render(client, guild, session)     # render SVG image
            #comment out - await context.channel.send(file=file1, embed=embed)

            await context.send(content="Test Message")
```

**Comment by eunwoo1104** [comment]
@echan00 
Oh, then just in case that the process doesn't take more than 15 mins, maybe this occur because we send initial response too late?
This can be proved by first send any response (`.send(5)`) then do long process, finally send another response.

**Comment by eunwoo1104** [comment]
Hold on, found this at official docs:
> Interaction `tokens` are valid for **15 minutes** and can be used to send followup messages but you **must send an initial response within 3 seconds of receiving the event.** If the 3 second deadline is exceeded, the token will be invalidated.

This was the reason.

**Comment by echan00** [comment]
Perhaps this library could include the ack response mentioned below? 

<img width="894" alt="Screen Shot 2021-01-15 at 1 46 59 PM" src="https://user-images.githubusercontent.com/6287299/104782047-70f7b880-5738-11eb-9d85-184bd52b2770.png">


https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionresponsetype

**Comment by M0RGaming** [comment]
> Perhaps this library could include the ack response mentioned below?
> 
> [Image here]
> 
> https://discord.com/developers/docs/interactions/slash-commands#interaction-response-interactionresponsetype



Before sending your message with your image, you can send off a quick ack response so the API doesn't invalidate your token. You can do this via a simple
```python
await ctx.send(send_type=2) # Send type 2 is a ack response
```

**Comment by echan00** [comment]
I have some simple responses that only requires a database query. Sometimes even those don't respond quickly enough.

I was thinking we could build the ack response into the library but this works too

**Comment by eunwoo1104** [comment]
> I have some simple responses that only requires a database query. Sometimes even those don't respond quickly enough.
> 
> I was thinking we could build the ack response into the library but this works too

Its actually implemeted on master branch.

**Comment by Nezernite** [comment]
```
Detected discord.Client! It is highly recommended to use `commands.Bot`. Do not add any `on_socket_response` event.
run
```
In a few seconds
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at C:\Users\Gode\Documents\GitHub\Bot\venv\lib\site-packages\discord_slash\client.py:294> exception=Forbidden('403 Forbidden (error code: 50001): Missing Access')>
Traceback (most recent call last):
  File "C:\Users\Gode\Documents\GitHub\Bot\venv\lib\site-packages\discord_slash\client.py", line 312, in sync_all_commands
    existing_cmds = await self.req.get_all_commands(guild_id = scope)
  File "C:\Users\Gode\Documents\GitHub\Bot\venv\lib\site-packages\discord\http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```
please help me.
code:
```
import discord
from discord_slash import SlashCommand
from config2 import token

client = discord.Client(intents=discord.Intents.all())
slash = SlashCommand(client, sync_commands=True)

guild_ids = [767088657986617385]


class MyClient(discord.Client):
    @client.event
    async def on_ready():
        print("run")

    @slash.slash(name="ping", guild_ids=guild_ids)
    async def _ping(ctx): # Defines a new "context" (ctx) command called "ping."
        await ctx.send(f"Pong! ({client.latency*1000}ms)")



client.run(token)
```

**Comment by LordOfPolls** [comment]
Locked to prevent irrelevant conversation as this has been resolved
