### ISSUE TITLE
KeyError: 'name', 'name' not in to_use["data"]

### ISSUE THREAD

**Issue by hieunguyen1053** [interactions-py/interactions.py#304]
When I press the Button in Discord, it gets this error.

![Screen Shot 2021-08-17 at 6 08 01 PM](https://user-images.githubusercontent.com/41591244/129715838-6c33a1ad-535d-4509-89a2-0a2100f93869.png)

It only has 2 keys: 'custom_id' and 'component_type', so it fails when running `self._on_slash(to_use)` method
![Screen Shot 2021-08-17 at 6 11 14 PM](https://user-images.githubusercontent.com/41591244/129716175-3e245638-ff69-4861-8bbe-93e0664094c4.png)

**Comment by FayeDel** [comment]
Update your version of the library to 3.0.1/3.0.1a.
