### ISSUE TITLE
[BUG] Permissions on subcommands are not deduplicated when sent to discord

### ISSUE THREAD

**Issue by snazzyfox** [interactions-py/interactions.py#305]
Discord has a limit of 10 permissions per command when using the [batch permission overwrite API](https://discord.com/developers/docs/interactions/application-commands#batch-edit-application-command-permissions). 

When there are many subcommands with the same permissions, e.g.

```py
permissions = [
  create_permission(role_1, 1, True), 
  create_permission(role_2, 1, True), 
  create_permission(role_3, 1, True), 
  ...
]

@subcommand(
  base='base', name='sub1', base_permissions=permissions, ...
)
async def sub1(...):
  ...

@subcommand(
  base='base', name='sub2', base_permissions=permissions, ...
)
async def sub2(...):
  ...
```

This pacakge concatenates all the base_permissions together for the same base command without de-duplicating them. This results in API call to look something like:

```
{ 
    command_id: 123,
    guild_id: 123, 
    permissions: [
        {id: role_1, type: 1, permission: true}, # repeated once for each use of base_command
        {id: role_1, type: 1, permission: true}, 
        {id: role_1, type: 1, permission: true}, 
}
```

This means whenever (the number of permissions on the base command) * (the number of subcommands) exceed 10 the list will contain more than 10 entries and rejected by discord even though in reality only 2-3 entries are needed.

**Comment by benwoo1110** [comment]
Simple solution, just set permissions on one of the sub commands. Bcu ultimate there is no per subcommand permissions. It will all accumulate for the entire base command.

**Comment by snazzyfox** [comment]
True, I guess a workaround is available, but I think it's quite hacky and inconsistent with other base command parameters like `guild_id` and `base_default_permissions`, for which only the last value specified takes effect (and when omitted, the default value overrides any previous user-specified values)

For example,
```
@subcommand(base='base', base_default_permissions=False, ...) 
# ...later
@subcommand(base=base', ...) # no base_default_permissions
```
Results in the entire base command having default permission set to True. 

```
@subcommand(base='base', guild_id=[123] ...)
# ...later
@subcommand(base=base', ...) # no guild_id
```
Results in the base command being registered as a global command because the earlier setting is overwritten with None

Since the value of these settings depend on the import order, this makes larger projects hard to manage when code is split into multiple files. The `base_permissions` field behaves differently and is instead a union of all of the values, not the last.

The easiest way to make them consistent is probably to just make `base_permissions` also takes the last value given like other fields instead of merging them. The current behavior essentially means if parameters for subcommands are inconsistent, they're silently combined into undesired behavior anyways. 

It's of course better to perform some checks to ensure omitted and inconsistent settings between subcommands are properly handled, but that's a larger endeavour. Regardless of how you'd prefer to handle this, I think it would make sense to call out these caveats in the documentation too.

**Comment by benwoo1110** [comment]
Yea tbh guild_id should be merged too imo. The fact that you assign base properties at sub command is bad design to begin with, but wasn't my decision and it probably won't change. I think the merge behaviour will be kept, just add a loop to remove duplicates and improve documentation. PRs are welcomed.

**Comment by i0bs** [comment]
Will be changing with new subclass inheritance in v4 as optionals.
