### ISSUE TITLE
Trying to create a ctx menu with ContextMenuType as CHAT_INPUT returns a 400 error

### ISSUE THREAD

**Issue by chweesee** [interactions-py/interactions.py#310]
Try to create a ctx menu having contextmenutype as chat_input, somewhat like
```py
from discord_slash.context import MenuContext
from discord_slash.model import ContextMenuType
from discord_slash import SlashCommand
import discord
from discord.ext import commands

bot=commands.Bot(command_prefix='$')
slash=SlashCommand(bot,sync_commands=True)

guild_ids = [<guild-id>]

@slash.context_menu(target=ContextMenuType.CHAT_INPUT, name="Give me Mod", guild_ids=guild_ids)
async def ctxtest(ctx: MenuContext):
    await ctx.send("banned",hidden=True)

bot.run('TOKEN')
```
observe how you get an error 400
now try to run the same thing with the type as user/message

**Comment by Catalyst4222** [comment]
A) ContextMenuType.CHAT\_INPUT is the same as a normal slash command, so use `@slash.slash` instead
B) The name for normal slash commands has to be `^[\w-]{1,32}$`, or lowercase with - and \_

**Comment by chweesee** [comment]
That returns a typeerror, ` @slash.slash(target=ContextMenuType.CHAT_INPUT, name="test", guild_ids=guild_ids)
TypeError: slash() got an unexpected keyword argument 'target`
which it should since slash() iirc doesnt have target as an argument

**Comment by Catalyst4222** [comment]
Yes, because it's done automatically. There's a separate decorator for slash commands because different information needs to be sent

**Comment by chweesee** [comment]
Yes, but then what is the use of having chat_input as a type in the first place?

**Comment by Catalyst4222** [comment]
Compatibility or something similar. It still shouldn't be used though

**Comment by chweesee** [comment]
Thanks , was a bit confusing when its the first type in their docs but theres technically no way to use it i guess

**Comment by i0bs** [comment]
Chat Input *is* used, it's used for checking the types of slash commands internally when the invocation process occurs. You should not be using them for context menus anyhow, the reason being that it will regardless output an error because the current design we have for the context menu decorators and methods do not allow a `description` kwarg since menus don't have it.
