### ISSUE TITLE
Slash command not showing up in slash menu

### ISSUE THREAD

**Issue by SoulFire2879** [interactions-py/interactions.py#316]
`@slash.slash(name="test")
async def test(ctx: SlashContext):
    embed = discord.Embed(title="Embed Test", description = 'UUUUUUUUUU', color = discord.Color.blurple())
    await ctx.send(embed=embed)`

this is the code from the example 
![image](https://user-images.githubusercontent.com/77575770/131087402-feedb7ca-683e-4d7f-9826-a30890b0d388.png)

it doesnt show up

**Comment by Catalyst4222** [comment]
1. Have you waited the hour delay for global commands?
2. Did you invite the bot with the applications.commands scope? This is different from bot permissions 
3. Did you add `sync_commands=True` to `SlashCommand` or sync in another way?
If you don't know what most of those are, I'd recommend reading through the quickstart of the docs

**Comment by Toricane** [comment]
In the future, please use the #support channel in the Discord for faster replies with help on how to implement this library
