### ISSUE TITLE
[BUG] `client.get_user` returns `None` in the context menus

### ISSUE THREAD

**Issue by InstFurry** [interactions-py/interactions.py#320]
**Describe the bug**
`client.get_user` returns `None` in the context menus, but works fine in the common discord.py commands

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Create a client variable for the library.
3. Create a context menu with `target=ContextMenuType.USER`. Trying to get target user via client.get_user(). Trying to get his mention string
```py
@slash.context_menu(target=ContextMenuType.USER,
                    name="hug",
                    guild_ids=guild_ids)
async def commandname(ctx: MenuContext):
    to_hug = client.get_user(id=ctx.target_id)
    await ctx.send(content=f"{ctx.author.mention} hugs {to_hug.mention}")
```
4. See the traceback error given in the terminal or logger file.

**What's normally expected**
`client.get_user()` returns an User object

**What actually happened**
Instead, I received this traceback error given from my IDLE terminal:

```
An exception has occurred while executing command `hug`:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\client.py", line 1352, in invoke_command
    await func.invoke(ctx, **args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\discord_slash\model.py", line 210, in invoke
    return await self.func(*args, **kwargs)
  File "C:\Users\Admin\Desktop\Just a папка 2.0\testbotslashcmds\slashbot2.py", line 81, in commandname
    content=f"{ctx.author.mention} hugs {to_hug.mention}",
AttributeError: 'NoneType' object has no attribute 'mention'
```

and it makes to use `client.fetch_user()` instead

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [x] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

P.S.: I am new in creating issues, so I'm sorry if I did something wrong

**Comment by Toricane** [comment]
I think `ctx.target_id` is always `None` for some reason, try `ctx.target_author.id`

**Comment by Toricane** [comment]
Also, some features of this lib version 3 and below may not work with discord.py 2.0, but try doing what I said above

**Comment by InstFurry** [comment]
> I think `ctx.target_id` is always `None` for some reason, try `ctx.target_author.id`

Yes, it works xd. Thank you!
