### ISSUE TITLE
[BUG] Unknown Webhook 10015 error when doing `ctx.send()`

### ISSUE THREAD

**Issue by xkevio** [interactions-py/interactions.py#321]
**Describe the bug**
Anytime a slash command is used and I make the bot reply with a simple `await ctx.send(...)`,
the bot sends the message correctly and then raises `discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook`. Any further instructions are then not executed.

**Reproducing steps**
Just copy & pasting the quick start `ping` example and running the bot.

```python
from discord import Intents
from discord.ext.commands.bot import Bot
from discord_slash import SlashCommand, SlashContext

client = Bot(intents=Intents.all(), command_prefix="/")
slash = SlashCommand(client, sync_commands=True)

guild_ids = [...] # omitted

@client.event
async def on_ready():
    print("Ready")

@slash.slash(name="ping", guild_ids=guild_ids)
async def ping(ctx: SlashContext):
    await ctx.send(f"Dunny! ({client.latency*1000}ms)")

client.run(token) # omitted
```

**The full traceback**
```python
An exception has occurred while executing command `ping`:
Traceback (most recent call last):
  File "C:\Users\xkevi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_slash\client.py", line 1352, in invoke_command
    await func.invoke(ctx, **args)
  File "C:\Users\xkevi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_slash\model.py", line 210, in invoke
    return await self.func(*args, **kwargs)
  File "c:\Users\xkevi\Documents\dunnymarkovbot\slash_main.py", line 66, in ping
    await ctx.send(f"Dunny! ({client.latency*1000}ms)")
  File "C:\Users\xkevi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord_slash\context.py", line 258, in send
    resp = await self._http.edit({}, self._token)
  File "C:\Users\xkevi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\http.py", line 250, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook
```

This happens both on my windows pc in the integrated VS Code terminal and on a simple
debian VPS in a bash terminal. So I wonder if it's a setting related to my bot that I have to change in the
Developer Portal.

**Versions**
- [x] Python 3.9.6
- [x] I am using discord.py version 1.7.3
- [x] I am using discord-py-interactions version 3.0.2

**Comment by i0bs** [comment]
I am unable to replicate this issue at all but this seems to be based on Discord's end, I have some feelings that they changed some logic under their hood to reflect interaction responses, or we have an extremely rare bug for us.

Can you try re-installing your pip? `pip uninstall discord-py-interactions` and `pip install -U discord-py-interactions==3.0.2` if you can in sequential order and tell us if you are still able to replicate the issue.

**Comment by xkevio** [comment]
Yeah, I felt a bit silly writing the reproduction steps as no one I had talked to previously had that error but those were the exact steps I took.

Re-installing or updating pip and `discord-py-interactions` didn't change anything either.

**Comment by i0bs** [comment]
Could you perhaps try this on a new bot application? Just for testing purposes you can create a new bot and invite it with the `applications.commands` scope as needed and see if that changes anything at all.

**Comment by xkevio** [comment]
Interesting, so yeah it works fine without errors when I do it with a new bot application. So something must be off with my actual bot application which is a bit older though I wouldn't know what to look for.

**Comment by i0bs** [comment]
Did you invite the bot correctly on your original bot with the scope mentioned? Could be that.

**Comment by xkevio** [comment]
Yes, I re-invited my original bot with the correct scopes several times while working on this bug. I use both the `bot` and `applications.commands` scope, I also tried only using `applications.commands` but that also didn't work.

**Comment by i0bs** [comment]
Because you were able to get this working with another bot, my recommendation would be checking the settings of your original bot in the Discord Developers portal, since this is no longer classified as a bug with our library.
