### ISSUE TITLE
[REQUEST] More explicit error when specifying component instead of list of components

### ISSUE THREAD

**Issue by O4h** [interactions-py/interactions.py#322]
**What is the feature you're proposing?**
I propose a more explicit error when specifying a single component instead of a list of components with `.send`. 

Currently, the error given is `AttributeError: 'str' object has no attribute 'get'`, which doesn't give much information about what is wrong, and an error telling that a list was expected would be quite helpful

**Comment by i0bs** [comment]
This is actually something we already have implemented in v4 and will come up respectively when it's released.

**Comment by O4h** [comment]
Nice, great to hear! I am closing this issue then ^^
