### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by Mapegz** [interactions-py/interactions.py#325]
[removed]

**Comment by i0bs** [comment]
`latest` is `stable`. the link you've [mentioned here](https://slash-command.readthedocs.io) is also incorrect.

**Comment by Mapegz** [comment]
Corrected a typo in the link (removed the accidental s after slash-command)

Added the title I was too dumb not to put before

**Comment by Mapegz** [comment]
> `latest` is `stable`. the link you've [mentioned here](https://slash-command.readthedocs.io) is also incorrect.

My bad, really sorry.
But this page dosen't have the entire documentation right? Because for the past 3 days I have to manually shift over to stable whenever I open the page.... 


https://discord-py-slash-command.readthedocs.io/en/latest
