### ISSUE TITLE
[REQUEST] When the slash command is changed, the guild is not updated.

### ISSUE THREAD

**Issue by DevHypers** [interactions-py/interactions.py#326]
**What is the feature you're proposing?**
If you run the command after changing the value of the slash command, it will not be updated unless you have been kicked out of the guild and invited again.
Is there an update method or a workaround? If not, please implement it, thank you

**Comment by i0bs** [comment]
Are you using the `sync_commands` keyword-argument when you're instantiating the slash command handler?

**Comment by i0bs** [comment]
Upon closer look, you've basically used a GitHub issue as a support ticket. Please consider joining our support server if you're seeking for help on our library.
