### ISSUE TITLE
NotFound 404 Error

### ISSUE THREAD

**Issue by SnowBerryZ** [interactions-py/interactions.py#339]
I use the Discord.py 1.7.3 & Discord-Py-Interactions 3.0.2 for the Slash Command Feature...

Now when the Bot is started and the first Command is used, so the Log give a NotFound 404 - Interaction Error.. ?! After that no more..

This Error repeats itself after reboot the Bot.

**Comment by Catalyst4222** [comment]
Can you provide your code? It'll help us narrow down the possibilities.

**Comment by SnowBerryZ** [comment]
The Error appears on all my Cog Commands first Time... On my Bot without Slash, is this running all perfectly 😕

Here a simple Fun-Command:
```
@cog_ext.cog_slash(name="cocktail" description="Trinke etwas...", guild_id=server_id)
    async def cocktail(self, ctx, member: discord.Member = None):
        if member:
            await ctx.send(f'{ctx.author.mention} schiebt {member.mention} {random.choice(cocktail)} rüber.')
        else:
            await ctx.send(f'{ctx.author.mention} schlürft angetrunken {random.choice(cocktail)}.')
```
Ignore the Tabs... Be Mobile ^_^

**Comment by Catalyst4222** [comment]
That code seems good to me. Could you send the traceback?

**Comment by SnowBerryZ** [comment]
Sure ^^

```
An exception has occurred while executing command `cocktail`:
Traceback (most recent call last):
  File ".../venv/lib/python3.8/site-packages/discord_slash/client.py", line 1352, in invoke_command
    await func.invoke(ctx, **args)
  File ".../venv/lib/python3.8/site-packages/discord_slash/model.py", line 209, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File ".../extensions/user.py", line 53, in cocktail
    await ctx.send(f"{ctx.author.mention} schiebt {member.mention} einen {random.choice(cocktail)} rüber!")
  File ".../venv/lib/python3.8/site-packages/discord_slash/context.py", line 256, in send
    await self._http.post_initial_response(json_data, self.interaction_id, self._token)
  File ".../venv/lib/python3.8/site-packages/discord/http.py", line 250, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown Interaction```

**Comment by SnowBerryZ** [comment]
When you want, you can join to my Discord-Server so you can see more Error's and Commands... But the Error is pregnant xD

When is helped...

**Comment by Toricane** [comment]
Do you have multiple instances of the bot running?

**Comment by SnowBerryZ** [comment]
Nooo... Never! My default Bot is running on a other System and always offline, when i tested the Slash Feature or do you mean i have the Bot on more Discord Servers like one?

**// Edit:**
I test this on any one Discord-Server without my Development-Server.
> Nope, same error! Weird..

**Next Idea:**
Is my Main File wrong for the Slash cogs? :-\
But the Example isn't worked for me!
> Nope, is right 😀

**Comment by SnowBerryZ** [comment]
True Toricane **FIXED** !

The Error is fixed, i have kick my Bot from the Development-Server and See no more Error :o: 

Very Nice, thank you so much for our Support Guys!

**Comment by SnowBerryZ** [comment]
**// FIXED**

I have found the fucking Error 😄
This Problem have make me angry for some Days and now my Networking at Home have make performance Problem for many minutes.. So i have become the Idea, is the remote Connection a Problem from Pycharm for Slash Commands? 

Bingo, i have deployed the Beta Bot on my Dedicated Server and see is worked fine and no Error's 😄 Yuuuupi.

Thanks you so much, for your Support Guys ♡

Take care!
