### ISSUE TITLE
[BUG] Quickstart docs reference wrong PyPI package

### ISSUE THREAD

**Issue by euan-reid** [interactions-py/interactions.py#341]
In the unstable branch, the wrong PyPI package ID is used for the `pip install` command in the [quickstart docs](https://github.com/goverfl0w/discord-interactions/blob/unstable/docs/quickstart.rst) - `discord-interactions` (the ID for [Discord's own library](https://github.com/discord/discord-interactions-python)) is used instead of `discord-py-interactions`.

**Comment by Toricane** [comment]
It's technically intentional but it's not viable right now;
The plan was, near when v4.0 actually comes out to stable, Discord'll give us the PyPI  `discord-interactions` name (and the docs assume the change)

**Comment by euan-reid** [comment]
Gotcha. Congrats on getting the name! Closing this as intended then.
