### ISSUE TITLE
[MISC] missing references in gettingstarted.rst

### ISSUE THREAD

**Issue by Amqzon** [interactions-py/interactions.py#350]
References for the errors page and listeners page lead to missing files inside the Handling my errors section in https://github.com/goverfl0w/discord-interactions/blob/stable/docs/gettingstarted.rst

**Comment by benwoo1110** [comment]
It works on actual RTD site for me. https://discord-interactions.readthedocs.io/en/latest/gettingstarted.html

**Comment by Amqzon** [comment]
i viewed the file on github so i suppose this is isn't an error right?

**Comment by benwoo1110** [comment]
yea the docs is meant to be compiled and viewed on readthedocs site, not on github.

**Comment by Amqzon** [comment]
Ok, Thank you for the help.
