### ISSUE TITLE
[BUG] Slash command's permission not working on mobile (Android)

### ISSUE THREAD

**Issue by gendai** [interactions-py/interactions.py#360]
**Describe the bug**
When defining a specific permission for a slash command (and disabling default_permission), the slash command would be correctly greyed out on the desktop discord application but not greyed out on discord mobile (Android) and command can even be invoked without the correct permission. 

**Reproducing steps**
1 - Define a simple slash command with a role permission:

```
@slash_ctx.slash(
    name="testcmd",
    description="Test command",
    guild_ids=server_guild_id,
    default_permission=False,
    permissions={server_guild_id: [create_permission(ROLE_ID, SlashCommandPermissionType.ROLE, True)]})
async def test_cmd(ctx: SlashContext):
   await ctx.send(f'Ok')
```

2 - Test the command on desktop discord (without the Role): command is greyed out
3 - Test the command on mobile discord (Android): command is not greyed out and can be invoked

**What's normally expected**
Slash command should be correctly restricted on mobile discord application (Android) given permissions.

**What actually happened**
Any user can invoked command on discord mobile application even without the correct permission.

**Versions**
- [ ] discord.py version 1.7.2.
- [ ] discord-py-interactions version 3.0.2.

**Comment by sillyElvy** [comment]
Afaik that's a discord issue and the command just isn't executed if you don't have the permission to use it.

**Comment by gendai** [comment]
> Afaik that's a discord issue and the command just isn't executed if you don't have the permission to use it.

If it was indeed the case, It would worry me less. But I try multiple time with different accounts and users without the permission were able to invoke the command on mobile.

**Comment by sillyElvy** [comment]
> > Afaik that's a discord issue and the command just isn't executed if you don't have the permission to use it.
> 
> If it was indeed the case, It would worry me less. But I try multiple time with different accounts and users without the permission were able to invoke the command on mobile.

So, if you add "print('bla')" to the command, it is executed even if the user doesn't have the perm?

But afaik that would still be a discord issue

**Comment by gendai** [comment]
> > > Afaik that's a discord issue and the command just isn't executed if you don't have the permission to use it.
> > 
> > 
> > If it was indeed the case, It would worry me less. But I try multiple time with different accounts and users without the permission were able to invoke the command on mobile.
> 
> So, if you add "print('bla')" to the command, it is executed even if the user doesn't have the perm?
> 
> But afaik that would still be a discord issue

Correct, it is executed.

I understand this might be a discord issue. If this is the case then I'll close this bug and just verify the role in the command manually.

**Comment by sillyElvy** [comment]
> > > > Afaik that's a discord issue and the command just isn't executed if you don't have the permission to use it.
> > > 
> > > 
> > > If it was indeed the case, It would worry me less. But I try multiple time with different accounts and users without the permission were able to invoke the command on mobile.
> > 
> > So, if you add "print('bla')" to the command, it is executed even if the user doesn't have the perm?
> > 
> > But afaik that would still be a discord issue
> 
> Correct, it is executed.
> 
> I understand this might be a discord issue. If this is the case then I'll close this bug and just verify the role in the command manually.

I'd wait until someone else confirms what I said, because I can only assume that's it is a discord issue.

**Comment by sami0596** [comment]
Hello,
try reinstalling discord on your phone, 
that should solve the issue.

**Comment by LordOfPolls** [comment]
it is definitely a discord side issue. I always recommend using the discord permissions system, but checking yourself in code

**Comment by gendai** [comment]
Okay, well looks like everyone agrees that this is a discord side issue, so I'm closing the issue here and I'll check the permission in the code.
