### ISSUE TITLE
[BUG] `SlashCommandOptionType.from_type` errors with Discord.py v2

### ISSUE THREAD

**Issue by Artemis21** [interactions-py/interactions.py#361]
**Describe the bug**

The `SlashCommandOptionType.from_type` function raises an error when used with Discord.py v2, because [it switches from using `abc.ABCMeta` to using `typing.Protocol`](https://github.com/Rapptz/discord.py/pull/6621).

**Reproducing steps**

Run the following with Discord.py v2 (or a fork that uses v2, like nextcord):

```python
import discord
import discord_slash

discord_slash.model.SlashCommandOptionType.from_type(discord.User)
```

**What's normally expected**

The function should return `SlashCommandOptionType.USER` when passed `discord.User`.

**What actually happened**

The following error is raised

```
Traceback (most recent call last):
  File ".../discord_slash/model.py", line 281, in from_type
    if issubclass(t, discord.abc.User): return cls.USER
  File "/usr/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "/usr/lib/python3.10/typing.py", line 1541, in _proto_hook
    raise TypeError("Protocols with non-method members"
TypeError: Protocols with non-method members don't support issubclass()
```

**Versions**

I am using 2.0 or higher, or a modified fork.

**Comment by sillyElvy** [comment]
v3 of this lib is not compatible with dpy v2

**Comment by Artemis21** [comment]
Ok, thanks.

**Comment by Artemis21** [comment]
Well, this seems to be present in v4 (unstable) too, so I will leave this open.

**Comment by i0bs** [comment]
How? V4 doesn't even have this

**Comment by Artemis21** [comment]
@goverfl0w Sorry, where can I find v4? I assumed it was the `unstable` branch but I see I was wrong.

**Comment by FayeDel** [comment]
Hiya!

v4.0 is located in the `unstable` branch, but this has its own models, rendering `discord_slash.model.SlashCommandOptionType.from_type(discord.User)` useless in that regard.

The reason why, if you're wondering, why you saw the `discord_slash` folder and its associated code in that branch was because of merge conflicts.

**Comment by Artemis21** [comment]
@DeltaXWizard Ok, thanks. So is the `discord_slash` folder just completely unused on the `unstable` branch?

**Comment by FayeDel** [comment]
Correct 👍🏻
