### ISSUE TITLE
[REQUEST] Add support for autocomplete of slash command options

### ISSUE THREAD

**Issue by CyberRex0** [interactions-py/interactions.py#362]
**What is the feature you're proposing?**
Autocomplete is now available as an option for the slash command.
That is required for this library and gives new experience.

**Additional Information**
Discord Developer Portal: Application Commands - Autocomplete
https://discord.com/developers/docs/interactions/application-commands#autocomplete

**Comment by Catalyst4222** [comment]
The autocomplete option should be planned for v4 iirc. It might not be working on release, since it will need a way to handle the request from discord and be able to assign a function to return the results. Until then, clever use of options and components should suffice

**Comment by FayeDel** [comment]
Closing in favor of #288.
