### ISSUE TITLE
[BUG] Can't use components=None anymore in normal commands

### ISSUE THREAD

**Issue by yannic-md** [interactions-py/interactions.py#364]
**Describe the bug**
I have a normal command which sends a message with buttons. If the user clicks on a button, it should edit the message with these buttons: The embed gets edited and the buttons should be removed. But since a few days, it's not working anymore. it Just says `This interaction failed.` I use `await message.edit(embed=new_embed, components=None)` for editing it.

**Reproducing steps**
1. Create a normal command that sends a message with an embed and buttons.
2. Use `await wait_for_component` to listen for a button click and remove the buttons with `await message.edit(embed=testingblabla, components=None)`
3. click on a button and see that it can't remove these buttons anymore.

**What's normally expected**
The buttons should be removed.

**What actually happened**
I receive no stack trace, it just says `This interaction failed.`

**Versions**
- [x] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by Toricane** [comment]
By using message.edit(), you are not responding back to the API saying that you responded to the button click, try `await button_ctx.edit_origin(..., components=None)`. If that doesn't work, then try `components=[]` instead. Also, for basic help like this, you can join our Discord server and ask there, and there are many helpers that can help you solve your problem sooner and faster.
