### ISSUE TITLE
[MISC] Quickstart example does not work

### ISSUE THREAD

**Issue by krisztiantobias** [interactions-py/interactions.py#365]
Hi! We have a quite mature discord bot and we want to replace the old commands with a slash. I've been trying to make the examples work for 4 hours now with no results. I followed the quickstart, I'm past the stackoverflow pages, but none of the examples worked.

Here is a sample code which should work:

```python
from discord.ext import commands
from discord_slash import SlashCommand, SlashContext

bot = commands.Bot(command_prefix="!")
slash = SlashCommand(bot, sync_commands=True)

guild_ids = [secret_id]  # Put your server IDs in this array.

@slash.slash(name="ping", description='Ping.', guild_ids=guild_ids)
async def ping(ctx: SlashContext):
	await ctx.defer()
	await ctx.send("Ping!")

@commands.command()
async def ping_old(ctx):
	await ctx.send("Ping old!")

@slash.context_menu(target=ContextMenuType.MESSAGE,
	name="commandname",
	guild_ids=guild_ids)
async def commandname(ctx: MenuContext):
	await ctx.send(
		content=f"Responded! The content of the message targeted: {ctx.target_message.content}",
		hidden=False
	)

bot.add_command(ping_old)
bot.run("secret_token")
```

Unfortunately Discord gives _'This interaction failed'_ all the time, however, there is no call or error on the bot side (Python 3.8.3, discord.py 2.0.0a). The slash command updates almost immediately when i change the name. The context menu does not show up also. I invited the bot again to the server, but that didn't help either. The old command works as expected when I call !ping_old. Would it be a temporary discord error?

Thank you in advance for your help!

**Comment by Catalyst4222** [comment]
The main reason I can think of for why that happens is you're using d.py 2.0 or a fork which doesn't add in a needed event. It looks like you did everything else needed (guild command, syncing, and the right scopes)
If you join the discord server, we should be able to give faster help than over GitHub

**Comment by krisztiantobias** [comment]
Yes, We are using discord.py 2.0.0a but the quickstart does not write that is it supported or not. Or should we use [nextcord](https://github.com/nextcord/nextcord)?

**Comment by Catalyst4222** [comment]
It assumes 1.7 because 2.0 isn't available on pip. Nextcord patches in the missing event iirc, so it should work

**Comment by krisztiantobias** [comment]
Ok, I tried this one with discord 1.7.3 and the slash part is works, but **the context menu is still hidden**, there is no Apps menu. Unfortunately discord.py is incompatible with nextcord, so it's not compatible with this discord-interactions.

**Comment by krisztiantobias** [comment]
Reinstall fixed it, it looks like nextcord really not likes discord.py. Both feature works with 1.7.3, but not with the newer alpha version.
