### ISSUE TITLE
[BUG] sync_all_commands always thinks there has been a change

### ISSUE THREAD

**Issue by krisztiantobias** [interactions-py/interactions.py#368]
**Describe the bug**
In `SlashCommand.sync_all_commands` the `cmd_data != existing_cmd` is always true in case of a context_menu.

**Reproducing steps**
1. Create a context menu command
```python
@slash.context_menu(target=ContextMenuType.USER, name="accounts")
async def accounts(ctx: MenuContext):
	await ctx.defer()
	asyncio.create_task(func_accounts(ctx))
```
2. Start your bot
3. Restart your bot
4. _"Detected changes on global, updating them"_ will appear in the logs

**What's normally expected**
When I don't modify a command, it should not detect changes.

**What actually happened**
When I don't modify a command, it detect changes and calls `put_slash_commands`. It looks like the returned command from discord is not exactly the same as what has been created previously. Based on a short debug session in `CommandData.__eq__` only the name matches.
```python
other.default_permission: True
other.description: ''
other.options: None
self.default_permission: None
self.description: None
self.options: []
```
Looks like the `CommandData.__init__` is not in harmony with the `SlashCommand.add_context_menu`:
```python
class CommandData:
def __init__(
	self,
	name,
	description=None,
	options=None,
	default_permission=True,
	id=None,
	application_id=None,
	version=None,
	**kwargs,
):
```
```python
_cmd = {
	"default_permission": None,
	"has_permissions": None,
	"name": name,
	"type": _type,
	"func": cmd,
	"description": "",
	"guild_ids": guild_ids,
	"api_options": [],
	"connector": {},
	"has_subcommands": False,
	"api_permissions": {},
}
```

**Versions**
- [x] I am using discord.py versions 1.7 and below with my code.
  - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

I'm using the 3.0.2 version with discord.py 1.7.3.

**Comment by krisztiantobias** [comment]
Workaround (or solution?):
```python
# in CommandData._init_
description=''
options=[]

# in add_context_menu
_cmd = {
	"default_permission": True,
...
}
```

**Comment by i0bs** [comment]
Closing in favor of #288 .
