### ISSUE TITLE
Slash command not registering

### ISSUE THREAD

**Issue by SpeedLight-Dev** [interactions-py/interactions.py#369]
I added in my `@slash.slash` decorator `guilds_ids=[...]` but the slash command is not registering.

When I create a slash command, the command should be created. Instead, it doesn't get created.

I'm using the latest version of `nextcord`.

**Comment by JUGADOR123** [comment]
I believe next cord had a patch to make it compatible with this lib but I'm not sure

**Comment by SpeedLight-Dev** [comment]
> I believe next cord had a patch to make it compatible with this lib but I'm not sure

Nevermind, a kwarg was missing in the examples.
