### ISSUE TITLE
Exception when ctx.guild value is id

### ISSUE THREAD

**Issue by 4surix** [interactions-py/interactions.py#37]
Hello !

Sorry to disturb you.
I use the 1.5.1 version of discord.py and 1.0.6 version of discord-py-slash-command, and I have this error :

```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "C:\Users\MOI\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\MOI\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord_slash\client.py", line 482, in on_socket_response
    if ctx.guild.id not in selected_cmd.allowed_guild_ids:
AttributeError: 'int' object has no attribute 'id'
```
  
This error is raised when the bot/app is not in the guild where the slash command was made, because at this line (45 and 56), if the guild is not found, `ctx.guild` has the id value and not the `Guild` object.

https://github.com/eunwoo1104/discord-py-slash-command/blob/20359fe23e8d9d1e26834c293665deea52144ae0/discord_slash/model.py#L45-L57
  
So I tried to find a solution in my pull request #36 .

Thank you for reading, have a nice day !

**Comment by eunwoo1104** [comment]
Looks like I forgot to change that part when updating. Thank you for fixing that, I'll check your pull request soon.
