### ISSUE TITLE
All component interactions now throw a warning message in the discord client.

### ISSUE THREAD

**Issue by EthanHicks1** [interactions-py/interactions.py#370]
**[Bug Summary]**
After updating my discord client to the newest version, aka the one release on the 22nd of November, I started getting this bogus warning message in my discord client (`This interaction failed`) after every interaction. I know the discord client update was the cause of this issue because I was getting the error message on my work PC but my personal PC which hasn't installed the update yet, never saw the error message pop up in the discord client after interacting with a component.

**Reproduction Steps**
Run any simple bot using components in a message and notice the error message popping up in the discord client. 

**What's normally expected**
That if a component is interacted with before it times out, everything will work as excepted.

**What actually happened**
Even if a component has not timed out yet, interacting with it will succeed however you will get the following error in your discord client after every interaction.
![bug](https://user-images.githubusercontent.com/20975793/143729331-b10ff580-9ad3-4047-bd11-c63393e91d87.PNG)

**Versions**
- [x] I am using discord.py versions 1.7 and below with my code
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

```
discord.py              --> 1.7.3
discord-py-interactions --> 3.0.2
```

**Comment by Catalyst4222** [comment]
Are you responding to the interaction? You do this by using `ComponentContext.edit_origin`, `.send`, or `.defer` with either `ignore` or `edit_origin` set to True

**Comment by EthanHicks1** [comment]
@Catalyst4222 does the `.send` need to be from the Context created from the `wait_for_component()` function or can it just be sent from `ctx`? Below is an example of what I have. If I uncomment the 3rd line I don't get the error but the bot ends up replying to itself which I don't really like. Based on the docs here: https://discord-interactions.readthedocs.io/en/latest/components.html?highlight=button#how-do-i-know-which-button-was-pressed it seemed that as long as you had a `.send` it was fine.

```
menu_ctx: ComponentContext = await wait_for_component(bot, components=action_row, timeout=30)
await ctx.send(content=f"You selected {menu_ctx.selected_options}")
# await menu_ctx.send(content=f"You selected {menu_ctx.selected_options}")
```

**Comment by Catalyst4222** [comment]
It has to be from `wait_for_component`, since it tells discord the interaction completed. If you don't want to respond with a message, you can do `await menu_ctx.defer(edit_origin=True)`

**Comment by EthanHicks1** [comment]
Yeah I was wanting to not edit the original message for the command I was working on and send a brand new message. Adding what you recommended fixed the issue. What you said makes sense but it's weird that this was not an issue until I updated my discord client to their most recent released version (I guess I had gotten lucky so far without running into the issue for some reason even though I am fairly certain a few days ago in a few commands I was not editing the original message and was sending new ones). I don't remember all of the doc examples but I feel like most of them don't mention that you need to do `.defer` if you don't edit the origin message. Maybe those examples where always editing the original message. Thanks for the help but again it's weird that I am I just now running into this issue because of a discord client update.

**Comment by EthanHicks1** [comment]
For future issues I will ask in the discord server before making a Github issue to see if it's actually an issue with the library or my code. Thanks again @Catalyst4222
