### ISSUE TITLE
[BUG] SlashContext returns invalid user status

### ISSUE THREAD

**Issue by Shandeika** [interactions-py/interactions.py#374]
**Describe the bug**
If you call a slash command and take ctx.member.status from it, we get an incorrect value (offline). If you explicitly pass the user, there is no such problem. That is, if I choose a person (the member parameter, which is optional), then this problem does not arise.
```python
    @cog_ext.cog_slash(name="user", description="Посмотреть информацию о пользователе")
    async def user(self, ctx: SlashContext, member: discord.Member = None):
        if member is None:
            member = ctx.author
        status = {
            discord.Status.online: "<:online:883791849607790602> Онлайн",
            discord.Status.idle: "<:idle:883791849796546560> Отошел",
            discord.Status.dnd: "<:dnd:883791849456816169> Не беспокоить",
            discord.Status.offline: "<:offline:883791849318408203> Не в сети",
        }
        embed = discord.Embed(
            title=f"Информация о {member.display_name}",
            description=self.cache.get_user(member.id).biography,
            color=member.top_role.color)
        embed.set_thumbnail(url=member.avatar_url)
        embed.set_author(name=member.display_name, icon_url=member.avatar_url)
        embed.set_footer(text=f"ID: {member.id}")
        embed.add_field(name="Имя пользователя", value=member.name)
        embed.add_field(name="Статус", value=status[member.status], inline=False)
        embed.add_field(name="Присоединился",
                        value=f"<t:{int(member.joined_at.timestamp())}:D> (<t:{int(member.joined_at.timestamp())}:R>)",
                        inline=True)
        embed.add_field(name="Создал аккаунт", value=f"<t:{int(member.created_at.timestamp())}:f>", inline=True)
        await ctx.send(embed=embed)
```

**Reproducing steps**

1. I call the slash command without selecting the user
2. I receive a response with incorrect user status data

**What's normally expected**
Getting the correct user status. dnd instead of offline
![изображение](https://user-images.githubusercontent.com/43181505/145102772-c55adcd7-b571-4ace-bec6-d6f24eb4cc03.png)

**What actually happened**
I get an incorrect user status. Offline instead of dnd
![изображение](https://user-images.githubusercontent.com/43181505/145102748-e665dfa4-e66b-427c-b2ae-05eace3f6ac6.png)

**Versions**
- [x] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by Shandeika** [comment]
In theory, this problem can be fixed if the bot searches for the user by id from SlashContext, but this looks more like a crutch than a solution.

**Comment by i0bs** [comment]
Closing this in favor of #288 .
