### ISSUE TITLE
[MISC] - Pypi web page installation update.

### ISSUE THREAD

**Issue by therealOri** [interactions-py/interactions.py#378]
I come to you to let you know that the pypi [web page](https://pypi.org/project/discord-py-interactions/) needs to be updated involving the installation process. (To use the proper name)

Currently says do this to install: `pip install -U discord-py-slash-command`
You no longer use that name as far as I can see and it conflicts with the name of the package.

Shouldn't it be `pip install -U discord-py-interactions` instead?

Either way, the name of what we are being told to install is different from the name of the package/library.

**Comment by i0bs** [comment]
Ignore it, `discord-py-interactions` is the correct one to be installing. We will be releasing version `4.0.0` today, so this won't be seen by most.
