### ISSUE TITLE
[MISC]  Pypi webpage formatting/embedding.

### ISSUE THREAD

**Issue by therealOri** [interactions-py/interactions.py#379]
[discord-py-interactions](https://pypi.org/project/discord-py-interactions/)
Idk if it's just my browser or what not but I'd like to bring this to your attention if it hasn't already, but your image links that are supposed to be embedded, aren't working as they should. (Same thing at the bottom of the page)

It may work for your readme.rst but I don't think the pypi page likes it.

![2021-12-14_12-26](https://user-images.githubusercontent.com/45724082/146066654-eaf41f69-1058-4279-b345-3a88382ed340.png)

Also, adding a spot/section like the last page for installation: `pip install -U discord-py-interactions` would be neat.

**Comment by i0bs** [comment]
Oh wow, that really sucks. It's most likely because the `setup()` method we're using from `setuptools` doesn't have `.RST` configured as the correct description format. We'll have a fix most likely for that in the next release.
