### ISSUE TITLE
[BUG] Cannot run v4 and discord.py simultaneously

### ISSUE THREAD

**Issue by Temmie3754** [interactions-py/interactions.py#381]
**Describe the bug**
V4 and discord.py do not run together as they should outlined by the docs.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Create a client variable for the library.
3. Follow the FAQ's guide to running v4 with discord.py (either copying the code or running one of a similar format).
4. Attempt to run a discord.py command or have a print statement in discord.py's on_ready.

**What's normally expected**
The command will execute and function correctly.

**What actually happened**
The command is not executed and the client for discord.py will not have started.

**Versions**
- [X] I am using discord.py versions 1.7 and below with my code.
    - [X] I am using 2.0 or higher, or a modified fork. (it occurs on discord.py 1.7.3 and Pycord 1.7.3)
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
Can you provide the actual code?

**Comment by Temmie3754** [comment]
```
import interactions
from discord.ext import commands

interactions = interactions.Client(token="TOKEN")
dpy = commands.Bot(command_prefix="/")

@dpy.command()
async def hello(ctx):
    await ctx.send("Hello from discord.py!")

@interactions.command(
    name="test",
    description="this is just a testing command.", scope=[913188722395217930]
)
async def test(ctx):
    await ctx.send("Hello from discord-interactions!")

interactions.start()
dpy.run(token="TOKEN", bot=True)
```

**Comment by i0bs** [comment]
Oh that's interesting. Out of curiosity, can you swap the d.py and v4 starter methods for me and see what happens? I want to see if either:

a. `discord.py` functions, but `v4.0.0` will not.
b. both will work.

**Comment by sillyElvy** [comment]
should be a

at least from what i tested two weeks ago

**Comment by Temmie3754** [comment]
yeah it's a, whichever goes first doesn't run anything after it

**Comment by i0bs** [comment]
The problem has likely to do with how both libraries work on runtime.

`v4.0.0`'s implementation of the gateway is an indefinite websocket connection. The only practical way that you would be able to also let `discord.py` run at the same time is somehow manually adding it into the base of the library. This is, however, a *really* bad approach to handling simultaneous library connections.

What could be done here is establishing your own `threading.Event` protocols to run both of the libraries, and then calling both of the events to start in one method, and then calling that method. It's *theoretical* but it might work.

**Comment by FayeDel** [comment]
Hiya!

The reason why they both can't work simultaneously in this example was partly what fl0w said, and generally, both calls are blocking; one client run call can't reach the other unless the first closes.
Threading is an option, but threading and asynchronous processes are wonky.

Here's something that I've tried, which uses asyncio tasks and loops to recreate the multiple processes (Tailored to your example);

```py
import interactions
from discord.ext import commands

interactions = interactions.Client(token="TOKEN")
dpy = commands.Bot(command_prefix="/")

@dpy.command()
async def hello(ctx):
    await ctx.send("Hello from discord.py!")

@interactions.command(
    name="test",
    description="this is just a testing command.", scope=[913188722395217930]
)
async def test(ctx):
    await ctx.send("Hello from discord-interactions!")

loop = asyncio.get_event_loop()

task2 = loop.create_task(dpy.start(token="TOKEN", bot=True))
task1 = loop.create_task(interactions.ready())

gathered = asyncio.gather(task1, task2, loop=loop)
loop.run_until_complete(gathered)
```

In this example, just for reference, I switched out start() for ready() because it's basically a sync/async equivalent.

Here's my test but with the `?` prefix for visuals:
![image](https://user-images.githubusercontent.com/33706469/146227458-14917a63-ff00-4e53-a502-75580e029368.png)

**Comment by Temmie3754** [comment]
Alright this works with a few tweaks, not ideal but seems to function fine. Thanks for the help.
