### ISSUE TITLE
[BUG] Documentation Bug in  interactions.models.component.Button

### ISSUE THREAD

**Issue by niklasmoell** [interactions-py/interactions.py#383]
**Describe the bug**
The Documentation is wrong.

**Reproducing steps**
Look in the Documentation:
https://discord-interactions.readthedocs.io/en/unstable/models.component.html

![image](https://user-images.githubusercontent.com/79917043/146213118-5806e670-21d6-4dc3-b560-dabe44fab0a1.png)

**What's normally expected**
The name of the argument should be "label".

**What actually happened**
The name of the argument is "str". 

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
Flagged.
