### ISSUE TITLE
[BUG] Intents don't work

### ISSUE THREAD

**Issue by FloWIsCoding** [interactions-py/interactions.py#391]
**Describe the bug**
I tried to put `interactions.Intents.PRIVILIGED` in the client, the bot turn online correctly but a lot of errors occurs.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the library 
2. Create a client variable for the library with `interactions.Intents.PRIVILIGED` in `intents` attribute.
3. Execute the program.
4. See the  error given in the terminal.

**What's normally expected**
It's supposed to work like the bot have all intents.

**What actually happened**
Instead, I received this error given from my Python terminal:

```
WARNING:mixin:Attribute tags is missing from the Application data model, skipping.
WARNING:mixin:Attribute user is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute status is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute client_status is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute activities is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute user is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute status is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute client_status is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute activities is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute user is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute status is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute client_status is missing from the PresenceActivity data model, skipping.
WARNING:mixin:Attribute activities is missing from the PresenceActivity data model, skipping.
```
with `interactions.Intents.DEFAULT`, we have :
```
WARNING:mixin:Attribute tags is missing from the Application data model, skipping.
```

I have already checked in the [code](https://github.com/goverfl0w/discord-interactions/blob/stable/interactions/api/models/intents.py) so can someone help me?

**Versions**
- [ ] I am using discord-py-interactions versions 4.0.

**Special**
*Sorry for my mistakes in english*

**Comment by i0bs** [comment]
Can you please provide to me what your code looks like when you're using `Presence` or `PresenceActivity`?

**Comment by FloWIsCoding** [comment]
> Can you please provide to me what your code looks like when you're using `Presence` or `PresenceActivity`?

```
from interactions import *
guild_id= #MyGuildID#
bot = Client(token="token",intents=Intents.DEFAULT | Intents.PRIVILEGED)

@bot.event
async def on_ready():
    print("en ligne")
    
@bot.command(name="test",scope=guild_id, description="Juste une commande de test!")
async def test(ctx:context.CommandContext):
    print(ctx.author)

bot.start()
```

**Comment by i0bs** [comment]
`Intents.DEFAULT | Intents.PRIVILEGED` is the same things as `Intents.ALL`. You can also try doing it as `intents=[]` and listing all of the intents you want to pass. We've fixed the mixin warnings as well, but this looks like a client issue.
