### ISSUE TITLE
Utilisation

### ISSUE THREAD

**Issue by thomaskeig** [interactions-py/interactions.py#4]
Is the code below a new command, how would I add slash commands to and existing @bot.command() command? 

```
​@​slash​.​slash​(​name​=​"test"​)​
​async​ ​def​ ​_test​(​ctx​: ​SlashContext​):
    ​embed​ ​=​ ​discord​.​Embed​(​title​=​"embed test"​)
    ​await​ ​ctx​.​send​(​content​=​"test"​, ​embeds​=​[​embed​])
```

**Comment by thomaskeig** [comment]
Oh, I think I understand. You use it as a seperate command.

**Comment by thomaskeig** [comment]
Ok no, I dont understand. The code below is exactly what I've used but when I type in "/" it just shown inbuilt commands. I've also done CTRL+R to restart discord while the bot is still running.

```
import discord
from discord.ext import commands
from discord_slash import SlashCommand
from discord_slash.model import SlashContext

bot = commands.Bot(command_prefix="!")
slash = SlashCommand(bot)


@slash.slash(name="test")
async def _test(ctx: SlashContext):
    embed = discord.Embed(title="embed test")
    await ctx.send(content="test", embeds=[embed])

@bot.event
async def on_ready():
    print('Bot loaded')

bot.run("TOKEN-HERE")
```

**Comment by thomaskeig** [comment]
I'm pretty sure I have the same issue as this guy https://github.com/eunwoo1104/discord-py-slash-command/issues/3 I'll do what they did...

**Comment by Leastrio** [comment]
You need to either use the libs built in way or send a post request to discords api, https://discord.com/developers/docs/interactions/slash-commands#create-guild-application-command

**Comment by thomaskeig** [comment]
Ok thanks
