### ISSUE TITLE
Support options for subcommands

### ISSUE THREAD

**Issue by spinnerich** [interactions-py/interactions.py#40]
Please add the possibility to add options to subcommands.
Since the official API allows this feature, I think it should also be available through this library.
Being able to create more complex slash commands would be great.

**Comment by eunwoo1104** [comment]
Saying for just in case, args are already supported by this extension.
The reason why there is no `options` arg at the decorator is because right now `auto_register` doesn't support subcommands.
I'll think about adding `options` arg though, or maybe supporting auto-registering subcommands.
