### ISSUE TITLE
[BUG] Error when sending empty messages

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#403]
**Describe the bug**
Using `http.create_message` leads an error with the caching if the message is empty  

**What happened**
~~Instead, I received this traceback error given from my Python terminal:~~
![unknown-16.png](https://user-images.githubusercontent.com/88881326/147514218-f463ad11-72b2-45a7-9443-a93342b86e04.png)

[Thread](https://discord.com/channels/789032594456576001/925169826639515701/925169833312665640) 

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [X] I am not using any of the listed above and am using the library code alone.

**Comment by i0bs** [comment]
are you gonna close the Issue since you made a commit fixing this @DeltaXWizard ? 👁️👄👁️

**Comment by FayeDel** [comment]
oml
(to be fair, I feel bad because I genuinely forgot about this issue)

Yeah, closing :)

**Comment by i0bs** [comment]
ty cutie 💞 💖 💖
