### ISSUE TITLE
[MISC] http.edit_channel_permission does not include reason it its request.

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#404]
Can check it in the image below:

![grafik](https://user-images.githubusercontent.com/88881326/147589799-aa834a47-207a-460a-a597-2e103fad8688.png)

**Comment by i0bs** [comment]
Probably got commented out to avoid the nice `reason` attribute error we were getting with making HTTP requests.

**Comment by FayeDel** [comment]
Probably,
This has been added to `unstable` as of 882c273, so I'm closing this issue.
