### ISSUE TITLE
[QUESTION] No return value in the `modify_guild` request?

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#415]
Why do you not return a value in the `modify_guild` request?
![grafik](https://user-images.githubusercontent.com/88881326/148054717-f4aa8746-90c9-48dd-aab0-c2df32cd7074.png)

according to the [discord documentation](https://discord.com/developers/docs/resources/guild#modify-guild) it will return the updated guild object

**Comment by FayeDel** [comment]
To be honest, I forgot why I type hinted it None
But looking back, I think it was just one of those tired mistakes I had making all those endpoints, but yeah it was supposed to return the updated Guild object (besides, I think this error only affects typehinting)

Thanks for pointing out though :) I'll look into it

**Comment by sillyElvy** [comment]
> (besides, I think this error only affects typehinting)

It would, but you also do not return anything. But if it wasn't intended I'll fix it in my PR
