### ISSUE TITLE
[MISC] The installation of the lib need maturin to build Orjson

### ISSUE THREAD

**Issue by NonAccount** [interactions-py/interactions.py#424]
Hello the installation of the discord-interactions need maturin to build the orjson.

**Comment by V3ntus** [comment]
This is addressed in the roadmap
> If `orjson` isn't detected, fallback to `json`

Right now, I believe it's fixed by falling back to python 3.9 or below. Also I may have heard `unstable` branch might also fix it

**Comment by i0bs** [comment]
Duplicate of #388
