### ISSUE TITLE
[MISC] Revamping the cogs/extension framework

### ISSUE THREAD

**Issue by V3ntus** [interactions-py/interactions.py#425]
As per James, Delta, Catalyst, etc. conversation in Discord, creating this issue just to track progress accordingly on the Git repo. There were lots of people interested in contributing it seems

James:
> the problem we have is that we're trying to make a decorator from the client work in a different class, and unless we do some incredibly disgusting functools wrapper hacky logic, it's not possible to base a decorator off of a class attr
> that's what makes it really hard for us
> 
> but i saw Joe [@V3ntus] do something with making a method external from both classes and having it simply call the client's event method we use, which makes it very easy to use
>
> i'll probably do something like this but in our decor file and organize it so it can differentiate between listeners and callback wraps we use

**Comment by sillyElvy** [comment]
Closing this issue because #428 was merged.
