### ISSUE TITLE
[BUG] Cannot specify intents as a list

### ISSUE THREAD

**Issue by snazzyfox** [interactions-py/interactions.py#442]
**Describe the bug**

When `intents` is passed as a list to `Client`, it is appended to without initialization.

**Reproducing steps**

Reproduction code:

```py
from interactions import Client, Intents

bot = Client(
    token='TOKEN',
    intents=[Intents.GUILDS, Intents.GUILD_MEMBERS],
)

bot.start()
```

**Expected behavior**
Intent number is computed from the list.

**What actually happened**
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\snaz\Documents\dpy-int-test\bot.py", line 4, in <module>
    bot = Client(
  File "C:\Users\snaz\AppData\Local\pypoetry\Cache\virtualenvs\dpy-int-test-coV1hBcm-py3.10\lib\site-packages\interactions\client.py", line 64, in __init__
    self.intents |= intent
AttributeError: 'Client' object has no attribute 'intents'
```

**Root cause**
When intents is a list, the code tries to repeatedly binary-or all passed intent numbers without initializing the variable first.

**Versions**
Reproduced on `4.0.1`, `stable`, and `unstable`.

- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by benwoo1110** [comment]
yea looks like an oversight, for now you can just do `intents=Intents.GUILDS | Intents.GUILD_MEMBERS`

**Comment by snazzyfox** [comment]
Thanks - I'll also send a PR for a quick fix.
