### ISSUE TITLE
[BUG] Leftover debug prints in synchronize()

### ISSUE THREAD

**Issue by snazzyfox** [interactions-py/interactions.py#443]
**Describe the bug**

Starting the bot always print out the internal list of commands. This is presumably prints used during debugging that should have been removed or changed to proper logging. These lists can be very long if there are many registered commands with many parameters specified.

https://github.com/goverfl0w/interactions.py/blob/unstable/interactions/client.py#L272-L273

**Reproducing steps**

Start any valid bot.

**What's normally expected**
The bot starts up without unnecessary debug output.

**What actually happened**
The bot prints out two lists of application commands regardless of log level.

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by benwoo1110** [comment]
~~Should have been fixed in unstable with https://github.com/goverfl0w/interactions.py/pull/421~~

Edit: Oh sorry, different logging issue. You can open a pr to change it to a log.debug

**Comment by snazzyfox** [comment]
Will do, thanks

**Comment by FayeDel** [comment]
Closing this issue as the associated PR has been merged.
