### ISSUE TITLE
[BUG] Cannot send a message with button interaction (v4.0.2)

### ISSUE THREAD

**Issue by jmmaa** [interactions-py/interactions.py#454]
**Describe the bug**
I just recently installed the v4.0.2 version but my @component function doesn't seem to send message.

**Reproducing steps**
I've uninstalled v4.0.1@unstable and installed v4.0.2. These are the steps in reproducing the bug

1. Import the library to the code.
2. Create a client/bot.
3. Create a simple slash command that sends a message with an embed and a button.
4. Create a component decorator function for the button.
5. access the embed information (something like title or description) in component func.
6. send a message when the component function is called.

Here is the sample code I made that reproduces the bug:
```Python
import interactions


bot = interactions.Client(token="TOKEN")

bug_button = interactions.Button(
    style=interactions.ButtonStyle.PRIMARY,
    custom_id="bug_btn",
    label="submit",
)


@bot.command(
    name="bugtest",
    scope=1234567890,
    description="squish",
    default_permission=True,
)
async def test(ctx: interactions.CommandContext):
    embed = interactions.Embed(title="Working")
    await ctx.send(content="test", embeds=embed, components=bug_button)


@bot.component(bug_button)
async def bug_button_clicked(ctx: interactions.ComponentContext):
    print(ctx.message.embeds[0].title)
    await ctx.send(content="Working")


bot.start()
```

**What's normally expected**
The bot should send a message with the embed info

**What actually happened**
This is the traceback

```
Traceback (most recent call last):
  File "d:\Github Repositories\bronya-bot\test3.py", line 28, in bug_button_clicked
    await ctx.send(content="Working")
  File "C:\Python39\lib\site-packages\interactions\context.py", line 326, in send
    payload: Message = Message(
  File "C:\Python39\lib\site-packages\interactions\api\models\message.py", line 267, in __init__
    [Embed(**embed) for embed in self.embeds] if self._json.get("embeds") else None
  File "C:\Python39\lib\site-packages\interactions\api\models\message.py", line 267, in <listcomp>
    [Embed(**embed) for embed in self.embeds] if self._json.get("embeds") else None
TypeError: interactions.api.models.message.Embed() argument after ** must be a mapping, not Embed
```

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ ] I am not using any of the listed above and am using the library code alone.
- [x] I am using Python v3.9.6
- [x] I am using interactions.py v4.0.2

**Comment by i0bs** [comment]
This seems to be an issue with embeds, not components. Can you add `._json` to your `embeds=embed`?

**Comment by jmmaa** [comment]
> This seems to be an issue with embeds, not components. Can you add `._json` to your `embeds=embed`?

I did and got a traceback
```
Traceback (most recent call last):
  File "d:\Github Repositories\bronya-bot\test3.py", line 22, in test
    await ctx.send(content="test", embeds=embed._json, components=bug_button)
  File "C:\Python39\lib\site-packages\interactions\context.py", line 206, in send
    else [embeds._json]
AttributeError: 'dict' object has no attribute '_json'
```

**Comment by Virgile-Dauge** [comment]
> > This seems to be an issue with embeds, not components. Can you add `._json` to your `embeds=embed`?
> 
> I did and got a traceback
> 
> ```
> Traceback (most recent call last):
>   File "d:\Github Repositories\bronya-bot\test3.py", line 22, in test
>     await ctx.send(content="test", embeds=embed._json, components=bug_button)
>   File "C:\Python39\lib\site-packages\interactions\context.py", line 206, in send
>     else [embeds._json]
> AttributeError: 'dict' object has no attribute '_json'
> ```

As you closed it, you must have found some kind of workaround. Could you please share it @arkhon7?

**Comment by jmmaa** [comment]
> As you closed it, you must have found some kind of workaround. Could you please share it @arkhon7?

I used the unstable branch as the issue was already solved in there, take note that you might still want to add `._json` on every embed class objects
