### ISSUE TITLE
[REQUEST] Message and User Commands

### ISSUE THREAD

**Issue by YHDiamond** [interactions-py/interactions.py#458]
**What is the feature you're proposing?**
I would love if Message and User Commands were in this library. 
Discord API Docs for them:
https://discord.com/developers/docs/interactions/application-commands#user-commands
https://discord.com/developers/docs/interactions/application-commands#message-commands

**Additional Information**
Most of the stuff required to do this already exists in the Slash Commands part of the library.

**Comment by i0bs** [comment]
We already have these usable in either the main, "universal" decorator `@command` or our feature converters `@user_command` and `@message_command`.

**Comment by YHDiamond** [comment]
Oh really? I couldn't find any info about it on the docs, would you be able to provide a quick code example?

**Comment by i0bs** [comment]
[Refer to this page.](https://discord-interactions.readthedocs.io/en/latest/client.html)

**Comment by YHDiamond** [comment]
Oh I think I might have been reading the wrong docs! So sorry to bother you and thanks so much for your help. Have a nice day/night!
