### ISSUE TITLE
Inconsistent parameter naming for subcommand decorator

### ISSUE THREAD

**Issue by mavit** [interactions-py/interactions.py#46]
The `subcommand` decorator has the following paramers:
- `base_desc`
- `description`
- `sub_group_desc`
- `subcommand_group`

They would be easier to remember if they were named consistently.  For example:
- `base_description`
- `description`
- `subcommand_group_description`
- `subcommand_group`

**Comment by eunwoo1104** [comment]
I actually named like that because I thought it would be too long to use the full name. I'll rename those though, since this naming can be confusing and hard to remember like you said.

**Comment by eunwoo1104** [comment]
Changed on new commit.
