### ISSUE TITLE
[REQUEST] Implement component-specific attributes from v3

### ISSUE THREAD

**Issue by FayeDel** [interactions-py/interactions.py#480]
**What is the feature you're proposing?**
Essentially, some v3-based properties like ctx.component, ctx.selected_options, etc, are not present in v4. They can be iterated manually, but it would be nicer if there'd be a `@property` based attribute that has the lib abstract the iteration and such similar to how v3 was, so we can also have `ctx.label` (`ctx.component` could arguably be redundant if you're using a callback for one singular component, or not for multiple stacked decorator usage.)

**Additional Information**
- [ ] My feature request is related to an existing Issue.
    - Issue (if referenceable):

**Comment by Damego** [comment]
Ig `ctx.component` should be.
We can change component and then edit message with updated components
```py
ctx.component.label/style/disabled = *something*
await ctx.edit(components=ctx.message.components)
```
