### ISSUE TITLE
[REQUEST] Add ability to travel back in time

### ISSUE THREAD

**Issue by r-warfield** [interactions-py/interactions.py#491]
**What is the feature you're proposing?**
Ngl I think we really need to travel backwards in time for a multitude of reasons. For reference to you smaller minded people, the function to do this is `asyncio.unsleep()`. 

**Additional Information**
- [x] My feature request is related to an existing Issue.
    - Every issue ever.

**Comment by i0bs** [comment]
Issues are intended to be used seriously. This issue is a violation of the Code of Conduct found in our [contribution requirements.](https://github.com/interactions-py/blob/unstable/CONTRIBUTING.rst) As a result, this Issue will be closed.
