### ISSUE TITLE
[REQUEST] Unit testing

### ISSUE THREAD

**Issue by i0bs** [interactions-py/interactions.py#496]
**What is the feature you're proposing?**
`unstable` is a land of both creativity and instability, which is commonly seen from the consistency in bugs appearing on this branch. This branch helps us with standardising a rapid development workflow, however, we often find ourselves having issues with detecting when regular core features of the library begin to break. It's hard to always be able to check every area of this library ourselves, so, I would like to suggest unit testing. This would be a sound and dependable way for us to keep a consistent method in testing parts of the library and halting our ability from committing new code if something fails as a check.

The introduction of unit testing would work in a similar fashion to `pre-commit`. Additionally, we've now enabled readthedocs builds to occur per Pull Request made in this repository, which will be useful for documentation-based changes as well.

**Additional Information**
- [ ] My feature request is related to an existing Issue.
    - Issue (if referenceable):

**Comment by LordOfPolls** [comment]
Resolved in 5.x
