### ISSUE TITLE
[REQUEST] Organise pre-commit configuration and CI/CD workflow.

### ISSUE THREAD

**Issue by i0bs** [interactions-py/interactions.py#497]
**What is the feature you're proposing?**
`pre-commit` has been a very useful tool for us as developers so far to ensure a consistently linted, formatted, and error-checked codebase. However, the current configuration that we have for it is rather messy and inconsistent in terms of working with our CI actions. I would like to put more effort into organising this, as well as making this a continuously automated task as both an integration and delivery service for Pull Requests made alongside commits as we currently do. This would not only allow for more accurate on-the-fly checking, but the ability to allow `pre-commit.ci` to automatically push commits to a Pull Request's branch in particular to fix the problems it runs into (if they're easily correctable) in terms of autoupdating.

With this, I would like to additionally break down our CI/CD workflow into the following areas:
- General pre-commit CI (w/ autoupdate)
- Publish library
- Code QL checking for vulnerabilities + optimisation
- Unit testing
- Readthedocs build previews
- black and flake8 for styling + formatting

**Additional Information**
- [X] My feature request is related to an existing Issue.
    - Issue (if referenceable): #496

**Comment by V3ntus** [comment]
May or may not be related but it might be useful to see base branch checking before merges on PRs. 

`${{ github.event.pull_request.base.ref }}`

**Comment by i0bs** [comment]
CI/CD workflow and pre-commit config were changed not too long ago. Closing.
