### ISSUE TITLE
[BUG] Defer (ignore = True) is missing for Unstable Version

### ISSUE THREAD

**Issue by GeomKid** [interactions-py/interactions.py#507]
Currently Using V4.0.2 unstable version and I noticed for componentContext the await defer (ignore= True ) option is missing

**Comment by i0bs** [comment]
There is no such thing as an `ignore` field in the API docs for deferring. You may have been mistaken for `ephemeral`, which is the proper name of hiding an interaction response.

**Comment by Toricane** [comment]
> There is no such thing as an `ignore` field in the API docs for deferring. You may have been mistaken for `ephemeral`, which is the proper name of hiding an interaction response.

No, there used to be an ignore param in v3 defer

**Comment by Toricane** [comment]
But you are right that it's not in API
