### ISSUE TITLE
[BUG] TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by dontbanmeplz** [interactions-py/interactions.py#510]
**Describe the bug**
message should delete but cannot find id of message
**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Create a client variable for the library.
3. Try creating a slash command.
4. send a message
5.  Delete the message
6. See the traceback error given in the terminal or logger file.

**What's normally expected**
The message should be deleted

**What actually happened**
Instead, I received this traceback error given from my Python terminal:

```
Traceback (most recent call last):
  File "/root/inter/main.py", line 233, in buy
    await n.delete()
  File "/usr/local/lib/python3.8/dist-packages/interactions/api/models/message.py", line 335, in delete
    message_id=int(self.id), channel_id=int(self.channel_id), reason=reason
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
code:
https://pastebin.com/qfJU76TF
**Versions**
newest unstable
wait_for

**Comment by sillyElvy** [comment]
could you try without ``wait_for``?

**Comment by dontbanmeplz** [comment]
it shouldent make a diffrence, it is not inside or looking from a wait_for

**Comment by i0bs** [comment]
`delete()` is functioning fine for me, but it's a good rule of thumb to isolate dependencies and see if it's an issue relating to ours or another one.

**Comment by dontbanmeplz** [comment]
it works with just a normal send sleep and delete, i dont know the problem with the code i have

**Comment by sillyElvy** [comment]
Could you try to use ``ctx.delete()`` instead? I believe this solved that problem once

**Comment by dontbanmeplz** [comment]
did nothing with no error

**Comment by sillyElvy** [comment]
Try to uninstall the "latest" unstable version and then reinstall it, for me it works fine even if in a command.

**Comment by dontbanmeplz** [comment]
nothing

**Comment by sillyElvy** [comment]
and with the `n.delete()`?

**Comment by dontbanmeplz** [comment]
```
Traceback (most recent call last):
  File "/root/inter/main.py", line 232, in buy
    await n.delete()
  File "/usr/local/lib/python3.8/dist-packages/interactions/api/models/message.py", line 335, in delete
    message_id=int(self.id), channel_id=int(self.channel_id), reason=reason
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
same error as before

**Comment by sillyElvy** [comment]
That's so weird because I cannot reproduce it.

**Comment by dontbanmeplz** [comment]
did you look at the pastebin code?

**Comment by sillyElvy** [comment]
```py
a = await ctx.send("a", components=Button(style=ButtonStyle.DANGER, label="Test", custom_id="none"))
await a.delete()
```

I was trying with this and it worked fine.

**Comment by dontbanmeplz** [comment]
for some reason it is only failing on that send
it works fine in another part of my program

**Comment by sillyElvy** [comment]
does the other part has a wait_for?

**Comment by dontbanmeplz** [comment]
i did both, and it works with and without

**Comment by sillyElvy** [comment]
could you show your component code`?

**Comment by dontbanmeplz** [comment]
https://pastebin.com/qfJU76TF

**Comment by sillyElvy** [comment]
![grafik](https://user-images.githubusercontent.com/88881326/153663937-8ac3dcb5-822f-41f0-ac01-ec608fe1c784.png)
 i don't see this part there

**Comment by dontbanmeplz** [comment]
```python
yny = interactions.Button(
    style=interactions.ButtonStyle.SUCCESS,
    label="Yes",
    custom_id="yes",
)
ynn = interactions.Button(
    style=interactions.ButtonStyle.DANGER,
    label="No",
    custom_id="no",
)
yn = [yny,ynn]
```
my bad

**Comment by sillyElvy** [comment]
hm
they're fine, too

idk whats wrong then

**Comment by dontbanmeplz** [comment]
yeah its odd because it works everywhere else

**Comment by Catalyst4222** [comment]
Is the message you're trying to delete a hidden message?

**Comment by sillyElvy** [comment]
> Is the message you're trying to delete a hidden message?

It's not, you can look in the pastebin

**Comment by dontbanmeplz** [comment]
@Catalyst4222 no look at the code

**Comment by dontbanmeplz** [comment]
Any suggestions?

**Comment by laToufff** [comment]
i have the same issue with the .edit() method. It sends the message from the Context object, but then I fails to edit and log the same error message as you.

**Comment by FayeDel** [comment]
Hiya!

I noticed you included the `print(n._json)` line right before that error on your traceback, mind showing me what that returns?

**Comment by dontbanmeplz** [comment]
@DeltaXWizard  thought it woud shed some light but it didnt
```json
{'content': 'Do you wish to buy 2 AAPL with a total cost of 340.88?', 'tts': False, 'embeds': [], 'allowed_mentions': {}, 'components': [{'type': 1, 'components': [{'style': 3, 'label': 'Yes', 'custom_id': 'yes', 'type': 2}, {'style': 4, 'label': 'No', 'custom_id': 'no', 'type': 2}]}], 'flags': 0}
```

**Comment by FayeDel** [comment]
It does thank you :)
Would you mind updating your instance to latest unstable and try again?

**Comment by dontbanmeplz** [comment]
@DeltaXWizard that fixed it, thanks!
