### ISSUE TITLE
[BUG] Error when creating option name with uppercase letters unclear

### ISSUE THREAD

**Issue by r-warfield** [interactions-py/interactions.py#517]
**Describe the bug**
When you create a chat_input command with uppercase letters, it only raises a 50035. It should tell the user that they used uppercase letters.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Import the module in Python.
2. Create a client variable for the library.
3. Create a chat-input command with an option that has a title with uppercase letters

**What's normally expected**
When I create a slash command with an option , It should tell the user that they used uppercase letters.

**What actually happened**
Instead, I received a 50035
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/interactions/api/http.py", line 282, in request
    raise HTTPException(data["code"], message=data["message"])
interactions.api.error.HTTPException: Invalid Form Body Error code: 50035
```

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [ x] I am not using any of the listed above and am using the library code alone.

**Comment by r-warfield** [comment]
making a pr as we ||dont|| speak

**Comment by i0bs** [comment]
Closing in favor of #518 .
