### ISSUE TITLE
Guild id required

### ISSUE THREAD

**Issue by quirky-bluejay** [interactions-py/interactions.py#52]
**The Issue**
In the `utils.manage_commands` functions for some commands `None` can be passed for the `guild_id` parameter to specify using a global scope, but the parameter is not optional
It would be expected that if you don't pass a guild id that it would use the global scope, instead of having to pass `None`

**Ideal solution**
Make the guild_id parameter optional

**Expected behaviour**
`utils.manage_commands.get_all_commands(id, token)` should work
ATM you have to do (id, token, None)

**Comment by eunwoo1104** [comment]
Applying that to all of the functions would be hard, since it will require reformatting sequence of parameters. However `get_all_commands` seems possible, don't know why I didn't already apply that to it.

**Comment by eunwoo1104** [comment]
Fixed on #57
