### ISSUE TITLE
[REQUEST] Add tasks.loop decorator to upcoming ext module

### ISSUE THREAD

**Issue by dgraney** [interactions-py/interactions.py#525]
**What is the feature you're proposing?**
I personally perform various tasks in the background for my bots. I believe adding in tasks.loop decorator similar to that used in the original discord.py library would be very useful. It also seems that this can be lifted 1-for-1 since it defaults to pulling `asyncio.get_event_loop` as a parameter.

**Comment by siqnole** [comment]
id like to see this as a feature. tasks.loop decorators are going to make interactions alot easier and could result in faster results (depending on loop times, other stuff, ect) and will also take a tribute to the old discord.py library aswell as keeping updates for users who are actively using tasks.loop

**Comment by mAxYoLo01** [comment]
> id like to see this as a feature. tasks.loop decorators are going to make interactions alot easier and could result in faster results (depending on loop times, other stuff, ect) and will also take a tribute to the old discord.py library aswell as keeping updates for users who are actively using tasks.loop

I have actually asked about adding loops as an interactions.py feature, but it was denied. But making it as an extension could definitely work, and I have already done a really basic implementation of it since I needed it.

**Comment by Catalyst4222** [comment]
The ext modules are made by independent devs, and not built in to the library itself. Feel free to create it yourself though

**Comment by FayeDel** [comment]
(They did suggest for it to be in ext though)

**Comment by siqnole** [comment]
> The ext modules are made by independent devs, and not built in to the library itself. Feel free to create it yourself though

alot easier if it comes with it, because the users that already have been using tasks.loop dont have to diy it risking an error.

**Comment by Catalyst4222** [comment]
The purpose of ext is to let devs create what they need, especially things that don't fit in the library or would boost it too much

And if someone does make tasks into an ext, users won't have to diy it, since it will have already been done

**Comment by i0bs** [comment]
We won't be building it into the framework itself. We highly recommend those interested to make a 3rd party themselves (what we want to see!)

**Comment by Catalyst4222** [comment]
I've started on a tasks ext, which can be found [here](https://github.com/Catalyst4222/interactions-tasks). I'm waiting to publish it until 4.1 comes out, but it should be usable if installed by `pip install -U git+https://github.com/Catalyst4222/interactions-tasks`

**Comment by dgraney** [comment]
> I've started on a tasks ext, which can be found [here](https://github.com/Catalyst4222/interactions-tasks). I'm waiting to publish it until 4.1 comes out, but it should be usable if installed by `pip install -U git+https://github.com/Catalyst4222/interactions-tasks`

Awesome! Great work and thank you!

Also, was not aware of the purpose of ext, though it certainly does make sense.
