### ISSUE TITLE
[REQUEST] Comparable models

### ISSUE THREAD

**Issue by Catalyst4222** [interactions-py/interactions.py#534]
**What is the feature you're proposing?**
Currently, it's hard to check if two objects (e.g. Members) refer to the same item on discord. I would like a way to easily check if two objects are the same, and preferably also be able to store those objects in places that need hashes (sets and dict keys)

One simpler way to do this would be to create a mixin which has methods for `__eq__` and `__hash__`, and compare/hash the ids of the objects

**Additional Information**
- [ ] My feature request is related to an existing Issue.
    - Issue (if referenceable):

**Comment by i0bs** [comment]
We *could* add this, but a simple way of doing this (internally at least) is checking the JSON attribute of the model and comparing it to another, or checking if the one you currently have has been cached. Either solution works, but I would need to see more use cases to provide a worthy case for implementing these magics.
