### ISSUE TITLE
AttributeError: 'Embed' object has no attribute '_json'

### ISSUE THREAD

**Issue by jerryfane** [interactions-py/interactions.py#535]
When trying to send a message with "embeds" `(await ctx.send('', embeds=[embed]))` I get the "**AttributeError: 'Embed' object has no attribute '_json**'" Error. 

That's actually an easy fix, you just need to change line 204 in [context.py](https://github.com/interactions-py/library/blob/stable/interactions/context.py) as: 

`[embed.to_dict() for embed in embeds]`

**Comment by sillyElvy** [comment]
Actually, this is your fault because you are using the discord embed model. You can fix this error by using `embeds=[interactions.Embed(**embed.to_dict())]`

Also you could check out the discord support server for issues like that: discord.gg/interactions
