### ISSUE TITLE
[BUG] OptionType number overrides string

### ISSUE THREAD

**Issue by iammoonman** [interactions-py/interactions.py#545]
**Describe the bug**
One of the text options in my application command has an input that is usually a number, but can be a string. Both "12a" and "72" are valid inputs. The input type is set as a string, but either Discord or the library rejects the command if the input is only a number.

**Reproducing steps**
These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

1. Create a slash command.
2. Add a string option.
3. Run the command.
4. Enter a number for that option.
5. (!) The application did not respond

**What's normally expected**
The command accepts the response as valid and my code throws errors instead.

**What actually happened**
"The application did not respond" type error. Nothing came up in the terminal.

**Versions**
- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

**Comment by iammoonman** [comment]
It's also giving an "(!) Invalid interaction application command" error

**Comment by i0bs** [comment]
We've streamlined our bug reporting process with Issue forms. Please create a new issue and link it to this one in order to provide to us clarity and more information towards your problem.
