### ISSUE TITLE
[BUG] Unstable Version Cog Loading

### ISSUE THREAD

**Issue by GeomKid** [interactions-py/interactions.py#549]
**Describe the bug**
Please give us an in-depth description of the bug you're having.
When Loading cogs with the new version only the last file gets loaded

These are the steps I took in order to produce this bug, which should be able to be reproduced for everyone else as well.

```
bot = interactions.Client(
    token=#redacted token,)
bot.rules = []

for filename in os.listdir("./newcogs_copy"):
    if filename.endswith(".py"):
        bot.load(f"newcogs_copy.{filename[:-3]}")


@bot.event
async def on_ready():
    print(f"Ready!Login as {bot.me.name}")
```
Files in ./newcogs_copy
test1.py (Command test1)
test2.py (Command Test2)

Only test 2 is loaded and usable 
**What's normally expected**
All commands can be seen
**What actually happened**
Instead,  only the last cog commands get loaded
```
```

**Versions**
- discord interaction 4.1.0 unstable

**Comment by i0bs** [comment]
Issues are meant for either stable or release for us right now. Please report this in our server
