### ISSUE TITLE
[MISC] How to send an image file with slash command in V4?

### ISSUE THREAD

**Issue by NLKNguyen** [interactions-py/interactions.py#560]
Hi,

It looked like the method of embedding files was changed a few times, so how to do that with the latest version? 
Can you please provide an example showing how to attach a local file (PNG) into a response for a slash command interaction? 

Thanks

**Comment by i0bs** [comment]
If you're talking about uploading a file to Discord, it's not possible yet. You *are* able to send, attachments, however.

**Comment by i0bs** [comment]
I'll be closing this Issue. If you still have any remaining questions, please consider joining our support server.
