### ISSUE TITLE
[BUG] NoneType exception when using extension_autocomplete and disable_sync=True

### ISSUE THREAD

**Issue by V3ntus** [interactions-py/interactions.py#582]
### Describe the bug.

When attempting to register an autocomplete callback inside an extension with `disable_sync=True`, a NoneType exception occurs

### List the steps.

Define a command with autocomplete option and an autocomplete callback in an extension:
```py
@interactions.extension_command(
    name="testauto",
    description="test autocomplete",
    options=[
        Option(
            type=OptionType.STRING,
            name="message",
            description="test",
            autocomplete=True
        )
    ]
)
async def testauto_cmd(self, ctx: interactions.CommandContext, message: str = None):
    await ctx.send("You sent: {}".format(message))

@interactions.extension_autocomplete(command="test", name="message")
async def do_autocomplete(self, ctx):
    await ctx.populate([
        Choice(
            name="One",
            value="1"
        ),
        Choice(
            name="Two",
            value="2"
        )
    ])
```

### What you expected.

To register a callback successfully

### What you saw.

```py
Traceback (most recent call last):
  File "/Users/ventus/GitRepos/discord-py-interactions_boilerplate/main.py", line 75, in <module>
    client.load("cogs." + cog)
  File "/Users/ventus/GitRepos/discord-py-interactions_boilerplate/env/lib/python3.9/site-packages/interactions/client.py", line 937, in load
    raise error from error
  File "/Users/ventus/GitRepos/discord-py-interactions_boilerplate/env/lib/python3.9/site-packages/interactions/client.py", line 933, in load
    extension = setup(self, *args, **kwargs)
  File "/Users/ventus/GitRepos/discord-py-interactions_boilerplate/cogs/helloworld.py", line 188, in setup
    HelloWorld(client)
  File "/Users/ventus/GitRepos/discord-py-interactions_boilerplate/env/lib/python3.9/site-packages/interactions/client.py", line 1143, in __new__
    func = client.autocomplete(*args, **kwargs)(func)
  File "/Users/ventus/GitRepos/discord-py-interactions_boilerplate/env/lib/python3.9/site-packages/interactions/client.py", line 850, in autocomplete
    _command: Union[Snowflake, int] = int(_command_obj.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by V3ntus** [comment]
In #477, I implemented logic to append the scope whenever the `Client.command` decorator was called, to an internal set inside `Client`. This allows autocomplete to view if a command is limited to a scope and can fetch that command successfully. The `_scope` set does not seem to get populated in `extension_command`, therefore `_command_obj` never gets populated with ApplicationCommand data

Will try to submit a PR with fixes

**Comment by V3ntus** [comment]
Here: https://github.com/interactions-py/library/blob/6cc6333a26d9686a900c2119f94ef14f5e7503bc/interactions/client.py#L832

Inverting the `self._automate_sync` check fixes this

**Comment by i0bs** [comment]
> Here:
> 
> https://github.com/interactions-py/library/blob/6cc6333a26d9686a900c2119f94ef14f5e7503bc/interactions/client.py#L832
> 
> Inverting the `self._automate_sync` check fixes this

As in `if not self._automate_sync or ...` ?

**Comment by V3ntus** [comment]
> As in `if not self._automate_sync or ...` ?

Yes, I'm pretty certain that was what I used to resolve in my testing
