### ISSUE TITLE
[BUG] leave_guild throwing an error

### ISSUE THREAD

**Issue by blackvillain** [interactions-py/interactions.py#598]
### Describe the bug.

When I try to use the method `leave_guild`, the library throws an error:

```
DEBUG:http:RETURN 400: {
    "code": 50109,
    "message": "The request body contains invalid JSON."
}
```

### List the steps.

1. Create a Client object
2. make a list of all guilds the bot is on
3. call `client._http.leave_guild(guild_id=guild_id)`
4. observe nothing happening but an error inside of the debug console

### What you expected.

The bot to leave all guilds hes on

### What you saw.

Instead, I received this error given from my Python terminal:
```
DEBUG:http:RETURN 400: {
    "code": 50109,
    "message": "The request body contains invalid JSON."
}
```

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
After this was discussed in the support server, we've determined that the issue therein lies with us trying to send a JSON body for an endpoint that does not require it. We'll be flagging as an known bug.
