### ISSUE TITLE
[BUG] The user model does not currently contain support for a banner_color attribute

### ISSUE THREAD

**Issue by r-warfield** [interactions-py/interactions.py#607]
### Describe the bug.

When creating a User model, you get this message:
`WARNING:mixin:Attribute banner_color is missing from the User data model, skipping.`

Ideally, there would be an attribute for this.

### List the steps.

1. Start the bot
2. Turn on logging
3. Use `bot._http.get_user()` to get the user dict from Discord
4. Attempt to use that dict to create an `interactions.User` object

### What you expected.

I expect no error and a banner_color attribute to be created

### What you saw.

Instead, I received this warning from my Python terminal:
```
WARNING:mixin:Attribute banner_color is missing from the User data model, skipping.

```

### What version of the library did you use?

stable

### Version specification

4.1.1b1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
More of a general edge case where, due to being both a. undocumented and b. simply missing, it's a feature request, but we'll be flagging it.
