### ISSUE TITLE
[REQUEST] Remove the `Format` class.

### ISSUE THREAD

**Issue by i0bs** [interactions-py/interactions.py#608]
### Describe the feature.

To be real, we don't ever implement this class elsewhere. It was originally designed as a way to dynamically format string inputs for what we now have implemented as `mention` property methods, as well as time formatting. However, since these have been PR'd, we don't touch it anymore.

This request is to remove the class in all due to its irrelevance.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by FayeDel** [comment]
Closing as the associated PR has been merged.
