### ISSUE TITLE
[REQUEST] Add a basic `Color` object.

### ISSUE THREAD

**Issue by i0bs** [interactions-py/interactions.py#610]
### Describe the feature.

People may want to be able to easily call upon colors. Since it should be at least an accepted concept, I am wanting to add a basic `Color` object that includes the official branding colors. Please note that other colors that are custom-defined are ideally frowned on for this idea since the core library is about making implementations strict to what Discord offer, which we can argue debatably with the branding colors.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by FayeDel** [comment]
Closing issue as the associated PR has been merged (and not autoclosed).
