### ISSUE TITLE
[REQUEST] Move to Furo, a better Sphinx theme.

### ISSUE THREAD

**Issue by i0bs** [interactions-py/interactions.py#615]
### Describe the feature.

While Karma has done a great job for us so far, it's caused numerous issues:

- Lack of theme picker (dark/light)
- Inability to view source code
- Search bar poorly functional with automodule usage
- Current theme has colors uncomfortable to the eye
- Inability to permalink to a method, class or attr
- Cannot preview attr/arg types when hovering (hover refs) 

The goal of Furo is to eliminate all of these issues, which you can view an example of here: https://sphinx-themes.org/sample-sites/furo/

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by FayeDel** [comment]
This is closed because #938 is merged.
