### ISSUE TITLE
[BUG] Members cache does not function as intended

### ISSUE THREAD

**Issue by AstreaTSS** [interactions-py/interactions.py#617]
### Describe the bug.

`interactions` currently has a (somewhat internal) cache for various items like users, roles, channels, etc. It also has one for members, too.

This is obviously a nice feature for developers; however, it does not function correctly. It assumes that a member's ID *alone* can be used as the key for a member. However, a member with the same ID from one guild *is not* the same as a member with the same ID from another guild.

(To simplify that: if you're in two guilds, in the API, despite having the same user ID everywhere, the "you" in each guild is different with differing nicknames, roles, etc., right? The cache forgot about that.)

### List the steps.

1. Fetch a member with a set ID from a guild, guild X.
2. Use the cache to get a member with the same ID as the above from another guild, guild Y.

### What you expected.

In this case, nothing should be returned as we never fetched the member from guild Y.

### What you saw.

The member object for guild X.

### What version of the library did you use?

`release`

### Version specification

4.1.0, though this hasn't been fixed in unstable either.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
An issue we've acknowledged about this is similar to our interactions storage in the cache where numerous items cannot be shared under the same ID key. It's an unfortunate edge case that is planned to be addressed alongside implementing TTL, however, it's been low prior'd.

Nonetheless we'll be flagging this and acknowledging as a bug.

**Comment by i0bs** [comment]
See #909 for information. Closing as this affects the prior functionality.
