### ISSUE TITLE
[REQUEST] Expand Snowflake model attributes

### ISSUE THREAD

**Issue by FayeDel** [interactions-py/interactions.py#622]
### Describe the feature.

Currently, all the attributes (not counting with `@property`) are `hash()`/`int()`/`str()`.
I've left equality Snowflake model checking alongside greater/less than (with and without equal to) up for debate since v4.0 beta was released, so I'm raising the respective issue for feedback if this needs to be implemented (This isn't per API schema, hence the lack of implementation, but I think a lot of the community would appreciate the extension.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Catalyst4222** [comment]
I believe that `__eq__` is needed to be able to compare the same id from multiple sources (like message id vs components origin message id)
`__gt__` and `__lt__` probably have fewer use cases, but I don't see any reason not to add them
