### ISSUE TITLE
[BUG] Random gateway closing

### ISSUE THREAD

**Issue by FayeDel** [interactions-py/interactions.py#623]
### Describe the bug.

This is a somewhat well-known gateway bug, essentially the Gateway connection randomly closes at an unprecedented time. Compared to pre v4.1, which has displayed an indefinite heartbeat traceback at best, this error is reached on average far longer than pre 4.1, which is good, but there's no logged cause for why it's failing.

See https://canary.discord.com/channels/789032594456576001/801461008865951784/950461585560850452 for details.

### List the steps.

1. Run the bot, optionally with `logging.DEBUG`.
2. Leave it running forever.

### What you expected.

The connection should keep running/resuming as expected.

### What you saw.

There's no traceback, it just stops after either `HEARTBEAT`, `HEARTBEAT_ACK`, or before a heartbeat signal at normal event logs.

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by lajonss** [comment]
Docker reports ~100% CPU usage.

Pyrasite stacks dump
[bot1.docker.log](https://github.com/interactions-py/library/files/8249813/bot1.docker.log)

Pyrasite inspection:
```
>>> sys._current_frames()[140713552049984].f_locals
{'self': <interactions.api.gateway.WebSocketClient object at 0x7ffa6b7cc300>, 'packet': WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None)}
```

Could it be that gateway.WebSocketClient's self._closed is False while aiohttp ws connection is closed?

I'll try running my bot with this patch:
```python
            while not self._closed:
                stream = await self.__receive_packet_stream
                self._closed = self._client.closed
```
https://github.com/interactions-py/library/blob/stable/interactions/api/gateway.py#L197

update: My container was restarted about 14h ago (it was running for about 1d 16h). I can't see any relevant error or debug messages in logs.
update 2: The bot crashed again with no information in logs. This time it took 1d 13h.

**Comment by i0bs** [comment]
This has been driving me fucking insane. I've tried almost every way imaginable to ensure that our `_closed` attribute constantly reflects the client's closed state, but I keep on running into this. I've found some issues similar to this, however, with `_client` suddenly becoming a `NoneType` when we call `__receive_packet_stream`. This *might* be unrelated but also worth looking into.

**Comment by r-warfield** [comment]
might have fixed it, may pr soon

**Comment by V3ntus** [comment]
Reopen requested
