### ISSUE TITLE
[REQUEST] Detailed error exceptions

### ISSUE THREAD

**Issue by i0bs** [interactions-py/interactions.py#627]
### Describe the feature.

Developers are having a hard time with figuring out what is breaking with our library. *Really* hard times. This request is focused on finding a solution to not only parsing and cresting a new error formatter, but using proper error exception types for client specific issues. 

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
we neeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddd this

**Comment by i0bs** [comment]
Moreover: we meant to code this for launch in 4.1, but I made the last minute decision nearing our deadline to do it post-launch. There's egg on my face on it, and the next release I wish to make this ensured.

**Comment by sillyElvy** [comment]
Are you going to do this? If not, please give me information about how it should be working

**Comment by i0bs** [comment]
I'll put this on my todo list after some other things
