### ISSUE TITLE
[REQUEST] Add a guilds property to Client

### ISSUE THREAD

**Issue by Jalancar** [interactions-py/interactions.py#631]
### Describe the feature.

There needs to be an easier way to access the guilds that the bot is in, especially in a task loop. I would like a guilds property added to the Client class that would have return all of the bot's guilds.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by FayeDel** [comment]
Closing issue as the associated PR has been merged to unstable.
