### ISSUE TITLE
[REQUEST] File Upload Support

### ISSUE THREAD

**Issue by kbots-tech** [interactions-py/interactions.py#636]
### Describe the feature.

My bot I'm reworking to use this library sends images and files with embeds specific to command calls, being able to upload/send files a la the discord.py method would be really helpful. Eg:

```py
embed=discord.Embed(title=f"Your Character Sheet for {self.fields[ctx.author.id][0]}", color=0xde2939),
            file=discord.File(output))
```

if this could be added either as an extension or part of the core library that'd be super helpful.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
This is planned as a core feature as the Web API allow this to work in parallel to attachments.
