### ISSUE TITLE
[MISC] Extra quote in example in Quickstart page

### ISSUE THREAD

**Issue by shivrm** [interactions-py/interactions.py#643]
### Describe the bug.

In the Quickstart page, the first example under the [Creating and sending Components](https://discord-py-slash-command.readthedocs.io/en/latest/quickstart.html#creating-and-sending-components) section has an extra quote, which causes a `SyntaxError`.

### List the steps.

1. Navigate to the [Creating and sending Components](https://discord-py-slash-command.readthedocs.io/en/latest/quickstart.html#creating-and-sending-components) section
2. Copy the code in the first example and paste it in a Python file
3. Create a bot instance using `bot = interactions.Client(token="your_secret_bot_token")`
4. Replace `your_secret_bot_token` with your bot token and `the_id_of_your_guild` with your guild ID
5. Run the code with `python <path_to_file>`
6. Observe the output shown in the console

### What you expected.

The code works without error

### What you saw.

Instead of running without errors, Python shows the following error:
```
  File "<file_path>", line 15
    @bot.component("hello"")

SyntaxError: EOL while scanning string literal
```

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
Closing in favor of #642
