### ISSUE TITLE
[BUG] change_presence Not Working

### ISSUE THREAD

**Issue by JamesTesting888** [interactions-py/interactions.py#654]
### Describe the bug.

- No error and no logging
- Talked to Delta, she/he said will have a look

### List the steps.

await bot.change_presence(
        presence=interactions.ClientPresence(
            status=interactions.StatusType.ONLINE,
            activities=[
                interactions.PresenceActivity(
                    name="/support",
                    type=interactions.PresenceActivityType.GAME
                )
            ]
        )
    )

### What you expected.

Change the presence of the bot to "/support"

### What you saw.

Nothing

### What version of the library did you use?

unstable

### Version specification

4.1.1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by v1r** [comment]
Same issue here, it looks like the change_presence is not exposed anywhere.

**Comment by i0bs** [comment]
May you please specify which beta version you're on for 4.1.1?

**Comment by FayeDel** [comment]
Hiya!
I'm making a PR for this soon, I have a local implementation (currently) that fixes this ^^ :)

**Comment by JamesTesting888** [comment]
iirc, it is 4.1.1 b

**Comment by FayeDel** [comment]
Closing this as the associated PR fixes them.
