### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dugaldp** [interactions-py/interactions.py#664]
### Describe the bug.

When trying to return a list of members in a guild using:
```
for member in bot.guilds().members:
        print(member)
```
An error was given

### List the steps.

$ pip install -U git+https://github.com/interactions-py/library@unstable
Import interactions module
Created a slash command with the code above

### What you expected.

I expected the terminal to print out a list of members in the guild 

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
    for member in bot.guilds().members:
  File "/opt/homebrew/lib/python3.9/site-packages/interactions/client.py", line 105, in guilds
    return [Guild(**_, _client=self._http) for _ in self._http.cache.self_guilds.view]
  File "/opt/homebrew/lib/python3.9/site-packages/interactions/client.py", line 105, in <listcomp>
    return [Guild(**_, _client=self._http) for _ in self._http.cache.self_guilds.view]
TypeError: interactions.api.models.guild.Guild() got multiple values for keyword argument '_client'
```

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
This Issue is really hard to understand. I get what it means, and we've appropriated a fix for this. Next time, please format your issues to be easier to read.
