### ISSUE TITLE
[BUG] The Unstable Syncing of Guild Commands

### ISSUE THREAD

**Issue by GeomKid** [interactions-py/interactions.py#667]
### Describe the bug.

When the bot is started with `disable_sync=False` the guild commands were not synced correctly for example :
```py
@bot.command(
    scope=["guild1_id", "guild2_id"],
    name="test1",
    description="Test1",
)
async def math(self, ctx: ComponentContext):
    return await ctx.send("test1")


@bot.command(
    scope=["guild1_id", "guild2_id"],
    name="test2",
    description="Test2",)
async def math(self, ctx: ComponentContext):
    await ctx.defer()
    await ctx.send("Test2")
```
guild 1 will have test1 and test 2 
but 
guild 2 will only have test 2
This also happens inside extensions

### List the steps.

1. Import module
2. Create guild command
3. Start Bot
4. Wait till the bot started completely
5. Go to Guild1 and Guild 2 to see the slash commands by trying to use them

### What you expected.

Bith Guild1 and Guild 2 will have test1 and test 2

### What you saw.

guild 1 will have test1 and test 2 
but 
guild 2 will only have test 2

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Toricane** [comment]
Aren't you overwriting the first function because both of your functions have the same name (`math`)?

**Comment by FayeDel** [comment]
Closing as the PR associated has been merged. ^^

While the statement you said Toricane is true, I think it's an accident and purely unintentional (It's an example to be fair)
