### ISSUE TITLE
[REQUEST] Examples in documentation

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#671]
### Describe the feature.

Implementation of examples per function for a better example of the usage of the function 

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
In accordance to #615 , we're including better examples in our documentation website rewrite. Additionally, I've begun working on adding some library-level examples as of commit [`5bbf0ab`](https://github.com/interactions-py/library/commit/5bbf0abd619f77b4af805824c5399128ea503f9d). I will be closing this Issue to reflect these.
