### ISSUE TITLE
[REQUEST] Adding a section describing how Client event can be used

### ISSUE THREAD

**Issue by B1ue-Dev** [interactions-py/interactions.py#678]
### Describe the feature.

I think since the library itself does support Discord gateway events, there should be a dedicated section for examples about how these events can be used in production, such as making a simple example about ``on_message_create`` or things like that.

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
This is planned in accordance to the Furo docs PR.

**Comment by B1ue-Dev** [comment]
Still waiting...

**Comment by i0bs** [comment]
It's coming in the new docs, don't fret. 😅

**Comment by B1ue-Dev** [comment]
(It's been 2 months since that last comment lol.)

**Comment by sillyElvy** [comment]
> (It's been 2 months since that last comment lol.)

I'll take I try on it

**Comment by B1ue-Dev** [comment]
Looking good now.
