### ISSUE TITLE
[REQUEST] Change how event data is built to fix bugs and remove some redundancy

### ISSUE THREAD

**Issue by r-warfield** [interactions-py/interactions.py#681]
### Describe the feature.

#487 

although we arent 100% *how* the best way of doing it yet, it would be good to refactor how event data is built to remove bugs like `An error occured dispatching message_reaction_remove_all: module 'interactions' has no attribute 'MessageReactionRemove'` due to previously relying on `gw.py` for all the event models, even if their names don't make much sense (`GuildMember` being used for Guild Member events instead of the member itself, and yet having seemingly all `Member` methods). this will definitly require some gateway editing

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by r-warfield** [comment]
ideas changed + waiting on cache rewrite :(

**Comment by i0bs** [comment]
Cache rewrite is pending approval, see #909 .

**Comment by Catalyst4222** [comment]
The cache rewrite has been finished, and with it a new way of handling the data sent in events. Is this issue still applicable?

**Comment by r-warfield** [comment]
No
I don't think so.
