### ISSUE TITLE
[BUG] Phantom `timestamp` being added to Embeds at HTTP POST response

### ISSUE THREAD

**Issue by V3ntus** [interactions-py/interactions.py#684]
### Describe the bug.

Users are reporting a `timestamp` field is being added onto embeds when it reaches Discord, even though they did not set `timestamp` to anything

### List the steps.

Create a simple embed and send it normally

### What you expected.

No timestamp

### What you saw.

```json
DEBUG:http:POST: https://discord.com/api/v10/interactions/.../.../callback: {'json': {'type': 4, 'data': {'content': '', 'tts': False, 'embeds': [..., 'timestamp': '2022-03-29T19:21:06.721804'}],
```

Oddly this is being added during a mixin iteration

Here: https://github.com/interactions-py/library/blob/711ae0ff020ca91f9102f966581ee47ff1c9725a/interactions/api/models/message.py#L1032

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by V3ntus** [comment]
*Possibly* linked with #683 in some way? Maybe?

Edit: probably not

**Comment by sillyElvy** [comment]
hrm

if you check data before and after hit, one has timestamp set to none, in the other its not present

that could be the issue, since I remove `None` values from the dicts..

**Comment by V3ntus** [comment]
Not exactly sure what you mean, sorry

Considering this code in `api/models/message.py`, if `timestamp` is `None`, it adds `utcnow`, it doesn't do any sort of removing
```py
def __init__(self, **kwargs):
    super().__init__(**kwargs)
    self.timestamp = (
        datetime.fromisoformat(self._json.get("timestamp"))
        if self._json.get("timestamp")
        else datetime.utcnow()
    )
```

**Comment by sillyElvy** [comment]
![grafik](https://user-images.githubusercontent.com/88881326/160694657-cfe74435-e3d2-447f-8693-76116585af15.png)

i remove `None` values, maybe that's the issue there?

**Comment by V3ntus** [comment]
Oh yeah this happens without the presence of `timestamp` in my `Embed` object too. I was testing to see if `timestamp=None` would do anything different

**Comment by i0bs** [comment]
Hey! We've fixed this on our unstable branch and will be closing this now. 😄
