### ISSUE TITLE
ctx.send(embed=)

### ISSUE THREAD

**Issue by Waspyeh** [interactions-py/interactions.py#7]
Why is embed, embeds?

**Comment by TurnrDev** [comment]
Probably to remain consistent with discord.py

**Comment by eunwoo1104** [comment]
Since slash command allows us to send up to 10 embeds at once.

**Comment by Waspyeh** [comment]
> Since slash command allows us to send up to 10 embeds at once.

Woah seriously?

**Comment by VCJames** [comment]
> > Since slash command allows us to send up to 10 embeds at once.
> 
> Woah seriously?

Yes. A little disappointed I don't see anything so far similar to Teams cards or the `/giphy` suggestion/autocompletion. The latter of which *does* offer you 10 GIFs but.. I digress... tested:

![image](https://user-images.githubusercontent.com/15795500/102449688-d30eb200-4002-11eb-8fc2-d8ba3face644.png)

![image](https://user-images.githubusercontent.com/15795500/102449699-d9049300-4002-11eb-90d7-8abf88207716.png)
