### ISSUE TITLE
[BUG] get_all_emojis has become get_all_emoji

### ISSUE THREAD

**Issue by JamesTesting888** [interactions-py/interactions.py#704]
### Describe the bug.

In PyPI is get_all_emojis and it was get_all_emojis. Recently, the s in get_all_emojis is deleted. 

### List the steps.

Just do:
for i in await some_guild_obj.get_all_emojis()

### What you expected.

Actually getting all emojis.

### What you saw.

No attribute

### What version of the library did you use?

unstable

### Version specification

4.1.1 (newest one)

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
This is intended for the helper method being named the same as the http method.

**Comment by Catalyst4222** [comment]
`get_all_emojis` has indeed been renamed to `get_all_emoji`, but it is still `get_all_emojis` in the pyi file, which was likely the source of confusion

**Comment by sillyElvy** [comment]
> `get_all_emojis` has indeed been renamed to `get_all_emoji`, but it is still `get_all_emojis` in the pyi file, which was likely the source of confusion 

Noted, a fix will be pushed soon
