### ISSUE TITLE
[BUG] Inserting a string value as event name into ``@event``  is not possible

### ISSUE THREAD

**Issue by sillyElvy** [interactions-py/interactions.py#717]
### Describe the bug.

Previously it was possible to do so, now it will result in an attribute error

### List the steps.

-

### What you expected.

It to be working and registering the event properly

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "A:\Amogus\Python\interactions-bot\main.py", line 6
    raise SussyBaka("your code doesn't work, silly!")
          ^

SussyBaka: your code doesn't work, silly!
```

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
please tell me you're not actually having `SussyBaka` as an error in your issue

**Comment by sillyElvy** [comment]
> please tell me you're not actually having `SussyBaka` as an error in your issue

I do, I modified the whole language to exactly produce that error /s

No I just forgot to update it
