### ISSUE TITLE
[BUG] Latest version on raspberry pi is 3.0.2

### ISSUE THREAD

**Issue by HeyItsJustFelix** [interactions-py/interactions.py#721]
### Describe the bug.

I am trying to run the discord bot on a raspberry pi and when I run pip install discord-py-interactions, it reports "Could not find a version that satisfies the requirement discord-py-interactions (from versions: ) No matching distribution found for discord-py-interactions."
![image](https://user-images.githubusercontent.com/82989883/162597398-3d9131dd-ed26-4f1f-a0c3-636e0267b5a0.png)

I decided to run pip3 install discord-py-interactions and it installed a version but it is an outdated version being 3.0.2, which I am afraid will break things that work on windows
![image](https://user-images.githubusercontent.com/82989883/162597431-e2fbd1b2-c9b1-410e-bcdc-68bd9c34a3d6.png)

### List the steps.

1. On a pi, run pip install -U discord-py-interactions
2. On a pi, run pip3 install discord-py-interactions

### What you expected.

I was expecting the latest version of discord-py-interactions to be installed

### What you saw.

I recieved an error when using pip and it installed an outdated version when running pip3

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by V3ntus** [comment]
Suggest joining the Discord for prompt responses. ~~What Python version are you on?~~

Oh I see, Python 3.7.

**Comment by HeyItsJustFelix** [comment]
I didn't think of joining the discord, I appreciate it and will join shortly.

**Comment by HeyItsJustFelix** [comment]
V3ntus helped me install python 3.10.4 and it now is installing properly!
