### ISSUE TITLE
[BUG][REQUEST] Discord-py-interactions won't get installed on Termux

### ISSUE THREAD

**Issue by ghost** [interactions-py/interactions.py#724]
### Describe the bug.

Discord-py-interactions can't be installed because orjson needs maturin, which needs rust, which needs rustup.

This probably occurs because rust cargo build isn't available for termux, since there's no "aarch64-linux-android" on rustup. only rust can be installed, not cargo.

Is there any way to install discord-py-interactions without orjson? with a replacement like ujson? 

if not, i suggest you guys to replace it with ujson, since it can be successfully installed on most plataforms and it is fast as orjson

### List the steps.

`pip install discord-py-interactions`
(you'll get a orjson failure)

`pip install orjson`
_(orjson cannot be installed without maturin.)_

`pip install maturin `
_(you'll get a rust error. now try to install rust)_

`pkg install rust`
_(you'll successfully install it. now try installing maturin)_

`pip install maturin`
_(oops, cargo build is missing, try to install rustup)_

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
_error: target 'aarch64-linux-android' not found in channel._

### What you expected.

discord-py-interactions should be successfully installed. i've heard that there's a way to fallback from orjson to json, but i don't know how.

https://github.com/interactions-py/library/issues/424#issuecomment-1011430006

### What you saw.

```
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for maturin
Failed to build maturin
ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
```
pip install discord-py-interactions --no-deps
pip install -U aiohttp
```

This should work fine

**Comment by Kapideveloper** [comment]
> ```
> pip install discord-py-interactions --no-deps
> pip install -U aiohttp
> ```
> 
> This should work fine

i'm

**Comment by ghost** [comment]
> ```
> pip install discord-py-interactions --no-deps
> pip install -U aiohttp
> ```
> 
> This should work fine

Thanks, i'm gonna try
(closed issue due to missclick xD. it's reopened now)

**Comment by ghost** [comment]
> 

Didn't work.
Used the code from documentation for test:
```
import interactions

token = "CENSORED"

bot = interactions.Client(token=token)

@bot.command(
    name="my_first_command",
    description="This is the first command I made!",
    scope=the_id_of_your_guild,
)
async def my_first_command(ctx: interactions.CommandContext):
    await ctx.send("Hi there!")

bot.start()
```
![Screenshot_20220410-131213_Termux](https://user-images.githubusercontent.com/88977720/162628907-88ac7acc-1b5b-4d9b-82c1-176b26852d0d.png)

**Comment by sillyElvy** [comment]
Oh it did work, it got installed as you can see xd

Check your token/regenerate it, maybe that fixes it

Also you could join the [discord server](https://discord.gg/interactions) for help

**Comment by i0bs** [comment]
make sure your `token` is being read correctly. This type error most often occurs when the token is invalid in some way, shape or form.

**Comment by ghost** [comment]
> make sure your `token` is being read correctly. This type error most often occurs when the token is invalid in some way, shape or form.

Stills not working, even after regenerating token

**Comment by i0bs** [comment]
What means are you using to put the token in? If you're using something like `dotenv`, you need to make sure that it's actually *reading* the file. Otherwise, if you're putting the token in raw, please consult for more about this in our support server please

**Comment by ghost** [comment]
> What means are you using to put the token in? If you're using something like `dotenv`, you need to make sure that it's actually _reading_ the file. Otherwise, if you're putting the token in raw, please consult for more about this in our support server please

I was putting the token in raw.
i'm gonna make a thread in help channel

**Comment by ghost** [comment]
**Thanks to @EdVraz and @goverfl0w for providing a solution for this issue**

if someone needs to install the library on termux, try the following command to ignore orjson and successfully install the lib.

```
pip uninstall discord-py-interactions
pip install aiohttp==3.8.1
pip install colorama
pip install git+https://github.com/interactions-py/library.git@4.1.1-rc.1 --no-deps
```
