### ISSUE TITLE
[BUG] Can't use default emojis in SelectOption

### ISSUE THREAD

**Issue by muckee** [interactions-py/interactions.py#727]
### Describe the bug.

Not sure if this is a bug or a feature request.

Currently I retrieve random emojis from emojipedia and pass them as arguments to the 'emoji' parameter when I create a new SelectOption, though I have tried hardcoding a single emoji to test and I get the same issue.

I know that I'm supposed to pass an Emoji object with a _json attribute to the 'emoji' parameter, but if I'm using default emojis then I'm expected to copy and paste symbols or use the standard colon notation with a dictionary of emoji names.

Maybe I've just misunderstood something but is there some way using only the interactions library that I can create an Emoji object from a string like '😃' (or any other format where I start without an ID), or is there a workaround to implement SelectOption and just use an emoji as a string like that?

### List the steps.

For simplicity, I've only included a hardcoded version of the data I would like to use (or something equivalent) when creating a SelectOption object.

```
option = {
	'label': emoji_name,
	'value': x,
	'emoji': '😃'
}
```

### What you expected.

It should be possible to pass emojis directly to SelectObject options should yield a result, or provide some hint on constructing an Emoji object. Or, it should be possible to retrieve the standard emojis using the interactions library natively.

### What you saw.

Currently it only appears that a SelectOption can be created natively by relying on custom emojis or using an external request/library to query the discord API

### What version of the library did you use?

release

### Version specification

4.1.1-rc (also tested on stable version, yields slightly different result. same issue)

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
Try using `SelectOption(...,, emoji=interactions.Emoji(name="your_emoji_here")`.

Also, you might want to check out our [discord support server](https://discord.gg/interactions)

**Comment by i0bs** [comment]
It'd *probably* help if you gave us a code example of what you were trying to originally do with `Emoji()`. The correct functionality for partial emoji objects in a select menu option is this

```py
interactions.SelectMenu(
  options=[
    interactions.SelectOption(
      label="my label",
      value="test1",
      emoji=interactions.Emoji(id=None, name="😊", animated=False)
    )
  ]
)
```

Note that when inputting an emoji for a select menu option, `id` must be `None` and `animated` as `False` if it's a unicode. Otherwise, you populate these fields appropriately.

**Comment by muckee** [comment]
Thanks I just hadn't realised how to create a partial Emoji!
