### ISSUE TITLE
50035 Invalid Form Body upon basically anything register-related

### ISSUE THREAD

**Issue by pixelflowxyz** [interactions-py/interactions.py#73]
Hi all, hope all is well and you are safe.

I'm attempting to test my bot with discord-py-slash-command, but I'm getting a `RequestFailure: Request failed with resp: 400 | {"code": 50035, "errors": {"application_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "Value \"<built-in function id>\" is not snowflake."}]}}, "message": "Invalid Form Body"}` when I try to `discord_slash.utils.manage_commands.get_all_commands`, or when I try to `manage_commands.add_slash_command`.

I'm only using example code from the docs and in the issues while troubleshooting, so I'm really confused about what's happening!
I'm running this:
```
    def __init__(self, bot):
        if not hasattr(bot, "slash"):
            # Creates new SlashCommand instance to bot if bot doesn't have.
            bot.slash = SlashCommand(bot, override_type=True, auto_register=True)
        self.bot = bot
        self.bot.slash.get_cog_commands(self)

    def cog_unload(self):
        self.bot.slash.remove_cog_commands(self)

    @cog_ext.cog_slash(name="ping")
    async def ping(self, ctx: SlashContext):
        await ctx.send(content="Pong!")

def setup(bot):
    bot.add_cog(Slash(bot))
```

Any help would be extremely appreciated!

Thanks,
-Dan

Edit: It's almost definitely my own incompetence and stupidly causing something!

**Comment by eunwoo1104** [comment]
> ... when I try to `discord_slash.utils.manage_commands.get_all_commands`, or when I try to `manage_commands.add_slash_command`.

I think it might be the problem of passed args at those functions, can I see how did you use that? (Hide the token when you post it of course.)

**Comment by spinnerich** [comment]
I'm pretty sure you are not passing `bot.user.id` to the functions.
