### ISSUE TITLE
[BUG] .pyi files are not included when building

### ISSUE THREAD

**Issue by AstreaTSS** [interactions-py/interactions.py#730]
### Describe the bug.

Pretty much what it says.

`.pyi` files have been a *pain* for many users, and this may be the reason why. There's nothing in `setup.py` to include them - they *only* include `.py` files as of right now.

### List the steps.

1. Clone the project and open a terminal in the project folder.
2. Use `python setup.py sdist bdist_wheel` (or `python3` on Linux).
3. Check the `.tar.gz` in the `dist` folder that results from it. `.whl`, the file Python actually uses for installations, should have the same/similar files too anywho.

### What you expected.

`.pyi` files to be in the resulting `.tar.gz`, which allows for them to be used for typehinting when installing from a build.

### What you saw.

A lack of `.pyi` files.

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
I thought we fixed it

**Comment by sillyElvy** [comment]
This is known for atleast 2 months

**Comment by AstreaTSS** [comment]
Nope. `unstable` produces the same results.
