### ISSUE TITLE
[BUG] Incorrect typehintings for HTTPClient

### ISSUE THREAD

**Issue by AstreaTSS** [interactions-py/interactions.py#734]
### Describe the bug.

The `.pyi` for the `client` in `interactions/api/http` has incorrect typehintings for `HTTPClient`, and most of the HTTP methods will not be typehinted because of it.

This is likely due to the fact that in the `.pyi` file, the `HTTPClient` *does not* inherit from the request classes, unlike in the regular file. This means Python has no clue that `HTTPClient` even has those methods.

 While the HTTP client *is* an underscored attribute, it is used so often as of right now that it is worth having accurate typehintings. It's also nice when developing the library.

### List the steps.

Do something like this in pretty much any modern-day text editor with type checking support. I'll be using Pylance since I use Visual Studio Code:

```python
client = interactions.Client(...)

async def func():
    await client._http.get_member(GUILD_ID, MEMBER_ID)
```

### What you expected.

For the `get_member` function to be typehinted correctly.

### What you saw.

Pylance reports:
```
Cannot access member "get_member" for type "HTTPClient"
  Member "get_member" is unknown
```

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
![image](https://user-images.githubusercontent.com/41456914/163704209-81a48865-8b85-46b6-a3ab-3dae2f04d9d9.png)

Judging off of the poll ran going over the type hinting debacle, I'm not sure if this issue should be considered with fixing `.pyi` files, or ditching them in favor of `typing.Protocol` as voted out by the community.

**Comment by AstreaTSS** [comment]
> ![image](https://user-images.githubusercontent.com/41456914/163704209-81a48865-8b85-46b6-a3ab-3dae2f04d9d9.png)
> 
> Judging off of the poll ran going over the type hinting debacle, I'm not sure if this issue should be considered with fixing `.pyi` files, or ditching them in favor of `typing.Protocol` as voted out by the community.

For a minor issue that can be fixed pretty simply, I'd argue the former makes sense for now. The latter will require quite a bit of work and will need to be addressed separately, but just because that was voted for doesn't mean we immediately drop support for `.pyi` files.
