### ISSUE TITLE
[BUG] get_channel_messages does not sanity check the request data 

### ISSUE THREAD

**Issue by Wizzerinus** [interactions-py/interactions.py#769]
### Describe the bug.

so, apparently if you run get_channel_messages on a channel that does not exist, discord sends you a dictionary with 
```{'message': 'Unknown Channel', 'code': 10003}```

which makes sense, but then the code tries to iterate over this dictionary and fails because 'message' has no attribute get.

### List the steps.

1. Run `bot._http.get_channel_messages(12345)` (basically any number which doesn't correspond to a channel)
2. Observe the attribute error

### What you expected.

When a channel is not present, I expected either an empty list, or a error other than AttributeError (i.e. a custom ChannelNotPresentError or whatever)

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
  File "discordbot/bot_global.py", line 197, in get_channel_messages
    for res in await self._http.get_channel_messages(channel_id=channel, limit=limit)
  File "discord-py-interactions/interactions/api/http/channel.py", line 85, in get_channel_messages
    if message.get("id"):
AttributeError: 'str' object has no attribute 'get'
```

### What version of the library did you use?

unstable

### Version specification

4.1.1rc1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by FayeDel** [comment]
Closing this as the associated PR has been merged,
thanks for pointing this out ^^
