### ISSUE TITLE
[BUG] Link in README to quickstart points to wrong page

### ISSUE THREAD

**Issue by UnsignedArduino** [interactions-py/interactions.py#789]
### Describe the bug.

The link in the README that goes to the quickstart points to https://discord-interactions.rtfd.io/en/latest/quickstart.html while I think it should be https://interactionspy.readthedocs.io/en/latest/quickstart.html

### List the steps.

Click on the link in the README under "Where do I start?" that goes to the quickstart. (https://github.com/interactions-py/library#where-do-i-start)

### What you expected.

The correct quick start page. 

### What you saw.

The wrong quick start page. In Google Chrome, it also complains that it is a phishing site:
![A really red picture of Google Chrome saying that it is a deceptive site](https://user-images.githubusercontent.com/38868705/168497626-fbca0048-c2e1-436a-a006-a4796c276772.png)

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by i0bs** [comment]
SSL certification from ReadTheDocs is something outside the core development team's control, unfortunately. The best recommendation I can give is for you to proceed by clicking the "Details" button and hitting the "visit this site" hyperlink.

If at any time this becomes an inconvenience, here are some additional aliases that are used:

https://interactionspy.rtfd.io/
https://discord-py-slash-command.readthedocs.io/en/latest/

The second link is updated pending on discretion of the project maintainer. The primary link given in this repository is the most accurate.
