### ISSUE TITLE
Infer options when not provided from function arguments

### ISSUE THREAD

**Issue by jordanbertasso** [interactions-py/interactions.py#79]
It would be good if there was a default implementation for argument options when they are not provided.

For example, the argument name and description will just be the name of the function parameter and the type can be obtained by checking the type annotation.

I have a rough implementation of this on my fork https://github.com/jordanbertasso/discord-py-slash-command/commit/2e30a16803ca13a81d1c8f67c9d1b9f18a20e2d9

Thanks for creating this project btw.

Let me know what you think!

**Comment by eunwoo1104** [comment]
It is actually added on previous pull request: #64

**Comment by MrSpinne** [comment]
Since the new release will pass arguments kwargs, this seems unnecessary. If an argument is then not passed, you can simply use Python's default arguments.
