### ISSUE TITLE
Attempting to make an more complex command with this extension

### ISSUE THREAD

**Issue by Waspyeh** [interactions-py/interactions.py#8]
The code:
```
@self.slash.slash(name="away")
 async def _away(ctx: SlashContext):
     await ctx.send(content=f"Interaction received. {}")
```
What I am trying to accomplish
https://waspy.sheri.bot/2020/12/16/SUd4
I am trying to receive the option "Message". How would I do this?

Reading the docs, subcommands are not yet implemented?

**Comment by Leastrio** [comment]
You would have to add a parameter named message.

**Comment by thomaskeig** [comment]
> You would have to add a parameter named message.

How would you do that, I'm having the same issue.

**Comment by Leastrio** [comment]
For what Waspyeh is trying to do, this is how it would look like:
```
@self.slash.slash(name="away")
 async def _away(ctx: SlashContext, message):
     await ctx.send(content=f"Interaction received. {}")
```

**Comment by thomaskeig** [comment]
THANK YOU SO MUCH! THIS LIBRARY IS AMAZING <3

**Comment by Waspyeh** [comment]
> For what Waspyeh is trying to do, this is how it would look like:
> 
> ```
> @self.slash.slash(name="away")
>  async def _away(ctx: SlashContext, message):
>      await ctx.send(content=f"Interaction received. {}")
> ```

I will give this a try

**Comment by Waspyeh** [comment]
> For what Waspyeh is trying to do, this is how it would look like:
> 
> ```
> @self.slash.slash(name="away")
>  async def _away(ctx: SlashContext, message):
>      await ctx.send(content=f"Interaction received. {}")
> ```

```
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "/home/sheri/bot/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/sheri/bot/venv/lib/python3.8/site-packages/discord_slash/client.py", line 291, in on_socket_response
    await selected_cmd["func"](ctx, *args)
TypeError: _away() missing 1 required positional argument: 'message'
```
I want message to be an optional thing so that users can not provide a message to set their away status back to off

**Comment by Waspyeh** [comment]
```
        @self.slash.slash(name="away")
        async def _away(ctx: SlashContext, message):
            await ctx.send(content=f"Interaction received")
            await ctx.send(content=f"{message}")
```
@Leastrio

**Comment by eunwoo1104** [comment]
@Waspyeh try doing like this:
```py
async def _away(ctx: SlashContext, message=None):
```

**Comment by Waspyeh** [comment]
> @Waspyeh try doing like this:
> 
> ```python
> async def _away(ctx: SlashContext, message=None):
> ```

Yeah i figured it out, thanks
