### ISSUE TITLE
[BUG] Being rate-limited for reloading/loading/unloading a Cog

### ISSUE THREAD

**Issue by sami0596** [interactions-py/interactions.py#800]
### Describe the bug.

Almost whenever I reload, load, or unloading a cog, I'm being rate-limited for like 60 secs.
I assume you need to to put a small delay to avoid this

### List the steps.

bot.reload(f"{folder}.{extension}")

### What you expected.

To reload without issues

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
The HTTP client has encountered a per-route ratelimit. Locking down future requests for 57.597 seconds.
```

### What version of the library did you use?

release

### Version specification

4.2.1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
ig its from commands syncing

**Comment by sillyElvy** [comment]
The unstable branch has an argument preventing the deletion of commands on cog removal

**Comment by sami0596** [comment]
> The unstable branch has an argument preventing the deletion of commands on cog removal

What is that supposed to mean? That I wouldn't constantly keep being rate-limited for reloading a cog?

**Comment by sillyElvy** [comment]
> > The unstable branch has an argument preventing the deletion of commands on cog removal
> 
> What is that supposed to mean? That I wouldn't constantly keep being rate-limited for reloading a cog?

Yes, currently it removes all commands of the cog by default. On unstable you can specify `remove_commands=False` into `reload` or `remove` so it does not remove the commands

**Comment by sami0596** [comment]
> > > The unstable branch has an argument preventing the deletion of commands on cog removal
> > 
> > 
> > What is that supposed to mean? That I wouldn't constantly keep being rate-limited for reloading a cog?
> 
> Yes, currently it removes all commands of the cog by default. On unstable you can specify `remove_commands=False` into `reload` or `remove` so it does not remove the commands

But even with unloading / loading, when I haven't done something for a while and then decide to example unload, it would still be rate-limited

**Comment by i0bs** [comment]
You've specified all ways to resolve the extension but it seems to only apply to reloading. This understandably makes sense because you're making a huge bulk call when internally syncing and the bulk overwrite endpoint is much harsher.

How frequent are you reloading the extension?

**Comment by sillyElvy** [comment]
Since the unstable branch has a preventive argument now I'm closing this
