### ISSUE TITLE
[BUG] channel.get_history(limit=n) errors when n > 100

### ISSUE THREAD

**Issue by kojocrash** [interactions-py/interactions.py#802]
### Describe the bug.

When fetching a text channel's history, it errors when limit > 100
`messages = await channel.get_history(limit=200)`

This is because in the source code for `interactions\api\models\channel.py`, the program attempts to get the last element from list `_messages` **before** anything was appended to it:
```
_messages: List[Message] = []
_before: int = None
while limit > 100:
    _msgs = [
        Message(**res, _client=self._client)
        for res in await self._client.get_channel_messages(
            channel_id=int(self.id),
            limit=100,
            before=_before,
        )
    ]
    limit -= 100
    _before = int(_messages[-1].id)

    for msg in _msgs:
        if msg in _messages:
            return _messages
        else:
            _messages.append(msg)
```

Moving `_before = int(_messages[-1].id)` below the for loop fixes the problem:
```
_messages: List[Message] = []
_before: int = None
while limit > 100:
    _msgs = [
        Message(**res, _client=self._client)
        for res in await self._client.get_channel_messages(
            channel_id=int(self.id),
            limit=100,
            before=_before,
        )
    ]
    limit -= 100

    for msg in _msgs:
        if msg in _messages:
            return _messages
        else:
            _messages.append(msg)

    _before = int(_messages[-1].id)
```

### List the steps.

1. Run slash command
2. Fetch context's guild
3. Fetch guild's channels 
4. Iterate the guild's channels `ctx.guild.channels = await ctx.guild.get_all_channels()`
5. If `channel.type == interactions.ChannelType.GUILD_TEXT`, fetch channel's latest messages via 
`messages = await channel.get_history(limit=200)` 

### What you expected.

I expected a list of messages.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "c:\Users\seshu\OneDrive\Documents\MoonBot\kojo-bot-v2\bot.py", line 541, in report
    latestMessage: interactions.Message = await getLastMessage(ctx, reportID)
  File "c:\Users\seshu\OneDrive\Documents\MoonBot\kojo-bot-v2\bot.py", line 186, in getLastMessage
    messages = await channel.get_history(limit=200)
  File "C:\Users\seshu\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\models\channel.py", line 1086, in get_history
    _before = int(_messages[-1].id)
IndexError: list index out of range
```

### What version of the library did you use?

release

### Version specification

4.2.1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
If you want to make a PR don't move the line, it's supposed to be `_msgs`.

**Comment by kojocrash** [comment]
> If you want to make a PR don't move the line, it's supposed to be `_msgs`.

Yes, that's a much better solution. Also I just found that it also errors when running in an empty channel

**Comment by kojocrash** [comment]
oops, I did not mean to close the issue. forgive me it's my first time posting one lol

**Comment by sillyElvy** [comment]
> oops, I did not mean to close the issue. forgive me it's my first time posting one lol

Don't worry

> > If you want to make a PR don't move the line, it's supposed to be `_msgs`.
> 
> Yes, that's a much better solution. Also I just found that it also errors when running in an empty channel

What exactly is the error?

**Comment by kojocrash** [comment]
> What exactly is the error?
```
Traceback (most recent call last):
  File "c:\Users\seshu\OneDrive\Documents\MoonBot\kojo-bot-v2\bot.py", line 539, in report
    latestMessage: interactions.Message = await getLastMessage(ctx, reportID)
  File "c:\Users\seshu\OneDrive\Documents\MoonBot\kojo-bot-v2\bot.py", line 186, in getLastMessage
    messages = await channel.get_history(limit=200)
  File "C:\Users\seshu\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\models\channel.py", line 1086, in get_history
    _before = int(_msgs[-1].id)
IndexError: list index out of range
```

More or less the same thing. Program attempts to get the last message in the list, but the list is empty

**Comment by sillyElvy** [comment]
> > What exactly is the error?
> ```
> Traceback (most recent call last):
>   File "c:\Users\seshu\OneDrive\Documents\MoonBot\kojo-bot-v2\bot.py", line 539, in report
>     latestMessage: interactions.Message = await getLastMessage(ctx, reportID)
>   File "c:\Users\seshu\OneDrive\Documents\MoonBot\kojo-bot-v2\bot.py", line 186, in getLastMessage
>     messages = await channel.get_history(limit=200)
>   File "C:\Users\seshu\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\models\channel.py", line 1086, in get_history
>     _before = int(_msgs[-1].id)
> IndexError: list index out of range
> ```
> 
> More or less the same thing. Program attempts to get the last message in the list, but the list is empty
> 

Alright, I'll make a fix for it
