### ISSUE TITLE
[BUG] Option order not updated on bot restart

### ISSUE THREAD

**Issue by dude-guy-boy** [interactions-py/interactions.py#820]
### Describe the bug.

After changing the order of options in a command decorator, the command is not updated on bot restart.

### List the steps.

1. Create a command such as:

```py
@interactions.extension_command(
    name = "test-command",
    description = "test command",
    scope = DEV_GUILD,
    options = [
        interactions.Option(
            name = "regular_option",
            description = "one",
            type = interactions.OptionType.STRING,
            required = True,
        ),
        interactions.Option(
            name = "regular_option_2",
            description = "two_abcd",
            type = interactions.OptionType.STRING,
            required = True,
        )
    ]
)
async def test_cmd(self, ctx, regular_option, regular_option_2):
    print(regular_option, regular_option_2)
```

2. Run the bot
3. See that the command now exists
4. Change the order of options in the command such as:

```py
@interactions.extension_command(
    name = "test-command",
    description = "test command",
    scope = DEV_GUILD,
    options = [
        interactions.Option(
            name = "regular_option_2",
            description = "two_abcd",
            type = interactions.OptionType.STRING,
            required = True,
        ),
        interactions.Option(
            name = "regular_option",
            description = "one",
            type = interactions.OptionType.STRING,
            required = True,
        )
    ]
)
async def test_cmd(self, ctx, regular_option_2, regular_option):
    print(regular_option, regular_option_2)
```

5. Restart the bot
6. See that the command is still shown with the options in their original order, not the new one
7. Reload / Refresh client
8. See that its still shown with the original option order

### What you expected.

When the bot is restarted the option order for the command should be updated

### What you saw.

When the bot is restarted the option order is not updated

### What version of the library did you use?

unstable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by pa-long** [comment]
Yes i issues too with updating command groups and options, a quick fix for now that works for me : 
1. Stop the bot 
2. Change the name of the command, in your case : from `name = "test-command",` to `name = "test-command_2",` 
3. Run the bot then stop it again when it's ready.
4. Change the name back to `name = "test-command",`  
5. Run the bot again.

**Comment by i0bs** [comment]
Our internal sync calls only check for if the identity of data has changed for fields existent when modifying, and not the relational placement

**Comment by dude-guy-boy** [comment]
> Our internal sync calls only check for if the identity of data has changed for fields existent when modifying, and not the relational placement

I think it should be added in future, because it can also sometimes cause the bot to not be able to run, if I remember correctly i think in the case of switching order of autocomplete options in a subcommand, I believe I mentioned it in #stable on discord before

**Comment by i0bs** [comment]
Thank you for the suggestion. I'll pass the word up to our core development team and see where things will go next 👍
