### ISSUE TITLE
ctx.edit() doesnt return anything

### ISSUE THREAD

**Issue by catfo435** [interactions-py/interactions.py#83]
`ctx.edit()` uses` ctx._http.edit()` which returns the result of the PATCH when executed, but `ctx.edit()` doesnt return that, pls change that

**Comment by quirky-bluejay** [comment]
There is no `ctx.edit`, are you talking about `SlashMessage.edit` ?

**Comment by catfo435** [comment]
> There is no `ctx.edit`, are you talking about `SlashMessage.edit` ?

No,I meant `SlashContext.edit`

**Comment by quirky-bluejay** [comment]
Can you send a link to that. I **cannot** find that

**Comment by catfo435** [comment]
Hmm.. It's not there in this GitHub repository. It's there in the code in my computer installed through pip

I used `pip install -U discord-py-slash-command`

**Comment by quirky-bluejay** [comment]
That's the release version, not the development version that is what is on `master`

**Comment by catfo435** [comment]
> That's the release version, not the development version that is what is on `master`

Oh ok. Thanks.

**Comment by quirky-bluejay** [comment]
Also I'm pretty sure that the PATCH request doesn't return anything, or just returns the status code

**Comment by catfo435** [comment]
I want to add a reaction to the message I sent via `await ctx.send()`, so I was suggested to send a PATCH which will return the message, then with that I can add a reaction to the message.

thought of trying it using this module

**Comment by quirky-bluejay** [comment]
@PranavP435 had another look at `http.SlashRequest.edit` and I'm pretty sure it doesn't return the response from Discord, it returns a coroutine to be awaited in the function where the call to `http.SlashRequest.edit` was made

**Comment by quirky-bluejay** [comment]
> I want to add a reaction to the message I sent via `await ctx.send()`, so I was suggested to send a PATCH which will return the message, then with that I can add a reaction to the message.
> 
> 

Again I'm pretty sure that a PATCH request to a webhook message won't return anything (discord doesn't say if it returns or not [here](https://discord.com/developers/docs/resources/webhook#edit-webhook-message) , slash messages are webhook messages effectively)
I'm not too sure what they were trying to say.
To react on a message you'll need a message object, a bot user in the guild, and the bot must have the required perms
Ctx.send won't currently get you a message object, thats planned in v1.0.9

**Comment by eunwoo1104** [comment]
`ctx.edit` shouldn't return anything, even discord.py's `.edit` doesn't. `ctx.send` will return the message, but it is not implemented on the release version but on the GitHub master branch.
