### ISSUE TITLE
Allow passing of types to discord_slash.utils.manage_commands.create_option

### ISSUE THREAD

**Issue by issy** [interactions-py/interactions.py#84]
It would be nice to be able to pass a type, such as `str` or `discord.Role` to the `option_type` argument of the function `discord_slash.utils.manage_commands.create_option`
There may be other functions within that module which this could apply to, I haven't checked in depth. All it would need to do is map the type to an integer. For example: `str` would be `3`

**Comment by spinnerich** [comment]
This will be implemented in the next release.

**Comment by quirky-bluejay** [comment]
Correct me if I'm wrong, but as far as I know getting options from the type hints of a function is planned.
They are talking about `discord_slash.utils.manage_commands.create_option` which currently doesn't accept `str, int, discord.[...] etc` as the `option_type` argument on the dev branch.
I haven't seen anything planned *specifically* about this

**Comment by spinnerich** [comment]
`model.SlashCommandOptionType.from_type(str)` -> would return string type which can be set in `create_option`

**Comment by i0bs** [comment]
Building on this, I wish `model.SlashCommandOptionType` received a concatenation to `OptionType`. Pretty redundant to repeat something already known in the model script when it's an enum type.

**Comment by spinnerich** [comment]
I don't know if @eunwoo1104 wants to change that. Alternatively, you could just do `import discord_slash.model.SlashCommandOptionType as OptionType`.

**Comment by quirky-bluejay** [comment]
Would integrating `SlashCommandOptionType` into `create_option` be a possible idea?
so that you don't have to do `create_option(option_type=SlashCommandOptionType.from_type(type), [...])`

**Comment by eunwoo1104** [comment]
> This will be implemented in the next release.

This is not planned feature.

> Would integrating `SlashCommandOptionType` into `create_option` be a possible idea?
> so that you don't have to do `create_option(option_type=SlashCommandOptionType.from_type(type), [...])`

This seems to be the good idea. I'll implement this when I get some times.

**Comment by eunwoo1104** [comment]
Patched on #86 and will be included at next release.
