### ISSUE TITLE
[REQUEST] Add proxy param for interactions.Client

### ISSUE THREAD

**Issue by JoinChang** [interactions-py/interactions.py#840]
### Describe the feature.

In some areas, we can't directly connect to Discord server, so we need proxy.

In discord.py, we use the code below to connect proxy server:
```py
bot = commands.Bot(..., proxy="http://127.0.0.1:7890")
```
or
```py
client = discord.Client(
    connector=ProxyConnector(
        proxy_type=ProxyType.SOCKS5,
        host='127.0.0.1',
        port=7890,
        rdns=True
    ),
    ...
)
client.run(BOT_TOKEN)
```

I think in interactions.py, we can use the code below to connect:
```py
interactions.Client(BOT_TOKEN, proxy="http://127.0.0.1:7890")
```

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by V3ntus** [comment]
I think this is a good idea. It could also assumably be added in an ext

**Comment by V3ntus** [comment]
Heyya! I've went and written an implementation. If you would like to test out this functionality, checkout #871 and lmk if you run into problems 👍🏾
