### ISSUE TITLE
[BUG] 24 is not a valid MessageType

### ISSUE THREAD

**Issue by rlaphoenix** [interactions-py/interactions.py#859]
### Describe the bug.

When a message gets blocked by Discord Content Moderation Beta it will send Message Type 24 which isn't currently registered and therefore panics.

### List the steps.

1. Open Discord Server Settings
2. Enter ![Content Moderation](https://user-images.githubusercontent.com/17136956/173976566-951a2f8c-521f-404b-a3cd-8ef2ab51b70a.png) tab
3. Block some words
![image](https://user-images.githubusercontent.com/17136956/173976607-d51f9d73-a1f6-4f93-a5b2-6410b5fdc69f.png)
4. Type the blocked words in a channel the bot has access to.

### What you expected.

I expect it to gracefully ignore or handle the Message Type.

In the future, it should add a graceful error handler for messages that do not have a supported MessageType as this kind of change could happen many times in the future.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  ...
  File "C:\Users\Justin\Projects\private\.venv\lib\site-packages\interactions\client\bot.py", line 124, in start
    self._loop.run_until_complete(self._ready())
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Justin\Projects\private\.venv\lib\site-packages\interactions\client\bot.py", line 363, in _ready
    await self._login()
  File "C:\Users\Justin\Projects\private\.venv\lib\site-packages\interactions\client\bot.py", line 368, in _login
    await self._websocket._establish_connection(self._shard, self._presence)
  File "C:\Users\Justin\Projects\private\.venv\lib\site-packages\interactions\api\gateway\client.py", line 189, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "C:\Users\Justin\Projects\private\.venv\lib\site-packages\interactions\api\gateway\client.py", line 257, in _handle_connection
    self._dispatch_event(event, data)
  File "C:\Users\Justin\Projects\private\.venv\lib\site-packages\interactions\api\gateway\client.py", line 390, in _dispatch_event
    self._dispatch.dispatch(f"on_{name}", __obj(**data))  # noqa
  File "C:\Users\Justin\Projects\private\.venv\lib\site-packages\interactions\api\models\message.py", line 267, in __init__
    self.type = MessageType(self.type) if self._json.get("type") else None
  File "C:\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 24 is not a valid MessageType
```

### What version of the library did you use?

stable

### Version specification

4.2.1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by rlaphoenix** [comment]
I thought I would also post a message JSON:

```
{'type': 24, 'tts': False, 'timestamp': '2022-06-16T02:19:10.998000+00:00', 'pinned': False, 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['956263275887218808', '981189079263764530', '970332150891155607'], 'premium_since': None, 'pending': False, 'nick': '<redacted>', 'mute': False, 'joined_at': '2022-03-25T22:48:57.246000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': '2022-04-02T03:16:14.258000+00:00', 'avatar': None}, 'id': '<redacted>', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '', 'components': [], 'channel_id': '<redacted>', 'author': {'username': '<redacted>', 'public_flags': 0, 'id': '<redacted>', 'discriminator': '9990', 'avatar_decoration': None, 'avatar': '<redacted>'}, 'attachments': [], 'guild_id': '<redacted>', '_client': <interactions.api.http.client.HTTPClient object at 0x000001B126B329D0>}
```

**Comment by rlaphoenix** [comment]
I would also like to mention a very minimal change of just adding `CONTENT_MODERATION = 24` to MessageType with no other change at all seems to work fine. However, I'm not sure in what context Message object will be used so I cannot say it's a full-fledged fix. I have not read the code enough to say that.

**Comment by V3ntus** [comment]
Is this implemented in unstable?

**Comment by rlaphoenix** [comment]
> Is this implemented in unstable?

It is not implemented as of latest stable nor latest unstable branches:

stable: https://github.com/interactions-py/library/blob/stable/interactions/api/models/message.py#L37=  
unstable: https://github.com/interactions-py/library/blob/unstable/interactions/api/models/message.py#L71=

**Comment by FayeDel** [comment]
Hiya!

Currently, the message type points to an undocumented feature in Discord's side of things, but there's already a PR (#768) made to interface with automod, including the messagetype. Moreover, there may also be an unstable PR on the side (talked about at #unstable in the support server) that may deal with conversion issues like this that can also deal with the issue in a different approach.

**Comment by FayeDel** [comment]
Closing this issue as the AutoMod PR has been merged, docs are reflected and as per the issue, the MessageType is defined ^^
