### ISSUE TITLE
[BUG] Sometimes missing channel id and message id in message when ctx.send/edit

### ISSUE THREAD

**Issue by Toricane** [interactions-py/interactions.py#870]
### Describe the bug.

When trying to send message, edit interaction, or edit message, message id and channel id is sometimes missing. Usually it's always missing when ctx.send, but sometimes it's missing when edit, reported by paginator ext users

### List the steps.

1. Make a command
2. Try to send and edit:
```py
msg = await ctx.send("test")
print(msg.id, msg.channel_id)
msg = await ctx.edit("edit")
print(msg.id, msg.channel_id)
await msg.edit("test")
print(msg.id, msg.channel_id)
```

### What you expected.

Message should always have message and channel IDs 
```py
msg = await ctx.send("test")
print(msg.id, msg.channel_id)
msg = await ctx.edit("edit")
print(msg.id, msg.channel_id)
await msg.edit("test")
print(msg.id, msg.channel_id)
```

### What you saw.

Instead this happens
```py
None None
987906535692849182 862150987288412170
987906535692849182 862150987288412170
```
Sometimes it also occurs when ctx.edit or msg.edit, from reports of paginator ext users

### What version of the library did you use?

unstable

### Version specification

Happens in stable, in unstable, and in 4.3 beta 1

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by AstreaTSS** [comment]
Narrowed down the scope of this bug due to the fact that neither me nor Delta can reproduce it. It seems to only trigger 100% of the time on some devices and near 0% of the time on others.

This is very likely due to how `interactions.py` tries to get the message object when sending without deferring.
