### ISSUE TITLE
[BUG] Log Error for event logging (UnicodeEncodeError)

### ISSUE THREAD

**Issue by Donbur4156** [interactions-py/interactions.py#904]
### Describe the bug.

When starting the Bot in logging.DEBUG mode, some (especially GUILDE_CREATE) Events raise a Log Error.
`UnicodeEncodeError: 'charmap' codec can't encode character`

### List the steps.

1. start the bot
2. logging error in terminal

### What you expected.

The Event should be logged in the logging file.

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "C:\...\Python38\lib\logging\__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
  File "C:\...\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2b50' in position 54566: character maps to <undefined>

[.......]

File "c:\...\.venv\lib\site-packages\interactions\api\gateway\client.py", line 256, in _handle_connection
    log.debug(f"{event}: {str(data)}")
```

### What version of the library did you use?

stable

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Donbur4156** [comment]
The following fix is working for me:

interactions>api>gateway>client.py line 256
WebsocketClient --> _handle_connection
log.debug(f"{event}: {str(data).encode('utf-8')}")

**Comment by Toricane** [comment]
Closing since the PR linked above resolved this issue.
