### ISSUE TITLE
[BUG] no VoiceState in interactions

### ISSUE THREAD

**Issue by Nick-the-Descended** [interactions-py/interactions.py#966]
### Describe the bug.

I was trying to write a bot with interactions for the first time, installed it with `pip install discord-py-interactions` switching from discord.py and met with some errors. module interactions has no attribute VoiceState is being output to the console every time a voice channel has any change, eg: someone joins/leaves, mutes/unmutes...

### List the steps.

import interactions # import interactions
cli = Client(token="...") # create client
cli.start() # start client

let anyone mute/unmute in the voice channel, the error is output in the console

### What you expected.

Expected for the bot to run without any errors since it only has 3 lines of code without any functionality 

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
The HTTP client has exhausted a per-route ratelimit. Locking route for 1.0 seconds.
An error occured dispatching voice_state_update: module 'interactions' has no attribute 'VoiceState'
An error occured dispatching voice_state_update: module 'interactions' has no attribute 'VoiceState'
An error occured dispatching voice_state_update: module 'interactions' has no attribute 'VoiceState'
          ^
...
```
this doesn't crush the bot, but still annoying to see it spammed occured, also there is a type in the error (occured -> occurred) 

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
Hi! This is not a bug since the library natively doesn't support voice. For voice you should have a look at this: httos://github.com/interactions-py/voice
