### ISSUE TITLE
[BUG] Error when modifying options in a subcommand

### ISSUE THREAD

**Issue by dude-guy-boy** [interactions-py/interactions.py#989]
### Describe the bug.

When adding/modifying an option to an existing subcommand, I received an `Invalid Form Body` error that caused the bot to not start. A different subcommand under the same command contains autocomplete options, which may or may not be related to this issue (I believe this is the same bug as in issue #880, although it gives a different error message).

### List the steps.

Same as #880.

### What you expected.

When I add/modify an option in the subcommand, the bot should start as usual with the command updated to use the new/modified option.

### What you saw.

When adding a new option to an existing subcommand I get the following error:

```Invalid Form Body
Could not prepare the client:
Traceback (most recent call last):
  File "/Users/usr/github/bot/venv/lib/python3.10/site-packages/interactions/client/bot.py", line 380, in _ready
    await self.__sync()
  File "/Users/usr/github/bot/venv/lib/python3.10/site-packages/interactions/client/bot.py", line 657, in __sync
    res = await self._http.overwrite_application_command(
  File "/Users/usr/github/bot/venv/lib/python3.10/site-packages/interactions/api/http/interaction.py", line 92, in overwrite_application_command
    return await self._req.request(Route("PUT", url), json=data)
  File "/Users/usr/github/bot/venv/lib/python3.10/site-packages/interactions/api/http/request.py", line 174, in request
    raise LibraryException(
interactions.api.error.LibraryException: Invalid Form Body (code: 50035, severity 40)
Error at 39: APPLICATION_COMMANDS_DUPLICATE_NAME - Application command names must be unique
```

The same command has autocomplete options in a different subcommand, not sure if that affects this (I know there have been similar autocomplete issues in past)

### What version of the library did you use?

release

### Version specification

4.3.0

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by Damego** [comment]
Heya. Does this bug still exists on the latest verson? After completing these steps I didn't get any errors
