### ISSUE TITLE
[REQUEST&BUG] Missing Acess 

### ISSUE THREAD

**Issue by CaedenPH** [interactions-py/interactions.py#996]
### Describe the feature.

```
Your bot is missing access to guild with corresponding id 111111111111111! Adding commands will not be possible until it is invited with `application.commands` scope
```
This is spammed in console a couple hundred times, with the guild id's. How is this silenced?

### Code of Conduct

- [X] I agree to follow the contribution requirements.

**Comment by sillyElvy** [comment]
Hi! I can understand your issue. Since it is `log.warning`, using

```py
from logging import basicConfig, CRITICAL


basicConfig(level=CRITICAL)
```
should fix your issue

**Comment by CaedenPH** [comment]
> Hi! I can understand your issue. Since it is `log.warning`, using
> 
> ```python
> from logging import basicConfig, CRITICAL
> 
> 
> basicConfig(level=CRITICAL)
> ```
> 
> should fix your issue

This is a bit annoying, could there be an option in the client instance to silence these warnings?

**Comment by sillyElvy** [comment]
> > Hi! I can understand your issue. Since it is `log.warning`, using
> > ```python
> > from logging import basicConfig, CRITICAL
> > 
> > 
> > basicConfig(level=CRITICAL)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should fix your issue
> 
> This is a bit annoying, could there be an option in the client instance to silence these warnings?

It could be done, although it is very low priority and it would be made faster if you'd make a PR yourself tbh

**Comment by sillyElvy** [comment]
Update:
------------

![grafik](https://user-images.githubusercontent.com/88881326/186231595-7da474b5-41d4-4357-9f38-03a344d88d50.png)


This means the issue should just go away on its own.

Source message: https://canary.discord.com/channels/789032594456576001/801461008865951784/1011376069695250494
if you are not in that server: https://discord.gg/discord-developers
